# Lightning Round - Basic Features and Commands 

---

In this notebook, we go through basic constructs and commands.

## Competences 

The user should know to start `Julia` in various modes (command line prompt, `IJulia`), how to exit, learn some features and be able to write simple programs.

## Credits

This notebook is based on the [slides](https://github.com/JuliaLang/julia-tutorial/tree/master/LightningRound) accompanying  the Lightning Round [video]( https://www.youtube.com/watch?v=37L1OMk_3FU&feature=player_embedded#at=33) by [Alan Edelman](http://www-math.mit.edu/~edelman/index.php), all part of the [Julia Tutorial](https://github.com/JuliaLang/julia-tutorial).

## Julia resources

Julia resources are accessible through the [Julia home page](http://julialang.org).

Please check `packages`, `docs` and `juliacon` (_here you will also find links to videos from previous conferences_).


## Execution
To execute cell use `Shift + Enter` or press `Play` (__Run cell__).

To run all cells in the notebook go to `Cell` -> `Run All` 

## Markdown cells

Possibility to write comments / code / formulas in `Markdown` cells, makes Jupyter notebooks ideal for teaching and research. Text is written using _Julia Markdown_, which is _GitHub Markdown_ with additional understanding of basic `LaTeX`.

[Mastering (GitHub) Markdown](https://guides.github.com/features/mastering-markdown/) is a 3-minute read, another short and very good manual is at http://daringfireball.net/projects/markdown/.

Some particulars of Julia Markdown are described in 
[Documentation](http://docs.julialang.org/en/release-0.4/manual/documentation/) section of Julia Manual, yet another 3-minute read.

## `nbconvert`

It is extremely easy to convert notebooks to slides, LaTeX, or PDF.
For details see the 
[documentation](https://nbconvert.readthedocs.org/en/latest/usage.html).

### Slides

Clicking `View` -> `Cell Toolbar` -> `Slideshow` opens the `Slide Type` menu for each cell.

The slideshow is made with the command

`jupyter nbconvert --to slides notebook.ipynb`

The slideshow is displayed in browser with the command

`jupyter nbconvert --to slides --post serve notebook.ipynb`


### LaTeX

`jupyter nbconvert --to latex notebook.ipynb`

###  PDF 

`jupyter nbconvert --to PDF notebook.ipynb`

N.B. For the above conversions [Pandoc](http://pandoc.org/installing.html) needs to be installed.

## Which version of `Julia` is running?

In [1]:
versioninfo()

Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)


## Quitting

__Exiting__ from `julia>` or __restarting kernel__ in `IJulia`

In [2]:
# exit()

## Documentation

Documentation is well written and the starting point is http://docs.julialang.org/en/latest/

But, also remeber that `Julia` is __open source__ and all routines are available on [GitHub](http://github.com). You will learn how to make full use of this later in the course.

## Punctuation review

* `[...]` are for indexing, array constructors and __Comprehensions__
* `(...)` are __required__ for functions `quit()`, `tic()`, `toc()`, `help()` 
* `{...}` are for arrays
* `#` is for comments

## Basic indexing

In [3]:
A=rand(5,5) # Matrix with random entries between 0 and 1

5×5 Array{Float64,2}:
 0.0558188  0.325981   0.474978   0.586668   0.302188
 0.839967   0.995527   0.896092   0.0620054  0.106392
 0.633328   0.0620299  0.076536   0.761643   0.88815 
 0.323627   0.0204637  0.571532   0.458611   0.7353  
 0.911095   0.433011   0.0220353  0.748857   0.746437

In [4]:
A[1,1]

0.055818837156181855

In [5]:
rand(5,5)[1:2,3:4] # You can even do this

2×2 Array{Float64,2}:
 0.297148  0.157102
 0.688635  0.612065

### Indexing is elegant

If you want to compute the lower right $2\times 2$ block of $A^{10}$, in most languages you need to first compute $B=A^{10}$ and then index into $B$. In Julia, the command is simply

In [6]:
(A^10)[4:5,4:5] # Parenthesses around A^10 are necessary

2×2 Array{Float64,2}:
 1173.18  1230.25
 1551.83  1627.33

### Comprehensions - elegant array constructors

In [7]:
[i for i=1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [8]:
[trace(rand(n,n)) for n=1:5]

5-element Array{Float64,1}:
 0.455754
 0.516248
 1.03447 
 3.82181 
 2.10054 

In [9]:
x=1:10

1:10

In [10]:
[ x[i]+x[i+1] for i=1:9 ]

9-element Array{Int64,1}:
  3
  5
  7
  9
 11
 13
 15
 17
 19

In [11]:
z = [eye(n) for n=1:5]  # z is Array of Arrays

5-element Array{Array{Float64,2},1}:
 [1.0]                                                                           
 [1.0 0.0; 0.0 1.0]                                                              
 [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0]                                         
 [1.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0; 0.0 0.0 1.0 0.0; 0.0 0.0 0.0 1.0]            
 [1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0]

In [12]:
z[1] # First element is a 1x1 Array

1×1 Array{Float64,2}:
 1.0

In [13]:
z[4] # What is the fourth element?

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [14]:
A=[ i+j for i=1:5, j=1:5 ] # Another example of a comprehension

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [15]:
B=[ i+j for i=1:5, j=1.0:5 ] # Notice the promotion

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

## Commands `ndims()` and `typeof()`

In [16]:
ndims(ans)

2

In [17]:
ndims(z) # z is a one-dimensional array

1

In [18]:
typeof(z) # Array of Arrays

Array{Array{Float64,2},1}

In [19]:
typeof(z[5]) # z[5] is a two-dimensional array

Array{Float64,2}

In [20]:
typeof(A)

Array{Int64,2}

## Vectors are 1-dimensional arrays

See [Multi-dimensional arrays](http://julia.readthedocs.org/en/latest/manual/arrays/) for more.

In [21]:
v=rand(5,1) # This is 2-dimensional array

5×1 Array{Float64,2}:
 0.745208
 0.933832
 0.255117
 0.185157
 0.687036

In [22]:
vv=vec(v) # This is an 1-dimensional array or vector

5-element Array{Float64,1}:
 0.745208
 0.933832
 0.255117
 0.185157
 0.687036

In [23]:
v.==vv  # Notice that they are different

5×1 BitArray{2}:
 true
 true
 true
 true
 true

In [24]:
v-vv # Again a promotion

5×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [25]:
w=rand(5) # This is again a vector

5-element Array{Float64,1}:
 0.531707
 0.462179
 0.357671
 0.916109
 0.825718

In [26]:
Mv=[v w] # First column is a 5 x 1 matrix, second column is a vector of length 5

5×2 Array{Float64,2}:
 0.745208  0.531707
 0.933832  0.462179
 0.255117  0.357671
 0.185157  0.916109
 0.687036  0.825718

In [27]:
x=Mv[:,1] # Matrix columns are extracted as vectors

5-element Array{Float64,1}:
 0.745208
 0.933832
 0.255117
 0.185157
 0.687036

In [28]:
y=Mv[:,2]

5-element Array{Float64,1}:
 0.531707
 0.462179
 0.357671
 0.916109
 0.825718

In [29]:
x==v # The types differ

false

In [31]:
# But
x.==v

5×1 BitArray{2}:
 true
 true
 true
 true
 true

In [32]:
y==w

true

### 1D and 2D arrays

In [33]:
w=1.0:5

1.0:1.0:5.0

In [34]:
A*w

5-element Array{Float64,1}:
  70.0
  85.0
 100.0
 115.0
 130.0

In [35]:
w=collect(1.0:5) 

5-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [36]:
A*w  # This returns a 1-dimensional array

5-element Array{Float64,1}:
  70.0
  85.0
 100.0
 115.0
 130.0

In [37]:
A*v # This returns a 2-dimensional array - v is a 5 x 1 array

5×1 Array{Float64,2}:
 10.3604
 13.1667
 15.9731
 18.7794
 21.5858

## Discussion

Such behavior is due to the fact that `Julia` has vectors as a special type. __ Pros? Cons? __
 
What is matrix $\times$ vector?

What is the result of 

$$ C[i,j]=A[i,:]*B[:,j]$$

In [38]:
B=[A[i,:]*A[:,j] for i=1:5, j=1:5]

LoadError: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:138
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Base.ReshapedArray{S,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{S,1},SubArray{S,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at linalg\matmul.jl:79
  *(::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, ::AbstractArray{T,1}) at linalg\triangular.jl:1496
  ...

In [39]:
# Rows and columsn are both 1D vectors - must use dot product
B=[A[i,:]⋅A[:,j] for i=1:5, j=1:5]

5×5 Array{Int64,2}:
  90  110  130  150  170
 110  135  160  185  210
 130  160  190  220  250
 150  185  220  255  290
 170  210  250  290  330

In [40]:
inv(B)

5×5 Array{Float64,2}:
  8.79609e12   1.75922e13  -3.51844e13  -1.75922e13   2.63883e13
 -2.63883e13  -0.421875     3.51844e13   3.51844e13  -4.39805e13
  1.75922e13  -3.51844e13   3.51844e13  -3.51844e13   1.75922e13
  8.79609e12  -0.0         -3.51844e13   3.51844e13  -8.79609e12
 -8.79609e12   1.75922e13   0.0         -1.75922e13   8.79609e12

## `ones()`, `eye()` and `zeros()`
   
Notice that the output type depends on the argument. This is a general Julia feature called `Multiple dispatch` 
and will be explained later in more detail. 

In [41]:
ones(3,5), ones(5), ones(rand(1:3,4,6)) 
# The output type depends on the argument. Float64 is the default.

(
[1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0],

[1.0,1.0,1.0,1.0,1.0],
[1 1 … 1 1; 1 1 … 1 1; 1 1 … 1 1; 1 1 … 1 1])

In [42]:
rand(1:3,4,6)

4×6 Array{Int64,2}:
 3  2  3  3  3  3
 3  3  3  1  3  1
 1  1  1  2  2  1
 2  1  1  3  2  1

In [43]:
zeros(3,5), zeros(5), zeros(rand(1:3,4,6))

(
[0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0],

[0.0,0.0,0.0,0.0,0.0],
[0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0; 0 0 … 0 0])

In [44]:
eye(4), round(Int64,eye(4)), round(Int32,eye(4)), complex(eye(4)) 
# type can also be set

(
[1.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0; 0.0 0.0 1.0 0.0; 0.0 0.0 0.0 1.0],

[1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1],

Int32[1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1],

Complex{Float64}[1.0+0.0im 0.0+0.0im 0.0+0.0im 0.0+0.0im; 0.0+0.0im 1.0+0.0im 0.0+0.0im 0.0+0.0im; 0.0+0.0im 0.0+0.0im 1.0+0.0im 0.0+0.0im; 0.0+0.0im 0.0+0.0im 0.0+0.0im 1.0+0.0im])

## Complex numbers

`i` is too valuable symbol for loops, so Julia uses `im` for the complex unit. 

In [45]:
im

im

In [46]:
2im

0 + 2im

In [47]:
typeof(ans)

Complex{Int64}

In [48]:
typeof(2.0im)

Complex{Float64}

In [49]:
complex(3,4) # Another way of defining complex numbers

3 + 4im

In [50]:
complex(3,4.0) # If one of the arguments if Float64, so is the entire number

3.0 + 4.0im

In [51]:
sqrt(-1) # This produces an error (like in any other language),

LoadError: DomainError:
sqrt will only return a complex result if called with a complex argument. Try sqrt(complex(x)).

In [52]:
sqrt(complex(-1))  # and this is fine.

0.0 + 1.0im

## Ternary operator
Let us define our version of the sign function

In [53]:
si(x) = (x>0) ? 1 : -1

si (generic function with 1 method)

In [54]:
si(-13)

-1

This is equivalent to:

In [55]:
function si(x)
    if x>0
        return 1
    else
        return -1
    end
end

si (generic function with 1 method)

Any) in module Main at In[53]:1 overwritten at In[55]:2.


In [56]:
si(pi-8), si(0), si(0.0)

(-1,-1,-1)

The expressions can be nested:

In [57]:
si(x) = (x>0) ? 1 : ((x<0) ? -1: 0) # now si(0) is 0

si (generic function with 1 method)

 in module Main at In[55]:2 overwritten at In[57]:1.


In [58]:
si(π-8), si(0) # '\pi Tab' produces π and means π

(-1,0)

## Typing
Special mathematical (LaTeX) symbols can be used (like $\alpha$, $\Xi$, $\pi$, $\oplus$, $\cdot$, etc.). The symbol in both, the notebook and command line version, is produced by writing 
LaTeX command followed by `Tab` 

In [59]:
Ξ = 8; Ψ  = 6; Γ = Ξ ⋅ Ψ

48

In [60]:
typeof(Γ)

Int64

## Writing a program and running a file

Special feature of Julia is that the results of commands are not displayed, unless explicitely required. 

To display results you can use commands `@show` or `println()` (or many others, see the [Text I/O](http://julia.readthedocs.org/en/latest/stdlib/base/?highlight=print#text-i-o) in the manual.)

Consider the file `deploy.jl` with the following code
```julia
n=int(ARGS[1])          # take one integer argument
println(rand(1:n,n,n))  # generate and print n x n matrix of random integers between 1 and n
@show b=3               # set b to 3 and show the result
c=4                     # set c to 4
```
Running the program in the shell gives
```julia
$ julia deploy.jl 5
[1 3 2 4 1
 5 3 1 1 4
 5 4 2 2 5
 3 1 2 3 4
 4 4 5 4 4]
b = 3 => 3
```
Notice that the result of the last command (_c_) is not displayed.

>You can, of course, also run the above command in the `Console` tab of `JuliaBox`. To do this, you first have to change the directory
```
cd Julia-Course/src
```

Similarly, the program can be converted to executable and run directly, 
without referencing `julia` in the command line.
The refernece to `julia` must be added in the first line, as in the file `deploy1.jl`:
```julia
#!/usr/bin/julia
n=int(ARGS[1])
println(rand(1:n,n,n))
@show b=3
c=4
```
In the shell do:
```
$ chmod +x deploy1.jl
$ ./deploy1.jl 5
[4 5 3 2 5
 4 2 1 5 1
 3 2 4 5 1
 2 4 4 3 1
 3 4 5 3 3]
b = 3 => 3
```
Finally, to run the same program in `julia` shell or `IJulia`, the input has to be changed, as in the file `deploy2.jl`:
```julia
n=int(readline(STDIN))
println(rand(1:n,n,n))
@show b=3
c=4
```
__Notice that now the result of the last line is displayed by default__  - in this case it is `4`, the values of `c`. The output of the random matrix and of `b` is forced.

In [61]:
include("deploy2.jl")

STDIN> 5
[3 2 2 5 3; 5 3 4 2 2; 2 1 4 3 4; 4 2 4 3 4; 5 3 3 4 3]
b = 3 = 3


4

## Running external programs and unix pipe

### `run()` - calling external program

In [62]:
?run

search: run trunc truncate round rounding RoundUp RoundDown RoundToZero



```
run(command)
```

Run a command object, constructed with backticks. Throws an error if anything goes wrong, including the process exiting with a non-zero status.


Notice, that this is not a gret help, Julia has much better commands for this.

In [63]:
# This calls the unix Calendar program
# run(`cal`)

In [64]:
# The pipe is '|>' instead of usual '|'
# run(pipeline(`cal`,`grep Sa`)) 

### `ccall()` - calling `C` program

In [65]:
?ccall

search: ccall AbstractChannel



```
ccall((symbol, library) or function_pointer, ReturnType, (ArgumentType1, ...), ArgumentValue1, ...)
```

Call function in C-exported shared library, specified by `(function name, library)` tuple, where each component is a string or symbol.

Note that the argument type tuple must be a literal tuple, and not a tuple-valued variable or expression. Alternatively, `ccall` may also be used to call a function pointer, such as one returned by `dlsym`.

Each `ArgumentValue` to the `ccall` will be converted to the corresponding `ArgumentType`, by automatic insertion of calls to `unsafe_convert(ArgumentType, cconvert(ArgumentType, ArgumentValue))`. (See also the documentation for each of these functions for further details.) In most cases, this simply results in a call to `convert(ArgumentType, ArgumentValue)`.


In [66]:
# Simple version
t=ccall(:time,Int32,())

1492611339

In [67]:
typeof(t)

Int32

In [68]:
# With pointers
t=ccall(:clock,Cstring,())

Cstring(0x0000000000022390)

In [69]:
# Human readable version, does now work well in Win
# unsafe_string(t)

In [70]:
# With specifying the library
bytestring(ccall((:clock,"libc"), Ptr{UInt8}, ())) 

LoadError: error compiling anonymous: could not load library "libc"
The specified module could not be found.


## `Task()`, `produce()` and `consume()` 
`Julia` has  a control flow feature that allows computations to be suspended 
and resumed in a flexible manner (see
[tasks](http://julia.readthedocs.org/en/latest/manual/control-flow/#man-tasks) in the manual).

In [71]:
function stepbystep()
    for n=1:3
        produce(n^2)
    end
end

stepbystep (generic function with 1 method)

In [72]:
p=Task(stepbystep)

Task (runnable) @0x0000000088151cd0

In [73]:
consume(p)

1

In [74]:
consume(p)

4

In [75]:
consume(p) 

9

In [76]:
consume(p) # Guess what comes next?