# Lightning Round - Basic Features and Commands 

---

In this notebook, we go through basic constructs and commands.

## Competences 

The user should know to start `Julia` in various modes (command line prompt, `IJulia`), how to exit, learn some features and be able to write simple programs.

## Credits

This notebook is based on the [slides](https://github.com/JuliaLang/julia-tutorial/tree/master/LightningRound) accompanying  the Lightning Round [video]( https://www.youtube.com/watch?v=37L1OMk_3FU&feature=player_embedded#at=33) by [Alan Edelman](http://www-math.mit.edu/~edelman/index.php), all part of the [Julia Tutorial](https://github.com/JuliaLang/julia-tutorial).

## Julia resources

Julia resources are accessible through the [Julia home page](http://julialang.org).

Please check `packages`, `docs` and `juliacon` (_here you will also find links to videos from previous conferences_).


## Execution
To execute cell use `Shift + Enter` or press `Play` (__Run cell__).

To run all cells in the notebook go to `Cell` -> `Run All` 

## Markdown cells

Possibility to write comments / code / formulas in `Markdown` cells, makes Jupyter notebooks ideal for teaching and research. Text is written using _Julia Markdown_, which is _GitHub Markdown_ with additional understanding of basic `LaTeX`.

[Mastering (GitHub) Markdown](https://guides.github.com/features/mastering-markdown/) is a 3-minute read, another short and very good manual is at http://daringfireball.net/projects/markdown/.

Some particulars of Julia Markdown are described in 
[Documentation](http://docs.julialang.org/en/release-0.4/manual/documentation/) section of Julia Manual, yet another 3-minute read.

## `nbconvert`

It is extremely easy to convert notebooks to slides, LaTeX, or PDF.
For details see the 
[documentation](https://nbconvert.readthedocs.org/en/latest/usage.html).

### Slides

Clicking `View` -> `Cell Toolbar` -> `Slideshow` opens the `Slide Type` menu for each cell.

The slideshow is made with the command

`jupyter nbconvert --to slides notebook.ipynb`

The slideshow is displayed in browser with the command

`jupyter nbconvert --to slides --post serve notebook.ipynb`


### LaTeX

`jupyter nbconvert --to latex notebook.ipynb`

###  PDF 

`jupyter nbconvert --to PDF notebook.ipynb`

N.B. For the above conversions [Pandoc](http://pandoc.org/installing.html) needs to be installed.

## Which version of `Julia` is running?

In [1]:
versioninfo()

Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3


## Quitting

__Exiting__ from `julia>` or __restarting kernel__ in `IJulia`

In [2]:
# exit()

## Documentation

Documentation is well written and the starting point is http://docs.julialang.org/en/latest/

But, also remeber that `Julia` is __open source__ and all routines are available on [GitHub](http://github.com). You will learn how to make full use of this later in the course.

## Punctuation review

* `[...]` are for indexing, array constructors and __Comprehensions__
* `(...)` are __required__ for functions `quit()`, `tic()`, `toc()`, `help()` 
* `{...}` are for arrays
* `#` is for comments

## Basic indexing

In [3]:
A=rand(5,5) # Matrix with random entries between 0 and 1

5x5 Array{Float64,2}:
 0.589141   0.236581  0.784648  0.609539  0.277695 
 0.434805   0.768152  0.981204  0.328945  0.542079 
 0.674388   0.310239  0.444064  0.956564  0.379369 
 0.59245    0.21946   0.685676  0.338136  0.0315785
 0.0814153  0.247983  0.186041  0.856269  0.192363 

In [4]:
A[1,1]

0.5891406598959215

In [5]:
rand(5,5)[1:2,3:4] # You can even do this

2x2 Array{Float64,2}:
 0.610606  0.00812121
 0.39545   0.333569  

### Indexing is elegant

If you want to compute the lower right $2\times 2$ block of $A^{10}$, in most languages you need to first compute $B=A^{10}$ and then index into $B$. In Julia, the command is simply

In [6]:
(A^10)[4:5,4:5] # Parenthesses around A^10 are necessary

2x2 Array{Float64,2}:
 1242.61   535.399
  914.326  393.953

### Comprehensions - elegant array constructors

In [7]:
[i for i=1:5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [8]:
[trace(rand(n,n)) for n=1:5]

5-element Array{Float64,1}:
 0.765719
 0.893854
 1.27039 
 2.38561 
 2.3785  

In [9]:
x=1:10

1:10

In [10]:
[ x[i]+x[i+1] for i=1:9 ]

9-element Array{Any,1}:
  3
  5
  7
  9
 11
 13
 15
 17
 19

In [11]:
z = [eye(n) for n=1:5]  # z is Array of Arrays

5-element Array{Array{Float64,2},1}:
 1x1 Array{Float64,2}:
 1.0                                                                                                                        
 2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0                                                                                                         
 3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0                                                                                
 4x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0                                             
 5x5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [12]:
z[1] # First element is a 1x1 Array

1x1 Array{Float64,2}:
 1.0

In [13]:
z[4] # What is the fourth element?

4x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [14]:
A=[ i+j for i=1:5, j=1:5 ] # Another example of a comprehension

5x5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [15]:
B=[ i+j for i=1:5, j=1.0:5 ] # Notice the promotion

5x5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

## Commands `ndims()` and `typeof()`

In [16]:
ndims(ans)

2

In [17]:
ndims(z) # z is a one-dimensional array

1

In [18]:
typeof(z) # Array of Arrays

Array{Array{Float64,2},1}

In [19]:
typeof(z[5]) # z[5] is a two-dimensional array

Array{Float64,2}

In [20]:
typeof(A)

Array{Int64,2}

## Vectors are 1-dimensional arrays

See [Multi-dimensional arrays](http://julia.readthedocs.org/en/latest/manual/arrays/) for more.

In [21]:
v=rand(5,1) # This is 2-dimensional array

5x1 Array{Float64,2}:
 0.32014  
 0.552837 
 0.0274691
 0.490916 
 0.646462 

In [22]:
vv=vec(v) # This is an 1-dimensional array or vector

5-element Array{Float64,1}:
 0.32014  
 0.552837 
 0.0274691
 0.490916 
 0.646462 

In [23]:
v==vv  # Notice that they are different

false

In [24]:
v-vv # Again a promotion

5x1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [25]:
w=rand(5) # This is again a vector

5-element Array{Float64,1}:
 0.343098 
 0.922818 
 0.650603 
 0.0498243
 0.414088 

In [26]:
Mv=[v w] # First column is a 5 x 1 matrix, second column is a vector of length 5

5x2 Array{Float64,2}:
 0.32014    0.343098 
 0.552837   0.922818 
 0.0274691  0.650603 
 0.490916   0.0498243
 0.646462   0.414088 

In [27]:
x=Mv[:,1] # Matrix columns are extracted as vectors

5-element Array{Float64,1}:
 0.32014  
 0.552837 
 0.0274691
 0.490916 
 0.646462 

In [28]:
y=Mv[:,2]

5-element Array{Float64,1}:
 0.343098 
 0.922818 
 0.650603 
 0.0498243
 0.414088 

In [29]:
x==v # The types differ

false

In [30]:
y==w

true

### Sometimes brackets are needed

In [31]:
w=1.0:5

1.0:1.0:5.0

In [32]:
A*w  # This returns an error

LoadError: LoadError: MethodError: `A_mul_B!` has no method matching A_mul_B!(::Array{Float64,1}, ::Array{Int64,2}, ::FloatRange{Float64})
Closest candidates are:
  A_mul_B!(::Union{DenseArray{T,1},SubArray{T,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Union{DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD},SubArray{T,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, !Matched::Union{DenseArray{T,1},SubArray{T,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}})
  A_mul_B!(::Union{AbstractArray{T,1},AbstractArray{T,2}}, !Matched::Tridiagonal{T}, ::Union{AbstractArray{T,1},AbstractArray{T,2}})
  A_mul_B!(::Union{AbstractArray{T,1},AbstractArray{T,2}}, !Matched::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, ::Union{AbstractArray{T,1},AbstractArray{T,2}})
  ...
while loading In[32], in expression starting on line 1

In [33]:
w=collect(1.0:5) 

5-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [34]:
A*w  # This returns a 1-dimensional array

5-element Array{Float64,1}:
  70.0
  85.0
 100.0
 115.0
 130.0

In [35]:
A*v # This returns a 2-dimensional array - v is a 5 x 1 array

5x1 Array{Float64,2}:
  8.74202
 10.7798 
 12.8177 
 14.8555 
 16.8933 

## Discussion

Such behavior is due to the fact that `Julia` has vectors as a special type. __ Pros? Cons? __
 
What is matrix $\times$ vector?

What is the result of 

$$ C[i,j]=A[i,:]*B[:,j]$$

In [36]:
B=[A[i,:]*A[:,j] for i=1:5, j=1:5]

5x5 Array{Any,2}:
 [90]   [110]  [130]  [150]  [170]
 [110]  [135]  [160]  [185]  [210]
 [130]  [160]  [190]  [220]  [250]
 [150]  [185]  [220]  [255]  [290]
 [170]  [210]  [250]  [290]  [330]

In [37]:
inv(B) # Why this this happen? How to resolve it?

LoadError: LoadError: MethodError: `one` has no method matching one(::Type{Any})
while loading In[37], in expression starting on line 1

In [38]:
B=[(A[i,:]*A[:,j])[1] for i=1:5, j=1:5] # (First) element of a vector is a number

5x5 Array{Any,2}:
  90  110  130  150  170
 110  135  160  185  210
 130  160  190  220  250
 150  185  220  255  290
 170  210  250  290  330

In [39]:
map(Int64,B) # Need to map it to `Int64` 

5x5 Array{Int64,2}:
  90  110  130  150  170
 110  135  160  185  210
 130  160  190  220  250
 150  185  220  255  290
 170  210  250  290  330

Or, we can use the dot product of two vectors - still need mapping of the comprehension to `Int64`

In [40]:
B=[vec(A[i,:])⋅A[:,j] for i=1:5, j=1:5] 

5x5 Array{Any,2}:
  90  110  130  150  170
 110  135  160  185  210
 130  160  190  220  250
 150  185  220  255  290
 170  210  250  290  330

## `ones()`, `eye()` and `zeros()`
   
Notice that the output type depends on the argument. This is a general Julia feature called `Multiple dispatch` 
and will be explained later in more detail. 

In [41]:
ones(3,5), ones(5), ones(rand(1:3,4,6)) 
# The output type depends on the argument. Float64 is the default.

(
3x5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0,

[1.0,1.0,1.0,1.0,1.0],
4x6 Array{Int64,2}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1)

In [42]:
rand(1:3,4,6)

4x6 Array{Int64,2}:
 1  1  2  3  2  3
 2  1  2  3  1  3
 3  1  1  1  3  2
 1  3  1  1  3  1

In [43]:
zeros(3,5), zeros(5), zeros(rand(1:3,4,6))

(
3x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0,

[0.0,0.0,0.0,0.0,0.0],
4x6 Array{Int64,2}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0)

In [44]:
eye(4), round(Int64,eye(4)), round(Int32,eye(4)), complex(eye(4)) 
# type can also be set

(
4x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0,

4x4 Array{Int64,2}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1,

4x4 Array{Int32,2}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1,

4x4 Array{Complex{Float64},2}:
 1.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  1.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  1.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  1.0+0.0im)

## Complex numbers

`i` is too valuable symbol for loops, so Julia uses `im` for the complex unit. 

In [45]:
im

im

In [46]:
2im

0 + 2im

In [47]:
typeof(ans)

Complex{Int64}

In [48]:
typeof(2.0im)

Complex{Float64}

In [49]:
complex(3,4) # Another way of defining complex numbers

3 + 4im

In [50]:
complex(3,4.0) # If one of the arguments if Float64, so is the entire number

3.0 + 4.0im

In [51]:
sqrt(-1) # This produces an error (like in any other language),

LoadError: LoadError: DomainError:
sqrt will only return a complex result if called with a complex argument. Try sqrt(complex(x)).
while loading In[51], in expression starting on line 1

In [52]:
sqrt(complex(-1))  # and this is fine.

0.0 + 1.0im

## Ternary operator
Let us define our version of the sign function

In [53]:
si(x) = (x>0) ? 1 : -1

si (generic function with 1 method)

In [54]:
si(-13)

-1

This is equivalent to:

In [55]:
function si(x)
    if x>0
        return 1
    else
        return -1
    end
end

si (generic function with 1 method)

In [56]:
si(pi-8), si(0), si(0.0)

(-1,-1,-1)

The expressions can be nested:

In [57]:
si(x) = (x>0) ? 1 : ((x<0) ? -1: 0) # now si(0) is 0

si (generic function with 1 method)

In [58]:
si(π-8), si(0) # '\pi Tab' produces π and means π

(-1,0)

## Typing
Special mathematical (LaTeX) symbols can be used (like $\alpha$, $\Xi$, $\pi$, $\oplus$, $\cdot$, etc.). The symbol in both, the notebook and command line version, is produced by writing 
LaTeX command followed by `Tab` 

In [59]:
Ξ = 8; Ψ  = 6; Γ = Ξ ⋅ Ψ


48

In [60]:
typeof(Γ)

Int64

## Writing a program and running a file

Special feature of Julia is that the results of commands are not displayed, unless explicitely required. 

To display results you can use commands `@show` or `println()` (or many others, see the [Text I/O](http://julia.readthedocs.org/en/latest/stdlib/base/?highlight=print#text-i-o) in the manual.)

Consider the file `deploy.jl` with the following code
```julia
n=int(ARGS[1])          # take one integer argument
println(rand(1:n,n,n))  # generate and print n x n matrix of random integers between 1 and n
@show b=3               # set b to 3 and show the result
c=4                     # set c to 4
```
Running the program in the shell gives
```julia
$ julia deploy.jl 5
[1 3 2 4 1
 5 3 1 1 4
 5 4 2 2 5
 3 1 2 3 4
 4 4 5 4 4]
b = 3 => 3
```
Notice that the result of the last command (_c_) is not displayed.

>You can, of course, also run the above command in the `Console` tab of `JuliaBox`. To do this, you first have to change the directory
```
cd Julia-Course/src
```

Similarly, the program can be converted to executable and run directly, 
without referencing `julia` in the command line.
The refernece to `julia` must be added in the first line, as in the file `deploy1.jl`:
```julia
#!/usr/bin/julia
n=int(ARGS[1])
println(rand(1:n,n,n))
@show b=3
c=4
```
In the shell do:
```
$ chmod +x deploy1.jl
$ ./deploy1.jl 5
[4 5 3 2 5
 4 2 1 5 1
 3 2 4 5 1
 2 4 4 3 1
 3 4 5 3 3]
b = 3 => 3
```
Finally, to run the same program in `julia` shell or `IJulia`, the input has to be changed, as in the file `deploy2.jl`:
```julia
n=int(readline(STDIN))
println(rand(1:n,n,n))
@show b=3
c=4
```
__Notice that now the result of the last line is displayed by default__  - in this case it is `4`, the values of `c`. The output of the random matrix and of `b` is forced.

In [61]:
include("deploy2.jl")

STDIN> 5
[1 2 4 1 2
 2 2 2 5 4
 2 3 5 5 4
 1 3 3 4 3
 2 5 1 3 4]
b = 3 = 3


4

## Running external programs and unix pipe

### `run()` - calling external program

In [62]:
?(run) # ?() is also a function - gives help

search: run trunc truncate itrunc round RoundUp RoundDown RoundToZero



```
run(command)
```

Run a command object, constructed with backticks. Throws an error if anything goes wrong, including the process exiting with a non-zero status.


In [63]:
?run # parentheses can be ommited

search: run trunc truncate itrunc round RoundUp RoundDown RoundToZero



```
run(command)
```

Run a command object, constructed with backticks. Throws an error if anything goes wrong, including the process exiting with a non-zero status.


Notice, that this is not a gret help, Julia has much better commands for this.

In [64]:
run(`cal`) # This calls the unix Calendar program

      May 2016      
Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7 
 8  9 10 11 12 13 14 
15 16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31             
                     


In [65]:
run(pipeline(`cal`,`grep Sa`)) # The pipe is '|>' instead of usual '|'

Su Mo Tu We Th Fr Sa


### `ccall()` - calling `C` program

In [66]:
?("ccall") # ccall is the only function which needs "" in ?() - but this is no much help either :)

Base.Libdl.find_library
(intrinsic function #87)
Base.Libc.errno


In [67]:
ccall(:ctime, Int, ()) # Simple version

139849201859136

In [68]:
bytestring(ccall(:ctime, Ptr{UInt8}, ())) # Human readable version

"Mon Jul 25 16:30:56 4433340\n"

In [69]:
bytestring(ccall((:ctime,"libc"), Ptr{UInt8}, ())) 
# With specifying the library

"Mon Jul 25 18:01:36 4433340\n"

In [70]:
ccall(:ctime, Ptr{UInt8}, ()) # Or with pointers

Ptr{UInt8} @0x00007f312dffba40

## `Task()`, `produce()` and `consume()` 
`Julia` has  a control flow feature that allows computations to be suspended 
and resumed in a flexible manner (see
[tasks](http://julia.readthedocs.org/en/latest/manual/control-flow/#man-tasks) in the manual).

In [71]:
function stepbystep()
    for n=1:3
        produce(n^2)
    end
end

stepbystep (generic function with 1 method)

In [72]:
p=Task(stepbystep)

Task (runnable) @0x00007f2f2d777080

In [73]:
consume(p)

1

In [74]:
consume(p)

4

In [75]:
consume(p) 

9

In [76]:
consume(p) # Guess what comes next?