# Julia is Open - `whos()`, `methods()`, `@which`, ...

---

`Julia` is an open-source project, source being entirely hosted on `github`: http://github.com/julialang

The code consists of (actual numbers may differ):

- 29K lines of `C/C++`
- 6K lines of `scheme`
- 68K lines of `julia`

Julia uses [LLVM](http://llvm.org) which itself has 680K lines of code. Therefore, Julia is very compact, compared to other languages, like LLVM's `C` compiler `clang` (513K lines of code) or `gcc`  (3,530K lines). This makes it easy to read the actuall code and get full information, in spite the fact that some parts of the documentation are insufficient. `Julia`'s "navigating" system,
consisting of commands `whos()`, `methods()` and `@which`, makes this even easier.

Further, the `Base` (core) of Julia is kept small, and the rest of the functionality is obtained through packages.
Since packages are written in Julia, they are navigated on the same way.




In this notebook, we demonstrate how to get help and navigate the source code.

## Prerequisites

Basic knowledge of programming in any language.

Read [Methods](http://julia.readthedocs.org/en/latest/manual/methods/) section of the `Julia` manual. (5 min)

## Competences 

The reader should be able to read the code and be able to find and understand calling sequences and outputs of any function.

## Credits 

Some examples are taken from [The Julia Manual](http://julia.readthedocs.org/en/latest/manual/).


## Operators `+`, `*` and `⋅`

Consider operators `+`, `*` and `⋅`, the first two of them seem rather basic in any language. The `⋅` symbol is typed as LaTeX command `\cdot` + `Tab`.

`?+` gives some information, which is vary sparse. We would expect more details, and we also suspect that `+` can be used in more ways that just hose two.

`?*` explaind more instances where `*` can be used, but the text itself is vague and not sufficient. 

`?⋅` appears to be what we expect fro the dot product off two vectors.

In [1]:
?+

search: + .+



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.


In [2]:
?*

search: * .*



```
*(x, y...)
```

Multiplication operator. `x*y*z*...` calls this function with all arguments, i.e. `*(x, y, z, ...)`.

```
*(s, t)
```

Concatenate strings. The `*` operator is an alias to this function.

```jldoctest
julia> "Hello " * "world"
"Hello world"
```

```
*(A, B)
```

Matrix multiplication


In [3]:
?⋅

search: ⋅



```
dot(x, y)
⋅(x,y)
```

Compute the dot product. For complex vectors, the first vector is conjugated.


## methods()

`Julia` functions have a feature called _multiple dispatch_, which means that the method depends on the name __AND__ the input.
Full range of existing methods for certain function name is given by the `methods()` command. 
> Running `methods(+)` sheds a completely differfent light on `+`.

The great `IJulia` feature is that the links to the source code where the respective version of the function is defined, are readily provided. 

In [4]:
?methods

search: methods methodswith method_exists Method MethodTable MethodError



```
methods(f, [types])
```

Returns the method table for `f`.

If `types` is specified, returns an array of methods whose types match.


### The `"+"` operator

__N.B.__ For convenience, Left click on the left area of the `Out[]` cell toggles  scrolling. Double click collapses the output completely. 

In [8]:
methods(+)

# 171 methods for generic function "+":
+(x::Bool) at bool.jl:33
+(x::Bool, y::Bool) at bool.jl:36
+(y::AbstractFloat, x::Bool) at bool.jl:46
+(x::Int64, y::Int64) at int.jl:8
+(x::Int8, y::Int8) at int.jl:16
+(x::UInt8, y::UInt8) at int.jl:16
+(x::Int16, y::Int16) at int.jl:16
+(x::UInt16, y::UInt16) at int.jl:16
+(x::Int32, y::Int32) at int.jl:16
+(x::UInt32, y::UInt32) at int.jl:16
+(x::UInt64, y::UInt64) at int.jl:16
+(x::Int128, y::Int128) at int.jl:16
+(x::UInt128, y::UInt128) at int.jl:16
+(x::Integer, y::Ptr{T}) at pointer.jl:77
+(x::Float32, y::Float32) at float.jl:207
+(x::Float64, y::Float64) at float.jl:208
+(z::Complex{T<:Real}, w::Complex{T<:Real}) at complex.jl:111
+(x::Bool, z::Complex{Bool}) at complex.jl:118
+(z::Complex{Bool}, x::Bool) at complex.jl:119
+(x::Bool, z::Complex{T<:Real}) at complex.jl:125
+(z::Complex{T<:Real}, x::Bool) at complex.jl:126
+(x::Real, z::Complex{Bool}) at complex.jl:132
+(z::Complex{Bool}, x::Real) at complex.jl:133
+(x::Real, z::Complex{T<:Real}) at complex.jl:144
+(z::Complex{T<:Real}, x::Real) at complex.jl:145
+(x::Rational{T<:Integer}, y::Rational{T<:Integer}) at rational.jl:179
+(x::Bool, A::AbstractArray{Bool,N}) at arraymath.jl:136
+(x::Integer, y::Char) at char.jl:43
+(a::Float16, b::Float16) at float16.jl:136
+(x::BigInt, y::BigInt) at gmp.jl:256
+(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:279
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:285
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:292
+(x::BigInt, c::Union{UInt16,UInt32,UInt8}) at gmp.jl:304
+(c::Union{UInt16,UInt32,UInt8}, x::BigInt) at gmp.jl:308
+(x::BigInt, c::Union{Int16,Int32,Int8}) at gmp.jl:320
+(c::Union{Int16,Int32,Int8}, x::BigInt) at gmp.jl:321
+(x::BigFloat, y::BigFloat) at mpfr.jl:208
+(x::BigFloat, c::Union{UInt16,UInt32,UInt8}) at mpfr.jl:215
+(c::Union{UInt16,UInt32,UInt8}, x::BigFloat) at mpfr.jl:219
+(x::BigFloat, c::Union{Int16,Int32,Int8}) at mpfr.jl:223
+(c::Union{Int16,Int32,Int8}, x::BigFloat) at mpfr.jl:227
+(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:231
+(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:235
+(x::BigFloat, c::BigInt) at mpfr.jl:239
+(c::BigInt, x::BigFloat) at mpfr.jl:243
+(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:379
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:385
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:392
+(x::Irrational{sym}, y::Irrational{sym}) at irrationals.jl:72
+(x::Number) at operators.jl:73
+{T<:Number}(x::T<:Number, y::T<:Number) at promotion.jl:211
+{T<:AbstractFloat}(x::Bool, y::T<:AbstractFloat) at bool.jl:43
+(x::Number, y::Number) at promotion.jl:167
+(r1::OrdinalRange{T,S}, r2::OrdinalRange{T,S}) at operators.jl:330
+{T<:AbstractFloat}(r1::FloatRange{T<:AbstractFloat}, r2::FloatRange{T<:AbstractFloat}) at operators.jl:337
+{T<:AbstractFloat}(r1::LinSpace{T<:AbstractFloat}, r2::LinSpace{T<:AbstractFloat}) at operators.jl:356
+(r1::Union{FloatRange{T<:AbstractFloat},LinSpace{T<:AbstractFloat},OrdinalRange{T,S}}, r2::Union{FloatRange{T<:AbstractFloat},LinSpace{T<:AbstractFloat},OrdinalRange{T,S}}) at operators.jl:369
+(x::Ptr{T}, y::Integer) at pointer.jl:75
+{S,T}(A::Range{S}, B::Range{T}) at arraymath.jl:69
+{S,T}(A::Range{S}, B::AbstractArray{T,N}) at arraymath.jl:87
+(A::BitArray{N}, B::BitArray{N}) at bitarray.jl:834
+{T}(B::BitArray{2}, J::UniformScaling{T}) at linalg/uniformscaling.jl:28
+(A::Array{T,2}, B::Diagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::Bidiagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122
+(A::Array{T,2}, B::SymTridiagonal{T}) at linalg/special.jl:131
+(A::Array{T,2}, B::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}) at linalg/special.jl:159
+(A::Array{T,N}, B::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:1019
+{P<:Union{Base.Dates.CompoundPeriod,Base.Dates.Period}}(x::Union{DenseArray{P<:Union{Base.Dates.CompoundPeriod,Base.Dat

Following the first link, we get the following code snippet:
```
+(x::Bool) = int(x)
-(x::Bool) = -int(x)
+(x::Bool, y::Bool) = int(x) + int(y)
-(x::Bool, y::Bool) = int(x) - int(y)
*(x::Bool, y::Bool) = x & y
```

Therefore:

In [9]:
+(true), +(false),-(true),-(false)

(1,0,-1,0)

In [10]:
x, y = bitpack([0,1,0,1,0,1]), bitpack([0,1,1,1,1,0])

(Bool[false,true,false,true,false,true],Bool[false,true,true,true,true,false])

The above command is equivalent to 
```
x = bitpack([0,1,0,1,0,1]); y = bitpack([0,1,1,1,1,0])
```
except that only the last result would be displayed

In [11]:
+x,-(x)

(Bool[false,true,false,true,false,true],[0,-1,0,-1,0,-1])

In [12]:
x+y, +(x,y)

([0,2,1,2,1,1],[0,2,1,2,1,1])

In [9]:
c1=x+y

6-element Array{Int64,1}:
 0
 2
 1
 2
 1
 1

In [10]:
c2=+(x,y)

6-element Array{Int64,1}:
 0
 2
 1
 2
 1
 1

### Manipulating dates

We see that one of the `+` methods is adding days to time: 

```
 +(x::Date,y::Base.Dates.Day) at dates/arithmetic.jl:60
```
Therefore, the 135-th day from today is:

In [13]:
Dates.today()

2016-06-27

In [14]:
dd=Dates.today()+Dates.Day(135)

2016-11-09

In [15]:
typeof(dd)

Date

More information about the two types can be obtained by `methods(Dates.Date)` and `methods(Dates.Day)`, respectively. 

### Adding tridiagonal matrices

In the above output of `methods(+)`,  we see that we can add tridiagonal matrices:
```
+(A::Tridiagonal{T}, B::Tridiagonal{T}) at linalg/tridiag.jl:404
```
Following the link, we see that the method separately adds lower, main and upper diagonals, denoted by `dl`, `d` and `du`, respectively:
```
404: +(A::Tridiagonal, B::Tridiagonal) = Tridiagonal(A.dl+B.dl, A.d+B.d, A.du+B.du)
```
Let us see how exactly is the type `Tridiagonal` defined:

In [16]:
methods(Tridiagonal)

6-element Array{Any,1}:
 call{T}(::Type{Tridiagonal{T}}, dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}, du2::Array{T,1}) at linalg/tridiag.jl:267
 call{T}(::Type{Tridiagonal{T}}, dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}) at linalg/tridiag.jl:273                 
 call{Tl,Td,Tu}(::Type{Tridiagonal{T}}, dl::Array{Tl,1}, d::Array{Td,1}, du::Array{Tu,1}) at linalg/tridiag.jl:280       
 call{T}(::Type{Tridiagonal{T}}, M::Bidiagonal{T}) at linalg/bidiag.jl:63                                                
 call{T}(::Type{T}, arg) at essentials.jl:56                                                                             
 call{T}(::Type{T}, args...) at essentials.jl:57                                                                         

This output seems confusing, but from the second line we conclude that we can define three diagonals, lower, main and upper diagonal, denoted as above. We also know that that the lower and upper diagonals are of size $n-1$. Let us try it out:

In [17]:
T1 = Tridiagonal(rand(6),rand(7),rand(6))

7x7 Tridiagonal{Float64}:
 0.788104  0.0808071  0.0       0.0       0.0       0.0        0.0     
 0.033025  0.255864   0.356216  0.0       0.0       0.0        0.0     
 0.0       0.699346   0.680459  0.586916  0.0       0.0        0.0     
 0.0       0.0        0.425879  0.594901  0.016702  0.0        0.0     
 0.0       0.0        0.0       0.647992  0.739524  0.327748   0.0     
 0.0       0.0        0.0       0.0       0.624889  0.0482795  0.754741
 0.0       0.0        0.0       0.0       0.0       0.806467   0.141231

In [18]:
T2 = Tridiagonal(rand(-5:5,6),randn(7),rand(-9:0,6))

7x7 Tridiagonal{Float64}:
  0.238621  -7.0        0.0        0.0         0.0       0.0       0.0    
 -1.0        0.558798  -6.0        0.0         0.0       0.0       0.0    
  0.0       -4.0        0.744293  -9.0         0.0       0.0       0.0    
  0.0        0.0       -1.0        0.0550874  -1.0       0.0       0.0    
  0.0        0.0        0.0        1.0         1.24508  -5.0       0.0    
  0.0        0.0        0.0        0.0        -3.0       1.97232  -3.0    
  0.0        0.0        0.0        0.0         0.0      -3.0       1.81925

In [19]:
T3 = T1 + T2

7x7 Tridiagonal{Float64}:
  1.02672   -6.91919    0.0        0.0        0.0        0.0       0.0    
 -0.966975   0.814662  -5.64378    0.0        0.0        0.0       0.0    
  0.0       -3.30065    1.42475   -8.41308    0.0        0.0       0.0    
  0.0        0.0       -0.574121   0.649988  -0.983298   0.0       0.0    
  0.0        0.0        0.0        1.64799    1.9846    -4.67225   0.0    
  0.0        0.0        0.0        0.0       -2.37511    2.0206   -2.24526
  0.0        0.0        0.0        0.0        0.0       -2.19353   1.96048

This worked as expected, the result is again a `Tridiagonal`. We can access each diagonal by:

In [20]:
fieldnames(T3)

4-element Array{Symbol,1}:
 :dl 
 :d  
 :du 
 :du2

In [21]:
println(T3.dl, T3.d, T3.du)

[-0.9669750160268864,-3.3006535766187115,-0.5741208927323576,1.6479919658087303,-2.375111016003166,-2.1935329362715663][1.0267248624130698,0.8146619840630321,1.4247520484272789,0.6499882507927407,1.9845994549445591,2.0205978395062383,1.960477182794874][-6.9191928648010235,-5.643783666245672,-8.413084261531251,-0.9832979899782073,-4.672251961164073,-2.245259147359543]


In [23]:
B=full(T3)

7x7 Array{Float64,2}:
  1.02672   -6.91919    0.0        0.0        0.0        0.0       0.0    
 -0.966975   0.814662  -5.64378    0.0        0.0        0.0       0.0    
  0.0       -3.30065    1.42475   -8.41308    0.0        0.0       0.0    
  0.0        0.0       -0.574121   0.649988  -0.983298   0.0       0.0    
  0.0        0.0        0.0        1.64799    1.9846    -4.67225   0.0    
  0.0        0.0        0.0        0.0       -2.37511    2.0206   -2.24526
  0.0        0.0        0.0        0.0        0.0       -2.19353   1.96048

### `@which`

Let us take a closer look at what happens. The `@which` command gives the link to the part of the code which is actually invoked. The argument should be only function, without assignment, that is 
```
@which T1=Tridiagonal(rand(6),rand(7),rand(6))
```
throws an error.

In [19]:
@which Tridiagonal(rand(6),rand(7),rand(6))

call{T}(::Type{Tridiagonal{T}}, dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}) at linalg/tridiag.jl:273

In the code, we see that there is a type definition in the `immutable` block:
```
## Tridiagonal matrices ##
immutable Tridiagonal{T} <: AbstractMatrix{T}
dl::Vector{T} # sub-diagonal
d::Vector{T} # diagonal
du::Vector{T} # sup-diagonal
du2::Vector{T} # supsup-diagonal for pivoting
end
```
The `Tridiagonal` type consists of __four__ vectors.
In our case, we actually called the function `Tridiagonal()` with __three__ vector arguments. The function creates the type of the same name, setting the fourth reqired vector `du2` to `zeros(T,n-2)`.

The next function with the same name is invoked when the input vectors have different types, in which case the types arer promoted to a most general one, if possible.

In [20]:
T4 = Tridiagonal([1,2,3], [2.0,3.0,pi,4.0],rand(3)+im*rand(3))

4x4 Tridiagonal{Complex{Float64}}:
 2.0+0.0im  0.20347+0.676614im       0.0+0.0im           0.0+0.0im    
 1.0+0.0im      3.0+0.0im       0.707746+0.66663im       0.0+0.0im    
 0.0+0.0im      2.0+0.0im        3.14159+0.0im      0.557531+0.89053im
 0.0+0.0im      0.0+0.0im            3.0+0.0im           4.0+0.0im    

### `size()` and `full()`

For each matrix type we need to define the function which returns the size of a matrix, and the function which converts the matrix of a given type to a full matrix. These function are listed after the second `Tridiagonal()` function.

In [21]:
size(T4)

(4,4)

In [22]:
T4 = full(T4)

4x4 Array{Complex{Float64},2}:
 2.0+0.0im  0.20347+0.676614im       0.0+0.0im           0.0+0.0im    
 1.0+0.0im      3.0+0.0im       0.707746+0.66663im       0.0+0.0im    
 0.0+0.0im      2.0+0.0im        3.14159+0.0im      0.557531+0.89053im
 0.0+0.0im      0.0+0.0im            3.0+0.0im           4.0+0.0im    

### `sizeof()` 

Of course, using special types can leasd to much more efficient programs. For example, for `Tridiagonal` type, onlt four diagonals are stored, in comparison to storing full matrix when $n^2$ elements are stored. The storage used is obtained by the `sizeof()` function.

In [23]:
T1

7x7 Tridiagonal{Float64}:
 0.82623   0.39287   0.0        0.0        0.0       0.0       0.0     
 0.800854  0.306805  0.539296   0.0        0.0       0.0       0.0     
 0.0       0.798668  0.0476339  0.0170054  0.0       0.0       0.0     
 0.0       0.0       0.477484   0.376727   0.476926  0.0       0.0     
 0.0       0.0       0.0        0.309081   0.265363  0.674934  0.0     
 0.0       0.0       0.0        0.0        0.604978  0.232923  0.529863
 0.0       0.0       0.0        0.0        0.0       0.405191  0.613519

In [24]:
T1f=full(T1)

7x7 Array{Float64,2}:
 0.82623   0.39287   0.0        0.0        0.0       0.0       0.0     
 0.800854  0.306805  0.539296   0.0        0.0       0.0       0.0     
 0.0       0.798668  0.0476339  0.0170054  0.0       0.0       0.0     
 0.0       0.0       0.477484   0.376727   0.476926  0.0       0.0     
 0.0       0.0       0.0        0.309081   0.265363  0.674934  0.0     
 0.0       0.0       0.0        0.0        0.604978  0.232923  0.529863
 0.0       0.0       0.0        0.0        0.0       0.405191  0.613519

In [25]:
sizeof(T1f)  #   392 =  7 * 7 * 8 bytes

392

In [26]:
sizeof(T1) # This is not implemented for Tridiagonal - only the storage required for 4 vector variables' names is displayed

32

### `immutable`

The `immutable` command means that we can change individual elements of defined parts, but not the parts as a whole (an alternative is to use the `type` construtor). For example: 

In [27]:
@show T5 = Tridiagonal([1,2,3],[2,3,4,5],[-1,1,2])
T5.d[2]=123
@show T5
T5.dl = [-1, -1 ,1]

T5 = Tridiagonal([1,2,3],[2,3,4,5],[-1,1,2]) = [2 -1 0 0
 1 3 1 0
 0 2 4 2
 0 0 3 5]
T5 = [2 -1 0 0
 1 123 1 0
 0 2 4 2
 0 0 3 5]


LoadError: LoadError: type Tridiagonal is immutable
while loading In[27], in expression starting on line 4

### `methodswith()`

This is the reverse of `methods()` - which methods exist for the given type. For example, what can we do with `Tridiagonal` matrices, or with `Dates.Day`:

In [28]:
methodswith(Tridiagonal)

77-element Array{Method,1}:
 *(A::Tridiagonal{T}, B::Number) at linalg/tridiag.jl:406                                                                                              
 *(A::Tridiagonal{T}, B::UpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                                         
 *(A::Tridiagonal{T}, B::Base.LinAlg.UnitUpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                         
 *(A::Tridiagonal{T}, B::LowerTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                                         
 *(A::Tridiagonal{T}, B::Base.LinAlg.UnitLowerTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                         
 *(B::Number, A::Tridiagonal{T}) at linalg/tridiag.jl:407                                                                                              
 +(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122                                                                                          
 +(A::Tridiagonal{T}, B::Tridiagonal{T}) at linalg/tridiag.jl:404                                                                                      
 +(A::Diagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                         
 +(A::Tridiagonal{T}, B::Diagonal{T}) at linalg/special.jl:122                                                                                         
 +(A::Bidiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                       
 +(A::Tridiagonal{T}, B::Bidiagonal{T}) at linalg/special.jl:122                                                                                       
 +(A::Tridiagonal{T}, B::Array{T,2}) at linalg/special.jl:121                                                                                          
 +(A::SymTridiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:130                                                                                   
 +(A::Tridiagonal{T}, B::SymTridiagonal{T}) at linalg/special.jl:131                                                                                   
 +(A::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, B::Tridiagonal{T}) at linalg/special.jl:158                                             
 +(A::Tridiagonal{T}, B::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}) at linalg/special.jl:159                                             
 -(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122                                                                                          
 -(A::Tridiagonal{T}, B::Tridiagonal{T}) at linalg/tridiag.jl:405                                                                                      
 -(A::Diagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                         
 -(A::Tridiagonal{T}, B::Diagonal{T}) at linalg/special.jl:122                                                                                         
 -(A::Bidiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                       
 -(A::Tridiagonal{T}, B::Bidiagonal{T}) at linalg/special.jl:122                                                                                       
 -(A::Tridiagonal{T}, B::Array{T,2}) at linalg/special.jl:121                                                                                          
 -(A::SymTridiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:130                                                                                   
 -(A::Tridiagonal{T}, B::SymTridiagonal{T}) at linalg/special.jl:131                                                                                   
 -(A::Base.LinAlg.Ab

In [29]:
methodswith(Dates.Day)

13-element Array{Method,1}:
 +(x::Date, y::Base.Dates.Day) at dates/arithmetic.jl:62                                                                                                                                              
 -(x::Date, y::Base.Dates.Day) at dates/arithmetic.jl:63                                                                                                                                              
 call(::Type{DateTime}, y::Base.Dates.Year, m::Base.Dates.Month, d::Base.Dates.Day) at dates/types.jl:101                                                                                             
 call(::Type{DateTime}, y::Base.Dates.Year, m::Base.Dates.Month, d::Base.Dates.Day, h::Base.Dates.Hour) at dates/types.jl:101                                                                         
 call(::Type{DateTime}, y::Base.Dates.Year, m::Base.Dates.Month, d::Base.Dates.Day, h::Base.Dates.Hour, mi::Base.Dates.Minute) at dates/types.jl:101                                                  
 call(::Type{DateTime}, y::Base.Dates.Year, m::Base.Dates.Month, d::Base.Dates.Day, h::Base.Dates.Hour, mi::Base.Dates.Minute, s::Base.Dates.Second) at dates/types.jl:101                            
 call(::Type{DateTime}, y::Base.Dates.Year, m::Base.Dates.Month, d::Base.Dates.Day, h::Base.Dates.Hour, mi::Base.Dates.Minute, s::Base.Dates.Second, ms::Base.Dates.Millisecond) at dates/types.jl:101
 call(::Type{Date}, y::Base.Dates.Year, m::Base.Dates.Month, d::Base.Dates.Day) at dates/types.jl:105                                                                                                 
 convert(::Type{Base.Dates.Week}, x::Base.Dates.Day) at dates/periods.jl:277                                                                                                                          
 convert(::Type{Base.Dates.Hour}, x::Base.Dates.Day) at dates/periods.jl:270                                                                                                                          
 convert(::Type{Base.Dates.Minute}, x::Base.Dates.Day) at dates/periods.jl:270                                                                                                                        
 convert(::Type{Base.Dates.Second}, x::Base.Dates.Day) at dates/periods.jl:270                                                                                                                        
 convert(::Type{Base.Dates.Millisecond}, x::Base.Dates.Day) at dates/periods.jl:270

### The `"*"` operator

In [27]:
methods(*)

# 138 methods for generic function "*":
*(x::Bool, y::Bool) at bool.jl:38
*{T<:Unsigned}(x::Bool, y::T<:Unsigned) at bool.jl:53
*(x::Bool, z::Complex{Bool}) at complex.jl:122
*(x::Bool, z::Complex{T<:Real}) at complex.jl:129
*{T<:Number}(x::Bool, y::T<:Number) at bool.jl:49
*(x::Float32, y::Float32) at float.jl:211
*(x::Float64, y::Float64) at float.jl:212
*(z::Complex{T<:Real}, w::Complex{T<:Real}) at complex.jl:113
*(z::Complex{Bool}, x::Bool) at complex.jl:123
*(z::Complex{T<:Real}, x::Bool) at complex.jl:130
*(x::Real, z::Complex{Bool}) at complex.jl:140
*(z::Complex{Bool}, x::Real) at complex.jl:141
*(x::Real, z::Complex{T<:Real}) at complex.jl:152
*(z::Complex{T<:Real}, x::Real) at complex.jl:153
*(x::Rational{T<:Integer}, y::Rational{T<:Integer}) at rational.jl:186
*(a::Float16, b::Float16) at float16.jl:136
*{N}(a::Integer, index::CartesianIndex{N}) at multidimensional.jl:50
*(x::BigInt, y::BigInt) at gmp.jl:256
*(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:279
*(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:285
*(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:292
*(x::BigInt, c::Union{UInt16,UInt32,UInt8}) at gmp.jl:326
*(c::Union{UInt16,UInt32,UInt8}, x::BigInt) at gmp.jl:330
*(x::BigInt, c::Union{Int16,Int32,Int8}) at gmp.jl:332
*(c::Union{Int16,Int32,Int8}, x::BigInt) at gmp.jl:336
*(x::BigFloat, y::BigFloat) at mpfr.jl:208
*(x::BigFloat, c::Union{UInt16,UInt32,UInt8}) at mpfr.jl:215
*(c::Union{UInt16,UInt32,UInt8}, x::BigFloat) at mpfr.jl:219
*(x::BigFloat, c::Union{Int16,Int32,Int8}) at mpfr.jl:223
*(c::Union{Int16,Int32,Int8}, x::BigFloat) at mpfr.jl:227
*(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:231
*(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:235
*(x::BigFloat, c::BigInt) at mpfr.jl:239
*(c::BigInt, x::BigFloat) at mpfr.jl:243
*(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:379
*(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:385
*(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:392
*{T<:Number}(x::T<:Number, D::Diagonal{T}) at linalg/diagonal.jl:89
*(x::Irrational{sym}, y::Irrational{sym}) at irrationals.jl:72
*(y::Real, x::Base.Dates.Period) at dates/periods.jl:55
*(x::Number) at operators.jl:74
*(y::Number, x::Bool) at bool.jl:55
*(x::Int8, y::Int8) at int.jl:19
*(x::UInt8, y::UInt8) at int.jl:19
*(x::Int16, y::Int16) at int.jl:19
*(x::UInt16, y::UInt16) at int.jl:19
*(x::Int32, y::Int32) at int.jl:19
*(x::UInt32, y::UInt32) at int.jl:19
*(x::Int64, y::Int64) at int.jl:19
*(x::UInt64, y::UInt64) at int.jl:19
*(x::Int128, y::Int128) at int.jl:456
*(x::UInt128, y::UInt128) at int.jl:457
*{T<:Number}(x::T<:Number, y::T<:Number) at promotion.jl:212
*(x::Number, y::Number) at promotion.jl:168
*{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(A::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, x::Union{DenseArray{S,1},SubArray{S,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}) at linalg/matmul.jl:82
*(A::SymTridiagonal{T}, B::Number) at linalg/tridiag.jl:86
*(A::Tridiagonal{T}, B::Number) at linalg/tridiag.jl:406
*(A::UpperTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:454
*(A::Base.LinAlg.UnitUpperTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:457
*(A::LowerTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:454
*(A::Base.LinAlg.UnitLowerTriangular{T,S<:AbstractArray{T,2}}, x::Number) at linalg/triangular.jl:457
*(A::Tridiagonal{T}, B::UpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969
*(A::Tridiagonal{T}, B::Base.LinAlg.UnitUpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969
*(A::Tridiagonal{T}, B::LowerTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969
*(A::Tridiagonal{T

We can multiply various types of numbers and matrices. Notice, however, that there is no multiplication specifically defined for `Tridiagonal` matrices. This would not make much sense, since the product of two tridiagonal matrices is a pentadiagonal matrix, the product of three tridiagonal matrices is septadiagonal matrix, ...

Therefore, two tridiagonal matrices are first converted to full matrices, and then multiplied, as is seen in the source code.

In [33]:
T1*T2

7x7 Array{Float64,2}:
 0.808367  -7.0538   -0.78574    0.0        0.0        0.0        0.0     
 0.709541  -9.60564  -1.39174   -4.31437    0.0        0.0        0.0     
 0.798668   0.53895  -1.70008   -0.394389  -0.136043   0.0        0.0     
 0.0       -2.38742  -1.4424    -4.59183   -2.2882    -1.43078    0.0     
 0.0        0.0      -0.618162  -0.507422  -4.09372   -0.886393  -0.674934
 0.0        0.0       0.0       -0.604978   0.22167   -3.43569    0.601938
 0.0        0.0       0.0        0.0       -1.21557   -1.89477    0.56148 

In [34]:
@which T1*T2

*(A::Union{Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}},Bidiagonal{T},Diagonal{T},SymTridiagonal{T},Tridiagonal{T}}, B::Union{Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}},Bidiagonal{T},Diagonal{T},SymTridiagonal{T},Tridiagonal{T}}) at linalg/bidiag.jl:198

In [29]:
T1*(T2*T1) # Currently, T1*T2*T1, which is equal to (T1*T2)*T1 does not work, it will be fixed soon!

7x7 Array{Float64,2}:
 -0.0961737  -1.73039   -2.27898   …   0.0         0.0        0.0      
 -0.245406   -1.29539   -2.76855      -0.0535458   0.0        0.0      
 -0.62814    -3.64372   -6.33473      -0.535783   -0.19236    0.0      
 -0.0562586  -0.630233  -2.40722      -0.53994    -0.192194  -0.0630284
  0.0        -0.453171  -0.110782     -2.41912    -1.17312   -2.44173  
  0.0         0.0        0.266127  …  -2.82912     0.942483  -3.82172  
  0.0         0.0        0.0          -1.06001    -2.48057    0.575311 

In [26]:
methodswith(Tridiagonal)

77-element Array{Method,1}:
 *(A::Tridiagonal{T}, B::Number) at linalg/tridiag.jl:406                                                                                              
 *(A::Tridiagonal{T}, B::UpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                                         
 *(A::Tridiagonal{T}, B::Base.LinAlg.UnitUpperTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                         
 *(A::Tridiagonal{T}, B::LowerTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                                         
 *(A::Tridiagonal{T}, B::Base.LinAlg.UnitLowerTriangular{T,S<:AbstractArray{T,2}}) at linalg/triangular.jl:969                                         
 *(B::Number, A::Tridiagonal{T}) at linalg/tridiag.jl:407                                                                                              
 +(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122                                                                                          
 +(A::Tridiagonal{T}, B::Tridiagonal{T}) at linalg/tridiag.jl:404                                                                                      
 +(A::Diagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                         
 +(A::Tridiagonal{T}, B::Diagonal{T}) at linalg/special.jl:122                                                                                         
 +(A::Bidiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                       
 +(A::Tridiagonal{T}, B::Bidiagonal{T}) at linalg/special.jl:122                                                                                       
 +(A::Tridiagonal{T}, B::Array{T,2}) at linalg/special.jl:121                                                                                          
 +(A::SymTridiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:130                                                                                   
 +(A::Tridiagonal{T}, B::SymTridiagonal{T}) at linalg/special.jl:131                                                                                   
 +(A::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, B::Tridiagonal{T}) at linalg/special.jl:158                                             
 +(A::Tridiagonal{T}, B::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}) at linalg/special.jl:159                                             
 -(A::Array{T,2}, B::Tridiagonal{T}) at linalg/special.jl:122                                                                                          
 -(A::Tridiagonal{T}, B::Tridiagonal{T}) at linalg/tridiag.jl:405                                                                                      
 -(A::Diagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                         
 -(A::Tridiagonal{T}, B::Diagonal{T}) at linalg/special.jl:122                                                                                         
 -(A::Bidiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:121                                                                                       
 -(A::Tridiagonal{T}, B::Bidiagonal{T}) at linalg/special.jl:122                                                                                       
 -(A::Tridiagonal{T}, B::Array{T,2}) at linalg/special.jl:121                                                                                          
 -(A::SymTridiagonal{T}, B::Tridiagonal{T}) at linalg/special.jl:130                                                                                   
 -(A::Tridiagonal{T}, B::SymTridiagonal{T}) at linalg/special.jl:131                                                                                   
 -(A::Base.LinAlg.Ab

### The "$\cdot$" operator

In [30]:
methods(⋅)

# 5 methods for generic function "dot":
dot(x::Number, y::Number) at linalg/generic.jl:291
dot{T<:Union{Float32,Float64},TI<:Integer}(x::Array{T<:Union{Float32,Float64},1}, rx::Union{Range{TI<:Integer},UnitRange{TI<:Integer}}, y::Array{T<:Union{Float32,Float64},1}, ry::Union{Range{TI<:Integer},UnitRange{TI<:Integer}}) at linalg/matmul.jl:51
dot{T<:Union{Complex{Float32},Complex{Float64}},TI<:Integer}(x::Array{T<:Union{Complex{Float32},Complex{Float64}},1}, rx::Union{Range{TI<:Integer},UnitRange{TI<:Integer}}, y::Array{T<:Union{Complex{Float32},Complex{Float64}},1}, ry::Union{Range{TI<:Integer},UnitRange{TI<:Integer}}) at linalg/matmul.jl:64
dot(x::BitArray{1}, y::BitArray{1}) at linalg/bitarray.jl:5
dot(x::AbstractArray{T,1}, y::AbstractArray{T,1}) at linalg/generic.jl:292

By inspecting the source, we see that the `scalar` or the `dot` product of two vectors (1-dimensional arrays) is 
computed via `BLAS` function `dot` for real arguments, and the function `dotc` for complex arguments.  

In [31]:
a=rand(4); b=rand(4)
@which a⋅b

dot(x::AbstractArray{T,1}, y::AbstractArray{T,1}) at linalg/generic.jl:292

In [32]:
x = rand(1:5,5); y  = rand(-5:0,5); a = x⋅y
z = rand(5); b = x⋅z; c = z⋅x
w = rand(5) + im*rand(5); d = x⋅w; e = z⋅w; f = w⋅z
@show x, y, z, w
a, b, c, d, e, f

(x,y,z,w) = ([5,1,1,4,1],[-4,-4,-5,-2,-1],[0.7744754212645102,0.22659568835022603,0.34789203017305104,0.40054131978278984,0.8616511650805037],Complex{Float64}[0.3398887180364336 + 0.7514051053703097im,0.010099485366519279 + 0.3252337306512254im,0.024111262377866316 + 0.4915558821677388im,0.5354978734485039 + 0.5703424056663431im,0.13282456003100496 + 0.8439661857332146im])


(-38,6.910681269057491,6.910681269057491,4.008470391751574 + 7.6991509480691im,0.6028495358155636 + 1.7822998675037018im,0.6028495358155636 - 1.7822998675037018im)

## `whos()`

The command `whos()` reveals the content of the specified package or module. It can be invoked either with the package name, or with the package name and a regular expression.

In [34]:
whos(Dates)

                           Apr      8 bytes  Int64
                         April      8 bytes  Int64
                           Aug      8 bytes  Int64
                        August      8 bytes  Int64
                          Date    112 bytes  DataType
                    DateFormat    136 bytes  DataType
                    DatePeriod     92 bytes  DataType
                      DateTime    112 bytes  DataType
                         Dates    309 KB     Module
                           Day    112 bytes  DataType
                           Dec      8 bytes  Int64
                      December      8 bytes  Int64
                           Feb      8 bytes  Int64
                      February      8 bytes  Int64
                           Fri      8 bytes  Int64
                        Friday      8 bytes  Int64
                          Hour    112 bytes  DataType
                 ISODateFormat    265 bytes  Base.Dates.DateFormat
             ISODateTimeFormat    461 bytes  Ba

In [35]:
whos(LinAlg)

                             /     30 KB     Function
               ARPACKException    144 bytes  DataType
                     A_ldiv_B!     44 KB     Function
                     A_ldiv_Bc    487 bytes  Function
                     A_ldiv_Bt    486 bytes  Function
                      A_mul_B!     61 KB     Function
                      A_mul_Bc   6943 bytes  Function
                     A_mul_Bc!     22 KB     Function
                      A_mul_Bt   2442 bytes  Function
                     A_mul_Bt!   2979 bytes  Function
                     A_rdiv_Bc   2981 bytes  Function
                     A_rdiv_Bt   2536 bytes  Function
                     Ac_ldiv_B   5890 bytes  Function
                    Ac_ldiv_Bc   1920 bytes  Function
                      Ac_mul_B   8932 bytes  Function
                     Ac_mul_B!     23 KB     Function
                     Ac_mul_Bc   1685 bytes  Function
                    Ac_mul_Bc!   1478 bytes  Function
                     Ac_rdiv

In [36]:
# Now with a regular expression - we are looking for 'eigenvalue' related stuff. 
whos(Base, Regex("eig")) 

                           eig   3228 bytes  Function
                       eigfact   8359 bytes  Function
                      eigfact!     12 KB     Function
                        eigmax   2921 bytes  Function
                        eigmin   2885 bytes  Function
                          eigs     11 KB     Function
                       eigvals     10 KB     Function
                      eigvals!     10 KB     Function
                       eigvecs     10 KB     Function


Funally, let us list all we have in `Julia`'s `Base` module. __It is a long list!__ 
Notice that `Dates` and `LinAlg` are modules themselves.

In [37]:
whos(Base)

                             !   2222 bytes  Function
                            !=     15 KB     Function
                           !==     75 KB     Function
                             $     30 KB     Function
                             %     60 KB     Function
                             &     34 KB     Function
                             *    104 KB     Function
                             +    147 KB     Function
                             -    151 KB     Function
                           .!=   7199 bytes  Function
                            .%   4284 bytes  Function
                            .*     15 KB     Function
                            .+     21 KB     Function
                            .-     20 KB     Function
                            ./     10 KB     Function
                           .//   2548 bytes  Function
                            .<   7658 bytes  Function
                           .<<   2550 bytes  Function
                           .