# Julia is Open - `whos()`, `methods()`, `@which`, ...

---

`Julia` is an open-source project, source being entirely hosted on `github`: http://github.com/julialang

The code consists of (actual numbers may differ):

- 29K lines of `C/C++`
- 6K lines of `scheme`
- 68K lines of `julia`

Julia uses [LLVM](http://llvm.org) which itself has 680K lines of code. Therefore, `Julia` is very compact, compared to other languages, like LLVM's `C` compiler `clang` (513K lines of code) or `gcc`  (3,530K lines). This makes it easy to read the actuall code and get full information, in spite the fact that some parts of the documentation are insufficient. `Julia`'s "navigating" system,
consisting of commands `whos()`, `methods()` and `@which`, makes this even easier.

Further, the `Base` (core) of `Julia` is kept small, and the rest of the functionality is obtained through packages.
Since packages are written in `Julia`, they are navigated on the same way.




In this notebook, we demonstrate how to get help and navigate the source code.

## Prerequisites

Basic knowledge of programming in any language.

Read [Methods](http://julia.readthedocs.org/en/latest/manual/methods/) section of the `Julia` manual. (5 min)

## Competences 

The reader should be able to read the code and be able to find and understand calling sequences and outputs of any function.

## Credits 

Some examples are taken from [The Julia Manual](http://julia.readthedocs.org/en/latest/manual/).


## Operators `+`, `*` and `⋅`

Consider operators `+`, `*` and `⋅`, the first two of them seem rather basic in any language. The `⋅` symbol is typed as LaTeX command `\cdot` + `Tab`.

`?+` gives some information, which is vary sparse. We would expect more details, and we also suspect that `+` can be used in more ways that just hose two.

`?*` explaind more instances where `*` can be used, but the text itself is vague and not sufficient. 

`?⋅` appears to be what we expect fro the dot product off two vectors.

In [1]:
?+

search: + .+



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.


In [2]:
?*

search: * .*



```
*(A, B)
```

Matrix multiplication.

```
*(x, y...)
```

Multiplication operator. `x*y*z*...` calls this function with all arguments, i.e. `*(x, y, z, ...)`.

```
*(s, t)
```

Concatenate strings. The `*` operator is an alias to this function.

```jldoctest
julia> "Hello " * "world"
"Hello world"
```


In [3]:
?⋅

search: ⋅



```
dot(x, y)
⋅(x,y)
```

Compute the dot product. For complex vectors, the first vector is conjugated.

```
dot(n, X, incx, Y, incy)
```

Dot product of two vectors consisting of `n` elements of array `X` with stride `incx` and `n` elements of array `Y` with stride `incy`.


## methods()

`Julia` functions have a feature called _multiple dispatch_, which means that the method depends on the name __AND__ the input.
Full range of existing methods for certain function name is given by the `methods()` command. 
> Running `methods(+)` sheds a completely differfent light on `+`.

The great `IJulia` feature is that the links to the source code where the respective version of the function is defined, are readily provided. 

In [4]:
?methods

search: methods methodswith method_exists Method MethodTable MethodError



```
methods(f, [types])
```

Returns the method table for `f`.

If `types` is specified, returns an array of methods whose types match.


### The `"+"` operator

__N.B.__ For convenience, Left click on the left area of the `Out[]` cell toggles  scrolling. Double click collapses the output completely. 

In [5]:
methods(+)

# 163 methods for generic function "+":
+(x::Bool, z::Complex{Bool}) at complex.jl:136
+(x::Bool, y::Bool) at bool.jl:48
+(x::Bool) at bool.jl:45
+{T<:AbstractFloat}(x::Bool, y::T) at bool.jl:55
+(x::Bool, z::Complex) at complex.jl:143
+(x::Bool, A::AbstractArray{Bool,N<:Any}) at arraymath.jl:126
+(x::Float32, y::Float32) at float.jl:239
+(x::Float64, y::Float64) at float.jl:240
+(z::Complex{Bool}, x::Bool) at complex.jl:137
+(z::Complex{Bool}, x::Real) at complex.jl:151
+(a::Float16, b::Float16) at float16.jl:136
+(x::Char, y::Integer) at char.jl:40
+(c::BigInt, x::BigFloat) at mpfr.jl:240
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:298
+(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:291
+(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:285
+(x::BigInt, y::BigInt) at gmp.jl:255
+(x::BigInt, c::Union{UInt16,UInt32,UInt8}) at gmp.jl:310
+(x::BigInt, c::Union{Int16,Int32,Int8}) at gmp.jl:326
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:388
+(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:381
+(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:375
+(x::BigFloat, c::BigInt) at mpfr.jl:236
+(x::BigFloat, y::BigFloat) at mpfr.jl:205
+(x::BigFloat, c::Union{UInt16,UInt32,UInt8}) at mpfr.jl:212
+(x::BigFloat, c::Union{Int16,Int32,Int8}) at mpfr.jl:220
+(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:228
+{T}(B::BitArray{2}, J::UniformScaling{T}) at linalg\uniformscaling.jl:38
+(a::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem, b::Base.Pkg.Resolve.VersionWeights.VWPreBuildItem) at pkg/resolve/versionweight.jl:85
+(a::Base.Pkg.Resolve.VersionWeights.VWPreBuild, b::Base.Pkg.Resolve.VersionWeights.VWPreBuild) at pkg/resolve/versionweight.jl:131
+(a::Base.Pkg.Resolve.VersionWeights.VersionWeight, b::Base.Pkg.Resolve.VersionWeights.VersionWeight) at pkg/resolve/versionweight.jl:181
+(a::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue, b::Base.Pkg.Resolve.MaxSum.FieldValues.FieldValue) at pkg/resolve/fieldvalue.jl:44
+(x::Base.Dates.CompoundPeriod, y::Base.Dates.CompoundPeriod) at dates\periods.jl:314
+(x::Base.Dates.CompoundPeriod, y::Base.Dates.Period) at dates\periods.jl:312
+(x::Base.Dates.CompoundPeriod, y::Base.Dates.TimeType) at dates\periods.jl:359
+(dt::DateTime, z::Base.Dates.Month) at dates\arithmetic.jl:37
+(dt::DateTime, y::Base.Dates.Year) at dates\arithmetic.jl:13
+(x::DateTime, y::Base.Dates.Period) at dates\arithmetic.jl:64
+(x::Date, y::Base.Dates.Day) at dates\arithmetic.jl:62
+(x::Date, y::Base.Dates.Week) at dates\arithmetic.jl:60
+(dt::Date, z::Base.Dates.Month) at dates\arithmetic.jl:43
+(dt::Date, y::Base.Dates.Year) at dates\arithmetic.jl:17
+(y::AbstractFloat, x::Bool) at bool.jl:57
+{T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8}}(x::T, y::T) at int.jl:32
+(x::Integer, y::Ptr) at pointer.jl:108
+(z::Complex, w::Complex) at complex.jl:125
+(z::Complex, x::Bool) at complex.jl:144
+(x::Real, z::Complex{Bool}) at complex.jl:150
+(x::Real, z::Complex) at complex.jl:162
+(z::Complex, x::Real) at complex.jl:163
+(x::Rational, y::Rational) at rational.jl:202
+(x::Integer, y::Char) at char.jl:41
+{N}(i::Integer, index::CartesianIndex{N}) at multidimensional.jl:58
+(c::Union{UInt16,UInt32,UInt8}, x::BigInt) at gmp.jl:314
+(c::Union{Int16,Int32,Int8}, x::BigInt) at gmp.jl:327
+(c::Union{UInt16,UInt32,UInt8}, x::BigFloat) at mpfr.jl:216
+(c::Union{Int16,Int32,Int8}, x::BigFloat) at mpfr.jl:224
+(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:232
+(x::Irrational, y::Irrational) at irrationals.jl:88
+(x::Number) at operators.jl:115
+{T<:Number}(x::T, y::T) at promotion.jl:255
+(x::Number, y::Number) at promotion.jl:190
+(r1::OrdinalRange, r2::OrdinalRange) at operators.jl:505
+{T<:AbstractFloat}(r1::FloatRange{T}, r2::FloatRange{T}) at operators.jl:512
+{T<:AbstractFloat}(r1::LinSpace{T}, r2::LinSpace{T}) at operators.jl:531
+(r1::Union{FloatRange,LinSpace,OrdinalRange}, r2::Union{FloatRange,LinSpace,Ord

Following the third link, we get the following code snippet:
```
+(x::Bool) = int(x)
-(x::Bool) = -int(x)
+(x::Bool, y::Bool) = int(x) + int(y)
-(x::Bool, y::Bool) = int(x) - int(y)
*(x::Bool, y::Bool) = x & y
```

Therefore:

In [6]:
+(true), +(false),-(true),-(false)

(1,0,-1,0)

In [7]:
x, y = BitArray([0,1,0,1,0,1]), BitArray([0,1,1,1,1,0])

(Bool[false,true,false,true,false,true],Bool[false,true,true,true,true,false])

The above command is equivalent to 
```
x = bitpack([0,1,0,1,0,1]); y = bitpack([0,1,1,1,1,0])
```
except that only the last result would be displayed

In [8]:
+x,-(x)

(Bool[false,true,false,true,false,true],[0,-1,0,-1,0,-1])

In [9]:
x+y, +(x,y)

([0,2,1,2,1,1],[0,2,1,2,1,1])

In [10]:
c1=x+y

6-element Array{Int64,1}:
 0
 2
 1
 2
 1
 1

In [11]:
c2=+(x,y)

6-element Array{Int64,1}:
 0
 2
 1
 2
 1
 1

### Manipulating dates

We see that one of the `+` methods is adding days to time: 

```
 +(x::Date,y::Base.Dates.Day) at dates/arithmetic.jl:60
```
Therefore, the 135-th day from today is:

In [12]:
Dates.today()

2017-04-19

In [13]:
dd=Dates.today()+Dates.Day(135)

2017-09-01

In [14]:
typeof(dd)

Date

More information about the two types can be obtained by `methods(Dates.Date)` and `methods(Dates.Day)`, respectively. 

### Adding tridiagonal matrices

In the above output of `methods(+)`,  we see that we can add tridiagonal matrices:
```
+(A::Tridiagonal{T}, B::Tridiagonal{T}) at linalg/tridiag.jl:404
```
Following the link, we see that the method separately adds lower, main and upper diagonals, denoted by `dl`, `d` and `du`, respectively:
```
404: +(A::Tridiagonal, B::Tridiagonal) = Tridiagonal(A.dl+B.dl, A.d+B.d, A.du+B.du)
```
Let us see how exactly is the type `Tridiagonal` defined:

In [15]:
methods(Tridiagonal)

# 6 methods for generic function "(::Type)":
(::Type{Tridiagonal}){T}(dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}, du2::Array{T,1}) at linalg\tridiag.jl:319
(::Type{Tridiagonal}){T}(dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}) at linalg\tridiag.jl:335
(::Type{Tridiagonal}){T}(M::Bidiagonal{T}) at linalg\bidiag.jl:137
(::Type{Tridiagonal}){Tl,Td,Tu}(dl::AbstractArray{Tl,1}, d::AbstractArray{Td,1}, du::AbstractArray{Tu,1}) at linalg\tridiag.jl:344
(::Type{Tridiagonal})(A::AbstractArray{T<:Any,2}) at linalg\tridiag.jl:355
(::Type{T}){T}(arg) at sysimg.jl:53

This output seems confusing, but from the second line we conclude that we can define three diagonals, lower, main and upper diagonal, denoted as above. We also know that that the lower and upper diagonals are of size $n-1$. Let us try it out:

In [16]:
T1 = Tridiagonal(rand(6),rand(7),rand(6))

7×7 Tridiagonal{Float64}:
 0.244947   0.0498246   ⋅         ⋅         ⋅         ⋅         ⋅      
 0.0466415  0.370643   0.675246   ⋅         ⋅         ⋅         ⋅      
  ⋅         0.198166   0.625542  0.951448   ⋅         ⋅         ⋅      
  ⋅          ⋅         0.176512  0.623833  0.844704   ⋅         ⋅      
  ⋅          ⋅          ⋅        0.774254  0.451302  0.134293   ⋅      
  ⋅          ⋅          ⋅         ⋅        0.6204    0.92166   0.411225
  ⋅          ⋅          ⋅         ⋅         ⋅        0.950335  0.119784

In [17]:
full(T1)

7×7 Array{Float64,2}:
 0.244947   0.0498246  0.0       0.0       0.0       0.0       0.0     
 0.0466415  0.370643   0.675246  0.0       0.0       0.0       0.0     
 0.0        0.198166   0.625542  0.951448  0.0       0.0       0.0     
 0.0        0.0        0.176512  0.623833  0.844704  0.0       0.0     
 0.0        0.0        0.0       0.774254  0.451302  0.134293  0.0     
 0.0        0.0        0.0       0.0       0.6204    0.92166   0.411225
 0.0        0.0        0.0       0.0       0.0       0.950335  0.119784

In [18]:
T2 = Tridiagonal(rand(-5:5,6),randn(7),rand(-9:0,6))

7×7 Tridiagonal{Float64}:
 0.733067  -2.0        ⋅         ⋅        ⋅          ⋅          ⋅      
 5.0       -0.33284  -4.0        ⋅        ⋅          ⋅          ⋅      
  ⋅         1.0      -1.14754  -6.0       ⋅          ⋅          ⋅      
  ⋅          ⋅        5.0       1.2479  -2.0         ⋅          ⋅      
  ⋅          ⋅         ⋅       -3.0      0.978454  -6.0         ⋅      
  ⋅          ⋅         ⋅         ⋅       5.0        0.401844  -2.0     
  ⋅          ⋅         ⋅         ⋅        ⋅        -3.0       -0.894658

In [21]:
T3=T1+T2

7×7 Tridiagonal{Float64}:
 0.978014  -1.95018      ⋅          ⋅         ⋅         ⋅         ⋅      
 5.04664    0.0378037  -3.32475     ⋅         ⋅         ⋅         ⋅      
  ⋅         1.19817    -0.521998  -5.04855    ⋅         ⋅         ⋅      
  ⋅          ⋅          5.17651    1.87174  -1.1553     ⋅         ⋅      
  ⋅          ⋅           ⋅        -2.22575   1.42976  -5.86571    ⋅      
  ⋅          ⋅           ⋅          ⋅        5.6204    1.3235   -1.58877 
  ⋅          ⋅           ⋅          ⋅         ⋅       -2.04966  -0.774874

In [19]:
@which T1 + T2

+(A::Tridiagonal, B::Tridiagonal) at linalg\tridiag.jl:494

This worked as expected, the result is again a `Tridiagonal`. We can access each diagonal by:

In [22]:
println(T3.dl, T3.d, T3.du)

[5.04664,1.19817,5.17651,-2.22575,5.6204,-2.04966][0.978014,0.0378037,-0.521998,1.87174,1.42976,1.3235,-0.774874][-1.95018,-3.32475,-5.04855,-1.1553,-5.86571,-1.58877]


### `@which`

Let us take a closer look at what happens. The `@which` command gives the link to the part of the code which is actually invoked. The argument should be only function, without assignment, that is 
```
@which T1=Tridiagonal(rand(6),rand(7),rand(6))
```
throws an error.

In [23]:
@which Tridiagonal(rand(6),rand(7),rand(6))

(::Type{Tridiagonal}){T}(dl::Array{T,1}, d::Array{T,1}, du::Array{T,1}) at linalg\tridiag.jl:335

In the code, we see that there is a type definition in the `immutable` block:
```
## Tridiagonal matrices ##
immutable Tridiagonal{T} <: AbstractMatrix{T}
dl::Vector{T} # sub-diagonal
d::Vector{T} # diagonal
du::Vector{T} # sup-diagonal
du2::Vector{T} # supsup-diagonal for pivoting
end
```
The `Tridiagonal` type consists of __four__ vectors.
In our case, we actually called the function `Tridiagonal()` with __three__ vector arguments. The function creates the type of the same name, setting the fourth reqired vector `du2` to `zeros(T,n-2)`.

The next function with the same name is invoked when the input vectors have different types, in which case the types arer promoted to a most general one, if possible.

In [24]:
T4 = Tridiagonal([1,2,3], [2.0,3.0,pi,4.0],rand(3)+im*rand(3))

4×4 Tridiagonal{Complex{Float64}}:
 2.0+0.0im  0.15579+0.753237im           ⋅                    ⋅         
 1.0+0.0im      3.0+0.0im       0.658566+0.825549im           ⋅         
     ⋅          2.0+0.0im        3.14159+0.0im       0.247965+0.670974im
     ⋅              ⋅                3.0+0.0im            4.0+0.0im     

### `size()` and `full()`

For each matrix type we need to define the function which returns the size of a matrix, and the function which converts the matrix of a given type to a full matrix. These function are listed after the second `Tridiagonal()` function.

In [25]:
size(T4)

(4,4)

In [26]:
T4 = full(T4)

4×4 Array{Complex{Float64},2}:
 2.0+0.0im  0.15579+0.753237im       0.0+0.0im            0.0+0.0im     
 1.0+0.0im      3.0+0.0im       0.658566+0.825549im       0.0+0.0im     
 0.0+0.0im      2.0+0.0im        3.14159+0.0im       0.247965+0.670974im
 0.0+0.0im      0.0+0.0im            3.0+0.0im            4.0+0.0im     

### `sizeof()` 

Of course, using special types can leasd to much more efficient programs. For example, for `Tridiagonal` type, onlt four diagonals are stored, in comparison to storing full matrix when $n^2$ elements are stored. The storage used is obtained by the `sizeof()` function.

In [27]:
T1

7×7 Tridiagonal{Float64}:
 0.244947   0.0498246   ⋅         ⋅         ⋅         ⋅         ⋅      
 0.0466415  0.370643   0.675246   ⋅         ⋅         ⋅         ⋅      
  ⋅         0.198166   0.625542  0.951448   ⋅         ⋅         ⋅      
  ⋅          ⋅         0.176512  0.623833  0.844704   ⋅         ⋅      
  ⋅          ⋅          ⋅        0.774254  0.451302  0.134293   ⋅      
  ⋅          ⋅          ⋅         ⋅        0.6204    0.92166   0.411225
  ⋅          ⋅          ⋅         ⋅         ⋅        0.950335  0.119784

In [28]:
T1f=full(T1)

7×7 Array{Float64,2}:
 0.244947   0.0498246  0.0       0.0       0.0       0.0       0.0     
 0.0466415  0.370643   0.675246  0.0       0.0       0.0       0.0     
 0.0        0.198166   0.625542  0.951448  0.0       0.0       0.0     
 0.0        0.0        0.176512  0.623833  0.844704  0.0       0.0     
 0.0        0.0        0.0       0.774254  0.451302  0.134293  0.0     
 0.0        0.0        0.0       0.0       0.6204    0.92166   0.411225
 0.0        0.0        0.0       0.0       0.0       0.950335  0.119784

In [29]:
sizeof(T1f)  #   392 =  7 * 7 * 8 bytes

392

In [30]:
sizeof(T1) # This is not yet implemented for Tridiagonal - only the storage required for 4 vector variables' names is displayed

32

### `immutable`

The `immutable` command means that we can change individual elements of defined parts, but not the parts as a whole (an alternative is to use the `type` construtor). For example: 

In [31]:
@show T5 = Tridiagonal([1,2,3],[2,3,4,5],[-1,1,2])
T5.d[2]=123
@show T5
T5.dl = [-1, -1 ,1]

T5 = Tridiagonal([1,2,3],[2,3,4,5],[-1,1,2]) = [2 -1 0 0; 1 3 1 0; 0 2 4 2; 0 0 3 5]
T5 = [2 -1 0 0; 1 123 1 0; 0 2 4 2; 0 0 3 5]


LoadError: type Tridiagonal is immutable

### `methodswith()`

This is the reverse of `methods()` - which methods exist for the given type. For example, what can we do with `Tridiagonal` matrices, or with `Dates.Day`:

In [32]:
methodswith(Tridiagonal)

91-element Array{Method,1}:
 *(A::Tridiagonal, B::Number) at linalg\tridiag.jl:496                                                                                                                                   
 *(A::Tridiagonal, B::UpperTriangular) at linalg\triangular.jl:1324                                                                                                                      
 *(A::Tridiagonal, B::Base.LinAlg.UnitUpperTriangular) at linalg\triangular.jl:1324                                                                                                      
 *(A::Tridiagonal, B::LowerTriangular) at linalg\triangular.jl:1324                                                                                                                      
 *(A::Tridiagonal, B::Base.LinAlg.UnitLowerTriangular) at linalg\triangular.jl:1324                                                                                                      
 *(A::Base.LinAlg.AbstractTriangular, B::Union{Bidiagonal,SymTridiagonal,Tridiagonal}) at linalg\bidiag.jl:415                                                                           
 *(A::Union{Bidiagonal,SymTridiagonal,Tridiagonal}, B::Union{Bidiagonal,SymTridiagonal,Tridiagonal}) at linalg\bidiag.jl:416                                                             
 *(B::Number, A::Tridiagonal) at linalg\tridiag.jl:497                                                                                                                                   
 +(A::Array{T<:Any,2}, B::Tridiagonal) at linalg\special.jl:121                                                                                                                          
 +(A::Tridiagonal, B::Tridiagonal) at linalg\tridiag.jl:494                                                                                                                              
 +(A::Diagonal, B::Tridiagonal) at linalg\special.jl:120                                                                                                                                 
 +(A::Tridiagonal, B::Diagonal) at linalg\special.jl:121                                                                                                                                 
 +(A::Bidiagonal, B::Tridiagonal) at linalg\special.jl:120                                                                                                                               
 +(A::Tridiagonal, B::Bidiagonal) at linalg\special.jl:121                                                                                                                               
 +(A::Tridiagonal, B::Array{T<:Any,2}) at linalg\special.jl:120                                                                                                                          
 +(A::SymTridiagonal, B::Tridiagonal) at linalg\special.jl:129                                                                                                                           
 +(A::Tridiagonal, B::SymTridiagonal) at linalg\special.jl:130                                                                                                                           
 +(A::Base.LinAlg.AbstractTriangular, B::Tridiagonal) at linalg\special.jl:157                                                                                                           
 +(A::Tridiagonal, B::Base.LinAlg.AbstractTriangular) at linalg\special.jl:158                                                                                                           
 -(A::Tridiagonal, B::Tridiagonal) at linalg\tridiag.jl:495                                                                                                                              
 -(A::Diagonal, B::Tridiagonal) at linalg\special.jl:120                                                                                                                                 
 -(A::Tridiagonal, B::Diagonal) at linalg\special.jl:121          

In [33]:
methodswith(Dates.Day)

8-element Array{Method,1}:
 +(x::Date, y::Base.Dates.Day) at dates\arithmetic.jl:62                           
 -(x::Date, y::Base.Dates.Day) at dates\arithmetic.jl:63                           
 convert(::Type{Base.Dates.Week}, x::Base.Dates.Day) at dates\periods.jl:398       
 convert(::Type{Base.Dates.Hour}, x::Base.Dates.Day) at dates\periods.jl:391       
 convert(::Type{Base.Dates.Minute}, x::Base.Dates.Day) at dates\periods.jl:391     
 convert(::Type{Base.Dates.Second}, x::Base.Dates.Day) at dates\periods.jl:391     
 convert(::Type{Base.Dates.Millisecond}, x::Base.Dates.Day) at dates\periods.jl:391
 floor(dt::Date, p::Base.Dates.Day) at dates\rounding.jl:66

### The `"*"` operator

In [34]:
methods(*)

# 149 methods for generic function "*":
*(x::Bool, z::Complex{Bool}) at complex.jl:140
*(x::Bool, y::Bool) at bool.jl:50
*{T<:Unsigned}(x::Bool, y::T) at bool.jl:63
*(x::Bool, z::Complex) at complex.jl:147
*(x::Bool, y::Irrational) at irrationals.jl:90
*{T<:Number}(x::Bool, y::T) at bool.jl:60
*(x::Float32, y::Float32) at float.jl:243
*(x::Float64, y::Float64) at float.jl:244
*(z::Complex{Bool}, x::Bool) at complex.jl:141
*(z::Complex{Bool}, x::Real) at complex.jl:159
*(a::Float16, b::Float16) at float16.jl:136
*(this::Base.Grisu.Float, other::Base.Grisu.Float) at grisu/float.jl:138
*(c::BigInt, x::BigFloat) at mpfr.jl:240
*(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) at gmp.jl:298
*(a::BigInt, b::BigInt, c::BigInt, d::BigInt) at gmp.jl:291
*(a::BigInt, b::BigInt, c::BigInt) at gmp.jl:285
*(x::BigInt, y::BigInt) at gmp.jl:255
*(x::BigInt, c::Union{UInt16,UInt32,UInt8}) at gmp.jl:332
*(x::BigInt, c::Union{Int16,Int32,Int8}) at gmp.jl:338
*(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) at mpfr.jl:388
*(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) at mpfr.jl:381
*(a::BigFloat, b::BigFloat, c::BigFloat) at mpfr.jl:375
*(x::BigFloat, c::BigInt) at mpfr.jl:236
*(x::BigFloat, y::BigFloat) at mpfr.jl:205
*(x::BigFloat, c::Union{UInt16,UInt32,UInt8}) at mpfr.jl:212
*(x::BigFloat, c::Union{Int16,Int32,Int8}) at mpfr.jl:220
*(x::BigFloat, c::Union{Float16,Float32,Float64}) at mpfr.jl:228
*(B::BitArray{2}, J::UniformScaling) at linalg\uniformscaling.jl:132
*(z::Complex, w::Complex) at complex.jl:127
*{T<:Union{Int128,UInt128}}(x::T, y::T) at int.jl:426
*{T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8}}(x::T, y::T) at int.jl:33
*(z::Complex, x::Bool) at complex.jl:148
*(x::Real, z::Complex{Bool}) at complex.jl:158
*(x::Real, z::Complex) at complex.jl:170
*(z::Complex, x::Real) at complex.jl:171
*(x::Rational, y::Rational) at rational.jl:209
*{N}(a::Integer, index::CartesianIndex{N}) at multidimensional.jl:61
*(c::Union{UInt16,UInt32,UInt8}, x::BigInt) at gmp.jl:336
*(c::Union{Int16,Int32,Int8}, x::BigInt) at gmp.jl:342
*(c::Union{UInt16,UInt32,UInt8}, x::BigFloat) at mpfr.jl:216
*(c::Union{Int16,Int32,Int8}, x::BigFloat) at mpfr.jl:224
*(c::Union{Float16,Float32,Float64}, x::BigFloat) at mpfr.jl:232
*{T<:Number}(x::T, D::Diagonal) at linalg\diagonal.jl:113
*(x::Irrational, y::Irrational) at irrationals.jl:88
*(y::Real, x::Base.Dates.Period) at dates\periods.jl:90
*(x::Number) at operators.jl:116
*(y::Number, x::Bool) at bool.jl:65
*{T<:Number}(x::T, y::T) at promotion.jl:256
*(x::Number, y::Number) at promotion.jl:191
*{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(A::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}, x::Union{Base.ReshapedArray{S,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{S,1},SubArray{S,1,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}) at linalg\matmul.jl:79
*(A::SymTridiagonal, B::Number) at linalg\tridiag.jl:98
*(A::Tridiagonal, B::Number) at linalg\tridiag.jl:496
*(A::UpperTriangular, x::Number) at linalg\triangular.jl:477
*(A::Base.LinAlg.UnitUpperTriangular, x::Number) at linalg\triangular.jl:480
*(A::LowerTriangular, x::Number) at linalg\triangular.jl:477
*(A::Base.LinAlg.UnitLowerTriangular, x::Number) at linalg\triangular.jl:480
*(A::Tridiagonal, B::UpperTriangular) at linalg\triangular.jl:1324
*(A::Tri

We can multiply various types of numbers and matrices. Notice, however, that there is no multiplication specifically defined for `Tridiagonal` matrices. This would not make much sense, since the product of two tridiagonal matrices is a pentadiagonal matrix, the product of three tridiagonal matrices is septadiagonal matrix, ...

Therefore, two tridiagonal matrices are first converted to full matrices, and then multiplied, as is seen in the source code.

In [35]:
T1*T2

7×7 Array{Float64,2}:
 0.428686  -0.506479  -0.199299   0.0       0.0        0.0         0.0     
 1.88741    0.458598  -2.25744   -4.05147   0.0        0.0         0.0     
 0.990828   0.559585   3.24674   -2.56594  -1.9029     0.0         0.0     
 0.0        0.176512   2.91661   -2.8147   -0.421161  -5.06823     0.0     
 0.0        0.0        3.87127   -0.38771  -0.435464  -2.65385    -0.268587
 0.0        0.0        0.0       -1.8612    5.21533   -4.58571    -2.21123 
 0.0        0.0        0.0        0.0       4.75168    0.0225352  -2.00784 

In [36]:
@which T1*T2

*(A::Union{Bidiagonal,SymTridiagonal,Tridiagonal}, B::Union{Bidiagonal,SymTridiagonal,Tridiagonal}) at linalg\bidiag.jl:416

In [37]:
T1*T2*T1

7×7 Array{Float64,2}:
 0.0813826  -0.205858  -0.466667  -0.189622    0.0       0.0        0.0     
 0.483705   -0.183332  -1.8176    -4.67528    -3.4223    0.0        0.0     
 0.268801    0.900166   1.95591    0.0150613  -3.02624  -0.255546   0.0     
 0.0082328   0.643395   1.44682    0.693012   -5.71199  -4.72774   -2.08418 
 0.0         0.767153   2.35321    3.10429    -2.17047  -2.75967   -1.1235  
 0.0         0.0       -0.328524   2.87692    -2.06345  -5.62749   -2.15063 
 0.0         0.0        0.0        3.67901     2.15842  -1.24923   -0.231239

### The "$\cdot$" operator

In [38]:
methods(⋅)

# 11 methods for generic function "dot":
dot(x::BitArray{1}, y::BitArray{1}) at linalg\bitarray.jl:5
dot(x::Number, y::Number) at linalg\generic.jl:301
dot{T<:Union{Float32,Float64}}(DX::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,1},DenseArray{T,N<:Any},SubArray{T,1,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}, DY::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,1},DenseArray{T,N<:Any},SubArray{T,1,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}) at linalg\blas.jl:290
dot{T<:Union{Float32,Float64},TI<:Integer}(x::Array{T,1}, rx::Union{Range{TI},UnitRange{TI}}, y::Array{T,1}, ry::Union{Range{TI},UnitRange{TI}}) at linalg\matmul.jl:48
dot{T<:Union{Complex{Float32},Complex{Float64}},TI<:Integer}(x::Array{T,1}, rx::Union{Range{TI},UnitRange{TI}}, y::Array{T,1}, ry::Union{Range{TI},UnitRange{TI}}) at linalg\matmul.jl:61
dot{Tx<:Number,Ty<:Number}(x::Union{Base.ReshapedArray{Tx,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{Tx,1},SubArray{Tx,1,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}, y::AbstractSparseArray{Ty,Ti<:Any,1}) at sparse\sparsevector.jl:1295
dot{Tx<:Number,Ty<:Number}(x::AbstractSparseArray{Tx,Ti<:Any,1}, y::AbstractSparseArray{Ty,Ti<:Any,1}) at sparse\sparsevector.jl:1340
dot{Tx<:Number,Ty<:Number}(x::AbstractSparseArray{Tx,Ti<:Any,1}, y::AbstractArray{Ty,1}) at sparse\sparsevector.jl:1307
dot(x::AbstractArray{T<:Any,1}, y::AbstractArray{T<:Any,1}) at linalg\generic.jl:302
dot(n::Integer, DX::Union{DenseArray{Float64,N<:Any},Ptr{Float64}}, incx::Integer, DY::Union{DenseArray{Float64,N<:Any},Ptr{Float64}}, incy::Integer) at linalg\blas.jl:247
dot(n::Integer, DX::Union{DenseArray{Float32,N<:Any},Ptr{Float32}}, incx::Integer, DY::Union{DenseArray{Float32,N<:Any},Ptr{Float32}}, incy::Integer) at linalg\blas.jl:247

By inspecting the source, we see that the `scalar` or the `dot` product of two vectors (1-dimensional arrays) is 
computed via `BLAS` function `dot` for real arguments, and the function `dotc` for complex arguments.  

In [39]:
x = rand(1:5,5); y  = rand(-5:0,5); a = x⋅y
z = rand(5); b = x⋅z; c = z⋅x
w = rand(5) + im*rand(5); d = x⋅w; e = z⋅w; f = w⋅z
@show x, y, z, w
@show a, b, c, d, e, f

(x,y,z,w) = ([5,1,2,5,4],[-4,-5,-5,-1,-1],[0.18227,0.246293,0.79531,0.350186,0.881482],Complex{Float64}[0.137062+0.779661im,0.420614+0.817883im,0.00927016+0.732884im,0.951312+0.3763im,0.458019+0.73735im])
(a,b,c,d,e,f) = (-44,8.025117533903412,8.025117533903412,7.713101623383132 + 11.012856620885627im,0.8728205557925923 + 1.708152921907408im,0.8728205557925923 - 1.708152921907408im)


(-44,8.025117533903412,8.025117533903412,7.713101623383132 + 11.012856620885627im,0.8728205557925923 + 1.708152921907408im,0.8728205557925923 - 1.708152921907408im)

## `whos()`

The command `whos()` reveals the content of the specified package or module. It can be invoked either with the package name, or with the package name and a regular expression.

In [40]:
whos(Dates)

                           Apr      8 bytes  Int64
                         April      8 bytes  Int64
                           Aug      8 bytes  Int64
                        August      8 bytes  Int64
                          Date    112 bytes  DataType
                    DateFormat    136 bytes  DataType
                    DatePeriod     92 bytes  DataType
                      DateTime    112 bytes  DataType
                         Dates   6069 KB     Module
                           Day    112 bytes  DataType
                           Dec      8 bytes  Int64
                      December      8 bytes  Int64
                           Feb      8 bytes  Int64
                      February      8 bytes  Int64
                           Fri      8 bytes  Int64
                        Friday      8 bytes  Int64
                          Hour    112 bytes  DataType
                 ISODateFormat    265 bytes  Base.Dates.DateFormat
             ISODateTimeFormat    461 bytes  Ba

In [41]:
whos(LinAlg)

                             /      0 bytes  Base.#/
               ARPACKException    112 bytes  DataType
                     A_ldiv_B!      0 bytes  Base.LinAlg.#A_ldiv_B!
                     A_ldiv_Bc      0 bytes  Base.#A_ldiv_Bc
                     A_ldiv_Bt      0 bytes  Base.#A_ldiv_Bt
                      A_mul_B!      0 bytes  Base.LinAlg.#A_mul_B!
                      A_mul_Bc      0 bytes  Base.#A_mul_Bc
                     A_mul_Bc!      0 bytes  Base.LinAlg.#A_mul_Bc!
                      A_mul_Bt      0 bytes  Base.#A_mul_Bt
                     A_mul_Bt!      0 bytes  Base.LinAlg.#A_mul_Bt!
                     A_rdiv_Bc      0 bytes  Base.#A_rdiv_Bc
                     A_rdiv_Bt      0 bytes  Base.#A_rdiv_Bt
                     Ac_ldiv_B      0 bytes  Base.#Ac_ldiv_B
                    Ac_ldiv_B!      0 bytes  Base.LinAlg.#Ac_ldiv_B!
                    Ac_ldiv_Bc      0 bytes  Base.#Ac_ldiv_Bc
                      Ac_mul_B      0 bytes  Base.#Ac_mul_B
      

In [43]:
# Now with a regular expression - we are looking for 
# 'eigenvalue' related stuff. 
whos(Base, Regex("eig"))

                           eig      0 bytes  Base.LinAlg.#eig
                       eigfact      0 bytes  Base.LinAlg.#eigfact
                      eigfact!      0 bytes  Base.LinAlg.#eigfact!
                        eigmax      0 bytes  Base.LinAlg.#eigmax
                        eigmin      0 bytes  Base.LinAlg.#eigmin
                          eigs      0 bytes  Base.LinAlg.#eigs
                       eigvals      0 bytes  Base.LinAlg.#eigvals
                      eigvals!      0 bytes  Base.LinAlg.#eigvals!
                       eigvecs      0 bytes  Base.LinAlg.#eigvecs


Funally,let us list all we have in `Julia`'s `Base` module. __It is a long list!__ 
Notice that `Dates` and `LinAlg` are modules themselves.

In [44]:
whos(Base)

                             !      0 bytes  Base.#!
                            !=      0 bytes  Base.#!=
                           !==      0 bytes  Base.#!==
                             $      0 bytes  Base.#$
                             %      0 bytes  Base.#rem
                             &      0 bytes  Base.#&
                             *      0 bytes  Base.#*
                             +      0 bytes  Base.#+
                             -      0 bytes  Base.#-
                           .!=      0 bytes  Base.#.!=
                            .%      0 bytes  Base.#.%
                            .*      0 bytes  Base.#.*
                            .+      0 bytes  Base.#.+
                            .-      0 bytes  Base.#.-
                            ./      0 bytes  Base.#./
                           .//      0 bytes  Base.#.//
                            .<      0 bytes  Base.#.<
                           .<<      0 bytes  Base.#.<<
                           .<