# Working with Packages

---

Starting Julia loads Julia kernel and `Base` module. The `Base` (core) is kept small and all other functionality is accessible through packages which need to be individually included by the user.

Currently there are __1300+__ registered packages listed at 
[Julia Package Listing](http://pkg.julialang.org/).

In this notebook, we demonstrate how to use packages.

## Prerequisites

Read section [Packages](https://docs.julialang.org/en/stable/manual/packages/) of the Julia manual (15 min). 


## Competences 

The reader should be able to install and use registered and unregistered packages and create own packages.


## Credits 

Some examples are taken from [The Julia Manual](http://julia.readthedocs.org/en/latest/manual/).

---

## `Pkg.status()`

In [1]:
?Pkg.status()

```
status()
```

Prints out a summary of what packages are installed and what version and state they're in.


In [2]:
Pkg.status() # This is slow due to communication with GitHub

18 required packages:
 - Arrowhead                     0.0.1+             master
 - Clp                           0.3.0
 - Clustering                    0.7.0
 - DataFrames                    0.9.0
 - Gadfly                        0.6.0
 - Graphs                        0.7.1
 - IJulia                        1.4.1
 - IJuliaPortrayals              0.0.4              76632d2b (dirty)
 - ImageMagick                   0.2.3
 - Images                        0.9.1
 - Interact                      0.4.3
 - PyPlot                        2.3.1
 - Quaternions                   0.1.1
 - SpecialMatrices               0.1.3+             master
 - SymPy                         0.5.1
 - TestImages                    0.2.0
 - Wavelets                      0.6.1
 - Winston                       0.12.1             8b5e10e1 (dirty)
97 additional packages:
 - AxisAlgorithms                0.1.6
 - AxisArrays                    0.1.2
 - BaseTestNext                  0.2.2
 - BinDeps                       0.

## `Pkg.add()`

This command adds registered package from [Julia Package Listing](http://pkg.julialang.org/).
Adding the package downloads the package source code (and all other required packages) to your `.julia/v0.5/` directory.

GitHub repository names of registered Julia packages always end with the extension `.jl`, which is ommited in `Pkg.add()` command. The example below installs the package from the GitHub repository https://github.com/JuliaLang/Graphs.jl.

N.B. There are other registered packages dealing with graphs, please check them out.

In [2]:
?Pkg.add

```
add(pkg, vers...)
```

Add a requirement entry for `pkg` to `Pkg.dir("REQUIRE")` and call `Pkg.resolve()`. If `vers` are given, they must be `VersionNumber` objects and they specify acceptable version intervals for `pkg`.


In [3]:
# Pkg.add("Graphs")

In [4]:
a=readdir("/Users/Ivan/.julia/v0.5") # This is Julia's default display

125-element Array{String,1}:
 ".cache"          
 ".trash"          
 "Arrowhead"       
 "AxisAlgorithms"  
 "AxisArrays"      
 "BaseTestNext"    
 "BinDeps"         
 "BufferedStreams" 
 "Cairo"           
 "Calculus"        
 "CatIndices"      
 "Cbc"             
 "Clp"             
 ⋮                 
 "SymPy"           
 "TestImages"      
 "TexExtensions"   
 "TiledIteration"  
 "Tk"              
 "URIParser"       
 "Wavelets"        
 "WinRPM"          
 "Winston"         
 "WoodburyMatrices"
 "ZipFile"         
 "ZMQ"             

In [5]:
println(a)

String[".cache",".trash","Arrowhead","AxisAlgorithms","AxisArrays","BaseTestNext","BinDeps","BufferedStreams","Cairo","Calculus","CatIndices","Cbc","Clp","Clustering","Colors","ColorTypes","ColorVectorSpace","Compat","Compose","ComputationalResources","Conda","Contour","CoordinateTransformations","CustomUnitRanges","DataArrays","DataFrames","DataStructures","Dates","DiffBase","Distances","Distributions","DoubleDouble","DualNumbers","FFTViews","FileIO","FixedPointNumbers","FixedSizeArrays","ForwardDiff","Gadfly","Graphics","Graphs","Gtk","GtkReactive","GZip","Hexagons","Hiccup","IJulia","IJuliaPortrayals","ImageAxes","ImageCore","ImageFiltering","ImageMagick","ImageMetadata","Images","ImageTransformations","IncrementalSVD","IndirectArrays","IniFile","Interact","Interpolations","IntervalSets","Iterators","JSON","Juno","KernelDensity","LaTeXStrings","LibExpat","Libz","LinearAlgebra","LineSearches","Loess","MacroTools","MappedArrays","MathProgBase","MatrixDepot","Measures","Media","METADAT

## <a name="contents"></a> Contents of a package

We now have directory `/Users/Ivan/.julia/v0.5/Graphs`. Let us examine its content
(this can also be done directly from the GitHub repository  https://github.com/JuliaLang/Graphs.jl).

### Files

Each package has the following three files:

- `REQUIRE` 
    - may contain the version of Julia needed for the package to run
    - must contain all other registered packages that the present package is using (these packages are installed automatically, if not present) and
    - may contain the version of those packages. 
    
    
    
- `README.md` is the Markdown file, which contains the descritption of the package as displayed on the repository's home page.
- `LICENSE.md` contains the licensing information.

The file `travis.yml`, if present, defines how is the package tested on [Travis-CI](https://travis-ci.org/) after every posted change (via `git push` command). 
Details on using Travis-CI for Julia projects are at 
https://docs.travis-ci.com/user/languages/julia. Since testing is done on machines other than yours, with operating systems other than yours, and using Julia version which may differ from yours, this is a great way to correct bugs, and also a way to give users examples of how to run your code.

### Directories

The `src/` directory contains the actual code of your package.

It must contan the file named as the package itself, `src/Graphs.jl` in this case, which containd the following:

- `module` line starts the description of the main module, which has the same name as the package,
- `using` line(s) lists other registered packages used by the package. These packages are also listed in the `REQUIRE` file.
- `import` line lists the other modules and their components which are modified in this module
- `export` line lists all component which will be accessible directly in the main namespace. The components which are not exported, can still be used but the full name (including mogule name) must be used
- `include()` commands include the source files
- `end` concludes the description of the module.

If Travis-CI is used, the `test/` directory contains the file `runtests.jl` which is exaceuted during the testing, and, eventually, other files that this file is calling.

The `doc/` is optional and is used to store documentation.

The `deps/` directory is optional and is used to store dependencies if the package is using software written in other languages. There are many examples which can be checked out.

## `using` and `import`

Package needs to be added only once, prior to the first use.
We are now ready to use the package. 

We have two methods to do so, which differ in
their treatment of the namespace:
* `using` adds all methods,  constructors etc. from the package into the main namespace, so they can be called directly, like the function `simple_graph(4)` below.
* `import` enables us to use all the methods, constructors, etc. from the package, but they are not included in the namespace, so they must be called together with the package name,
`Graphs.simple_graph(4)`.

N.B. `import` can also be used on a particular function(s), as we shall explain later.

In [8]:
using Graphs

In [9]:
whos(Graphs)

             @graph_implements      0 bytes  Graphs.#@graph_implements
               @graph_requires      0 bytes  Graphs.#@graph_requires
       AbstractDijkstraVisitor     92 bytes  DataType
 AbstractEdgePropertyInspector    148 bytes  DataType
                 AbstractGraph    188 bytes  DataType
          AbstractGraphVisitor     92 bytes  DataType
            AbstractMASVisitor     92 bytes  DataType
           AbstractPrimVisitor     92 bytes  DataType
                 AdjacencyList     80 bytes  TypeConstructor
                 AttributeDict    212 bytes  DataType
AttributeEdgePropertyInspector    168 bytes  DataType
             BellmanFordStates    232 bytes  DataType
                  BreadthFirst     92 bytes  DataType
 ConstantEdgePropertyInspector    168 bytes  DataType
                    DepthFirst     92 bytes  DataType
                DijkstraStates    348 bytes  DataType
                          Edge    192 bytes  DataType
                      EdgeList    120 bytes

### Example

Let us construct the famous graph of the [Seven Bridges of Königsberg](https://en.wikipedia.org/wiki/Seven_Bridges_of_K%C3%B6nigsberg), plot it, and compute the number of _different_ walks which cross 3 bridges between the north side and the center island. Can you enumerate the walks?

For the `plot(g)` to work, [GraphViz](http://www.graphviz.org/) must be installed.

In Windows, this in not enough, and we must use the package [IJuliaPortrayals](https://github.com/jbn/IJuliaPortrayals.jl) 
(with line 263 changed from `gv_process.exitcode == 0` to `gv_process.exitcode != 0` - a bug!).

N.B. `IJuliaPortrayals` can be used to include various media, see the demo of the package.

In [10]:
g=simple_graph(4,is_directed=false)

Undirected Graph (4 vertices, 0 edges)

In [11]:
add_edge!(g,1,2)
add_edge!(g,1,2)
add_edge!(g,1,3)
add_edge!(g,1,3)
add_edge!(g,1,4)
add_edge!(g,2,4)
add_edge!(g,3,4)
g

Undirected Graph (4 vertices, 7 edges)

In [13]:
# Pkg.add("IJuliaPortrayals")
using IJuliaPortrayals

In [15]:
GraphViz(to_dot(g),"neato", "svg")

IJuliaPortrayals.GraphViz("graph graphname {\n1\n2\n3\n4\n1 -- 2\n1 -- 2\n1 -- 3\n1 -- 3\n1 -- 4\n2 -- 4\n3 -- 4\n}\n","neato","svg")

In [16]:
a=adjacency_matrix(g) #This is not what we want

4×4 Array{Bool,2}:
 false   true   true   true
  true  false  false   true
  true  false  false   true
  true   true   true  false

In [17]:
edges(g) # Lets look at the edges

7-element Array{Graphs.Edge{Int64},1}:
 edge [1]: 1 -- 2
 edge [2]: 1 -- 2
 edge [3]: 1 -- 3
 edge [4]: 1 -- 3
 edge [5]: 1 -- 4
 edge [6]: 2 -- 4
 edge [7]: 3 -- 4

In [18]:
# We shall emulate our adjacency matrix with the weight matrix
weights=[2,2,2,2,1,1,1]  
a=weight_matrix(g,weights)

4×4 Array{Int64,2}:
 0  2  2  1
 2  0  0  1
 2  0  0  1
 1  1  1  0

In [19]:
no_of_walks=(a^3)[1,2]

22

## Pkg.checkout()

The contents of a registered package obtained by the command `Pkg.add("Package_name")` is fixed at the time of registration. 

The package owner may further develop the package, but those changes are not registered (until the registration of a new version). 

If you want to use the latest available version, the command `Pkg.checkout("Package_name")` downloads the latest master.

## Pkg.clone()

Adds unregistered packages or repositories. Here the full GitHub address needs to be supplied.
As an example, we shall use the package [LinearAlgebra.jl](https://github.com/andreasnoack/LinearAlgebra.jl).

N.B. In Julia, the linear algebra routines are incorporated as wrappers of various 
[LAPACK ](http://www.netlib.org/lapack/). This package contains several routines written directly in Julia.

By inspecting the file `src/LinearAlgebra.jl`, we see that nothing is exported so all methods need to be fully specified. We also see that the SVD related stuff may be in the file 
`src/svd.jl`. There we see that the sub-module `SVDModule` is defined, but with nothing eported, and we must specify the full command `LinearAlgebra.SVDModule.svdvals!()`.

We shall compute the singular values of the bidiagonal unity Jordan form with the standard Julia function `svdvals()` and the function from the package.

In [22]:
# Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl")

In [24]:
using LinearAlgebra

In [25]:
whos(LinearAlgebra) # Not much of an information

                 LinearAlgebra    256 KB     Module
                   numnegevals      0 bytes  LinearAlgebra.#numnegevals


In [26]:
whos(LinearAlgebra.SVDModule) # Also no information

                     SVDModule     18 KB     Module


In [27]:
methods(LinearAlgebra.SVDModule.svdvals!)

# 7 methods for generic function "svdvals!":
svdvals!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(A::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}) at linalg\svd.jl:80
svdvals!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(A::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}, B::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}) at linalg\svd.jl:219
svdvals!{T<:Real,S}(A::Union{Hermitian{Complex{T},S},Hermitian{T,S},Symmetric{T,S}}) at linalg\symmetric.jl:236
svdvals!{T<:Union{Float32,Float64}}(M::Bidiagonal{T}) at linalg\bidiag.jl:160
svdvals!{T<:Real}(B::Bidiagonal{T}) at C:\Users\Ivan\.julia\v0.5\LinearAlgebra\src\svd.jl:107
svdvals!{T<:Real}(B::Bidiagonal{T}, tol; debug) at C:\Users\Ivan\.julia\v0.5\LinearAlgebra\src\svd.jl:107
svdvals!(A::Union{Base.ReshapedArray{T<:Any,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T<:Any,2},SubArray{T<:Any,2,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}) at C:\Users\Ivan\.julia\v0.5\LinearAlgebra\src\svd.jl:288

In [28]:
# We now know how to define bidiagonal matrix
methods(Bidiagonal)

# 6 methods for generic function "(::Type)":
(::Type{Bidiagonal})(dv::AbstractArray{T<:Any,1}, ev::AbstractArray{T<:Any,1}) at linalg\bidiag.jl:33
(::Type{Bidiagonal}){T}(dv::AbstractArray{T,1}, ev::AbstractArray{T,1}, isupper::Bool) at linalg\bidiag.jl:32
(::Type{Bidiagonal})(dv::AbstractArray{T<:Any,1}, ev::AbstractArray{T<:Any,1}, uplo::Char) at linalg\bidiag.jl:53
(::Type{Bidiagonal}){Td,Te}(dv::AbstractArray{Td,1}, ev::AbstractArray{Te,1}, isupper::Bool) at linalg\bidiag.jl:64
(::Type{Bidiagonal})(A::AbstractArray{T<:Any,2}, isupper::Bool) at linalg\bidiag.jl:82
(::Type{T}){T}(arg) at sysimg.jl:53

In [29]:
n=70
c=0.5
J=Bidiagonal(c*ones(n),ones(n-1),true)

70×70 Bidiagonal{Float64}:
 0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5      ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   …   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅       ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    

In [30]:
@time s=svdvals(J);

  0.064540 seconds (28.02 k allocations: 1.230 MB)


Julia uses convention that function names ending in `!` overwrite the input data.
Thus, we first make a copy of `J`.

In [31]:
J1=deepcopy(J);

In [32]:
J0=Bidiagonal([1.0,1,1],[1,1],true)

3×3 Bidiagonal{Float64}:
 1.0  1.0   ⋅ 
  ⋅   1.0  1.0
  ⋅    ⋅   1.0

In [33]:
LinearAlgebra.SVDModule.svdvals!(J0)

3-element Array{Float64,1}:
 1.80194 
 1.24698 
 0.445042

In [34]:
@time s1=LinearAlgebra.SVDModule.svdvals!(J1);

  0.000165 seconds (13 allocations: 9.703 KB)


In [35]:
typeof(s1), s1

(Array{Float64,1},[1.49967,1.49867,1.49701,1.49468,1.4917,1.48805,1.48375,1.47879,1.47318,1.46693  …  0.576594,0.561598,0.547933,0.535733,0.525133,0.516259,0.509224,0.504125,0.501035,6.35275e-22])

In [36]:
s[70], s1[70]

(6.352747104407252e-22,6.352747104407252e-22)

## `Pkg.rm()`

This command removes (deletes) added or cloned packages and all required packages not in use otherwise.

In [37]:
# Pkg.rm("Graphs")

In [38]:
# Pkg.rm("LinearAlgebra")

In [39]:
a=readdir("/Users/Ivan/.julia/v0.5");
println(a)

String[".cache",".trash","Arrowhead","AxisAlgorithms","AxisArrays","BaseTestNext","BinDeps","BufferedStreams","Cairo","Calculus","CatIndices","Cbc","Clp","Clustering","Colors","ColorTypes","ColorVectorSpace","Compat","Compose","ComputationalResources","Conda","Contour","CoordinateTransformations","CustomUnitRanges","DataArrays","DataFrames","DataStructures","Dates","DiffBase","Distances","Distributions","DoubleDouble","DualNumbers","FFTViews","FileIO","FixedPointNumbers","FixedSizeArrays","ForwardDiff","Gadfly","Graphics","Graphs","Gtk","GtkReactive","GZip","Hexagons","Hiccup","IJulia","IJuliaPortrayals","ImageAxes","ImageCore","ImageFiltering","ImageMagick","ImageMetadata","Images","ImageTransformations","IncrementalSVD","IndirectArrays","IniFile","Interact","Interpolations","IntervalSets","Iterators","JSON","Juno","KernelDensity","LaTeXStrings","LibExpat","Libz","LinearAlgebra","LineSearches","Loess","MacroTools","MappedArrays","MathProgBase","MatrixDepot","Measures","Media","METADAT

## Creating packages

You need to use GitHub:

1. Go to [GitHub](https://github.com) and `Sign up` and `Sign in`.
2. [Set up Git](https://help.github.com/articles/set-up-git/#platform-windows) at your computer. 

N.B. Check out [GitHub Guides](https://guides.github.com/).

One way to start developing packages is 

1. [Create new repository](https://help.github.com/articles/create-a-repo/) at GitHub.
2. Clone the created package to your computer with
```
git clone https://github.com/your_user_name/your_repository_name.jl
```
3. Start writing your code as described in [Contents of the Package](#contents).
4. Check what you have changed 
```
git commit
```
5. Add changes to be commited with 
```
git add file1 file2 ...
```
6. Commit the changes (you need to supply the message)
```
git commit
```
7. Push the changes to your GitHub repository
```
git push
```

N.B. There are various other possibilities and shorthands (see the Guides).
For example, steps 4., 5. and 6. can be shortened with
```
git commit -am "your message"
```
Also, if you work on your package from two computers, you may need to synchronize your repository: assume that you pushed the changes that you made on computer A to GitHub, and that you want to continue to work on your repository from computer B. Then, you obviously need to synchronize computer B with the latest version from GitHub. This is done with the following commands issued on computer B:
```
git fetch origin
git reset --hard origin/master
git clean -f -d
```



## Be social

You can fork other people's repositories, and use them and change them as your own. You can make pull requests to incorporate those changes to those repositories.

You can easily make different branches of your repository, and test different options.

GitHub enables you to share your work with others, so even small, undocumented packages can be very useful.