# Eigenvalue Decomposition - Definitions and Facts


## Prerequisites

The reader should be familiar with basic linear algebra concepts. 

 
## Competences 

The reader should be able to understand and check the facts about eigenvalue decomposition.

## Selected references

There are many excellent books on the subject. Here we list a few:

[J. W. Demmel, Applied Numerical Linear Algebra][Dem97]

[G. H. Golub and C. F. Van Loan, Matrix Computations][GV13]

[N. Higham, Accuracy and Stability of Numerical Algorithms][Hig02]

[L. Hogben, ed., Handbook of Linear Algebra][Hog14]

[B. N. Parlett, The Symmetric Eigenvalue Problem][Par80]

[G. W. Stewart, Matrix Algorithms, Vol. II: Eigensystems][Ste01]

[L. N. Trefethen and D. Bau, III, Numerical Linear Algebra][TB97]

[J. H. Wilkinson, The Algebraic Eigenvalue Problem][Wil65]


[Dem97]: #1 "J.W. Demmel, 'Applied Numerical Linear Algebra', SIAM, Philadelphia, 1997."
  
[GV13]: #1 "G. H. Golub and C. F. Van Loan, 'Matrix Computations', 4th ed., The John Hopkins University Press, Baltimore, MD, 2013."
  
[Hig02]: #1 "N. Higham, 'Accuracy and Stability of Numerical Algorithms', SIAM, Philadelphia, 2nd ed., 2002."
    
[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', CRC Press, Boca Raton, 2014."

[Par80]: #1 "B. N. Parlett, 'The Symmetric Eigenvalue Problem', Prentice-Hall, Englewood Cliffs, NJ, 1980, also SIAM, Philadelphia, 1998."

[Ste01]: #1 "G. W. Stewart, 'Matrix Algorithms, Vol. II: Eigensystems', SIAM, Philadelphia, 2001." 

[TB97]: #1 "L. N. Trefethen and D. Bau, III, 'Numerical Linear Algebra', SIAM, Philadelphia, 1997."

[Wil65]: #1 "J. H. Wilkinson, 'The Algebraic Eigenvalue Problem', Clarendon Press, Oxford, U.K.,  1965."
    

## General matrices

For more details and the proofs of the Facts below, see 
[L. M. DeAlba, Determinants and Eigenvalues][Hog14] and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 4.1-4.15, CRC Press, Boca Raton, 2014."

### Definitions

We state the basic definitions:

Let $F=\mathbb{R}$ or $F=\mathbb{C}$ and let $A\in F^{n\times n}$ with elements $a_{ij}\in F$.

An element $\lambda \in F$ is an __eigenvalue__ of $A$ if
$\exists x\in F$, $x\neq 0$ such that

$$
Ax=\lambda x,
$$
and $x$ is an __eigenvector__ of $\lambda$.

__Characteristic polynomial__ of $A$ is $p_A(x)=\det(A-xI)$.

__Algebraic multiplicty__, $\alpha(\lambda)$, is the multiplicity of $\lambda$ as a root of $p_A(x)$.

__Spectrum of $A$__, $\sigma(A)$, is the multiset of all eigenvalues of $A$, with each eigenvalue appearing $\alpha(A)$ times.

__Spectral radius__ of $A$ is 
$$\rho(A)=\max\{|\lambda|, \lambda \in \sigma(A)\}.
$$

__Eigenspace__ of $\lambda$ is 

$$
E_{\lambda}(A)=\ker(A-\lambda I).
$$

__Geometric multiplicity__ of $\lambda$ is 
$$\gamma(\lambda)=\dim(E_{\lambda}(A)).
$$

$\lambda$ is __simple__ if $\alpha(\lambda)=1$.

$\lambda$ is __semisimple__ if $\alpha(\lambda)=\gamma(\lambda)$.

$A$ is __nonderogatory__ if $\gamma(\lambda)=1$ for all $\lambda$.

$A$ is __nondefective__ if every $\lambda$ is semisimple.

$A$ is __diagonalizable__ if there exists nonsingular $B$ matrix and diagonal matrix $D$ such that
$A=BDB^{-1}$.

__Trace__ of $A$ is 
$$\mathop{\mathrm{tr}}(A)=\sum_i a_{ii}.$$

$Q\in\mathbb{C}^{n\times n}$ is __unitary__ if $Q^*Q=QQ^*=I$,
where $Q^*=(\bar Q)^T$.

__Schur decomposition__ of $A$ is $A=QTQ^*$,
where $Q$ is unitary and $T$ is upper triangular.

$A$ and $B$ are __similar__ if $B=QAQ^{-1}$ for some nonsingular matrix $Q$.

$A$ is __normal__ if $AA^*=A^*A$. 

### Facts

There are many facts related to the eigenvalue problem for general matrices. We state some basic ones:

1. $\lambda\in\sigma(A) \Leftrightarrow p_A(\lambda)=0$.

1. __Cayley-Hamilton Theorem.__ $p_A(A)=0$. 

2. A simple eigenvalue is semisimple.

3. $\mathop{\mathrm{tr}}(A)=\sum_{i=1}^n \lambda_i$.

4. $\det(A)=\prod_{i=1}^n \lambda_i$.

5. $A$ is singular $\Leftrightarrow$ $\det(A)=0$ $\Leftrightarrow$ $0\in\sigma(A)$.

7. If $A$ is triangular, $\sigma(A)=\{a_{11},a_{22},\ldots,a_{nn}\}$.

6. For $A\in\mathbb{C}^{n\times n}$, $\lambda\in\sigma(A)$ $\Leftrightarrow$ $\bar\lambda\in\sigma(A^*)$.

8. __Corollary of the Fundamental theorem of algebra.__ For $A\in\mathbb{R}^{n\times n}$, $\lambda\in\sigma(A)$ $\Leftrightarrow$ $\bar\lambda\in\sigma(A)$. 

9. If $(\lambda,x)$ is an eigenpair of a nonsingular $A$, then $(1/\lambda,x)$ is an eigenpair of $A^{-1}$.

10. Eigenvectors corresponding to distinct eigenvalues are linearly independent.

11. $A$ is diagonalizable $\Leftrightarrow$ $A$ is nondefective $\Leftrightarrow$ $A$ has $n$ linearly independent eigenvectors. 

12. Every $A$ has Schur decomposition. Moreover, $T_{ii}=\lambda_i$.

14. If $A$ is normal, matrix $T$ from its Schur decomposition is normal. Consequently:

    * $T$ is diagonal, and has eigenvalues of $A$ on diagonal,
    * matrix $Q$ of the Schur decomposition is the unitary matrix of eigenvectors,
    * all eigenvalues of $A$ are semisimple and $A$ is nondefective.

13. If $A$ and $B$ are similar, $\sigma(A)=\sigma(B)$. Consequently, $\mathop{\mathrm{tr}}(A)=\mathop{\mathrm{tr}}(B)$ and $\det(A)=\det(B)$.

11. Eigenvalues and eigenvectors are continous and differentiable: if $\lambda$ is a simple eigenvalue of $A$ and $A(\varepsilon)=A+\varepsilon E$ for some $E\in F^{n\times n}$, for small $\varepsilon$ there exist differentiable functions $\lambda(\varepsilon)$ and $x(\varepsilon)$ such that

$$
A(\varepsilon) x(\varepsilon) = \lambda(\varepsilon) x(\varepsilon).
$$

15. Classical motivation for the eigenvalue problem is the following: consider the system of linear differential equations with constant coefficients,
$$ \dot y(t)=Ay(t).$$
If the solution is $y=e^{\lambda t} x$ for some constant vector $x$, then

$$\lambda e^{\lambda t} x=Ae^{\lambda t} x \quad \textrm{or} \quad Ax=\lambda x.
$$


### Examples

We shall illustrate above Definitions and Facts on several small examples, using symbolic computation.

In [1]:
using SymPy

┌ Info: Recompiling stale cache file C:\Users\Ivan_Slapnicar\.julia\compiled\v1.0\SymPy\KzewI.ji for SymPy [24249f21-da20-56a4-8eb1-6a02cf4ae2e6]
└ @ Base loading.jl:1190


In [2]:
A=[-3 7 -1; 6 8 -2; 72 -28 19]

3×3 Array{Int64,2}:
 -3    7  -1
  6    8  -2
 72  -28  19

In [3]:
@vars x

(x,)

In [4]:
using LinearAlgebra
eye(n)=Matrix{Int}(I,n,n)
A-x*eye(3)

3×3 Array{Sym,2}:
 -x - 3       7       -1
      6  -x + 8       -2
     72     -28  -x + 19

In [5]:
# Characteristic polynomial p_A(λ)
p(x)=det(A-x*eye(3))
p(x)

26*x + (-x - 3)*(-x + 8)*(-x + 19) - 894

In [6]:
# Characteristic polynomial in nicer form
p(x)=factor(det(A-x*eye(3)))
p(x)

         2        
-(x - 15) *(x + 6)

In [7]:
λ=solve(p(x),x)

2-element Array{Sym,1}:
 -6
 15

The eigenvalues are $\lambda_1=-6$ and $\lambda_2=15$ with algebraic multiplicities
$\alpha(\lambda_1)=1$ and $\alpha(\lambda_2)=2$.

In [8]:
g=nullspace(A-λ[1]*eye(3))

1-element Array{Array{Sym,1},1}:
 [-1/4, 1/4, 1]

In [9]:
h=nullspace(A-λ[2]*eye(3))

1-element Array{Array{Sym,1},1}:
 [-1/4, -1/2, 1]

The geometric multiplicities are $\gamma(\lambda_1)=1$ and $\gamma(\lambda_2)=1$. Thus, $\lambda_2$ is not semisimple, therefore $A$ is defective and not diagonalizable.

In [10]:
# Trace and determinant
tr(A), λ[1]+λ[2]+λ[2]

(24, 24)

In [11]:
det(A), λ[1]*λ[2]*λ[2]

(-1350.0000000000002, -1350)

In [12]:
# Schur decomposition
T,Q=schur(A)
T

3×3 Array{Float64,2}:
 -6.0  25.4662       -72.2009
  0.0  15.0          -12.0208
  0.0   1.48587e-15   15.0   

In [13]:
Q

3×3 Array{Float64,2}:
 -0.235702  -0.0571662  -0.970143   
  0.235702  -0.971825   -5.90663e-16
  0.942809   0.228665   -0.242536   

In [14]:
?schur

search: schur schur! Schur ordschur ordschur! GeneralizedSchur schedule



```
schur(A::StridedMatrix) -> F::Schur
```

Computes the Schur factorization of the matrix `A`. The (quasi) triangular Schur factor can be obtained from the `Schur` object `F` with either `F.Schur` or `F.T` and the orthogonal/unitary Schur vectors can be obtained with `F.vectors` or `F.Z` such that `A = F.vectors * F.Schur * F.vectors'`. The eigenvalues of `A` can be obtained with `F.values`.

Iterating the decomposition produces the components `F.T`, `F.Z`, and `F.values`.

# Examples

```jldoctest
julia> A = [5. 7.; -2. -4.]
2×2 Array{Float64,2}:
  5.0   7.0
 -2.0  -4.0

julia> F = schur(A)
Schur{Float64,Array{Float64,2}}
T factor:
2×2 Array{Float64,2}:
 3.0   9.0
 0.0  -2.0
Z factor:
2×2 Array{Float64,2}:
  0.961524  0.274721
 -0.274721  0.961524
eigenvalues:
2-element Array{Float64,1}:
  3.0
 -2.0

julia> F.vectors * F.Schur * F.vectors'
2×2 Array{Float64,2}:
  5.0   7.0
 -2.0  -4.0

julia> t, z, vals = F; # destructuring via iteration

julia> t == F.T && z == F.Z && vals == F.values
true
```

---

```
schur(A::StridedMatrix, B::StridedMatrix) -> F::GeneralizedSchur
```

Computes the Generalized Schur (or QZ) factorization of the matrices `A` and `B`. The (quasi) triangular Schur factors can be obtained from the `Schur` object `F` with `F.S` and `F.T`, the left unitary/orthogonal Schur vectors can be obtained with `F.left` or `F.Q` and the right unitary/orthogonal Schur vectors can be obtained with `F.right` or `F.Z` such that `A=F.left*F.S*F.right'` and `B=F.left*F.T*F.right'`. The generalized eigenvalues of `A` and `B` can be obtained with `F.α./F.β`.

Iterating the decomposition produces the components `F.S`, `F.T`, `F.Q`, `F.Z`, `F.α`, and `F.β`.


In [15]:
F=schur(A)
fieldnames(typeof(F))

(:T, :Z, :values)

In [16]:
F.Z

3×3 Array{Float64,2}:
 -0.235702  -0.0571662  -0.970143   
  0.235702  -0.971825   -5.90663e-16
  0.942809   0.228665   -0.242536   

In [17]:
println(diag(T))

[-6.0, 15.0, 15.0]


In [18]:
Q'*Q

3×3 Array{Float64,2}:
 1.0          1.11022e-16  2.77556e-17
 1.11022e-16  1.0          1.52656e-16
 2.77556e-17  1.52656e-16  1.0        

In [19]:
Q*Q'

3×3 Array{Float64,2}:
 1.0          1.35877e-16  0.0        
 1.35877e-16  1.0          3.22346e-17
 0.0          3.22346e-17  1.0        

In [20]:
# Similar matrices
M=rand(-5:5,3,3)
B=M*A*inv(M)
eigvals(B), tr(B), det(B)

([-6.0, 15.0, 15.0], 23.999999999999993, -1350.000000000005)

### Example

This matrix is nondefective and diagonalizable.

In [21]:
A=[57 -21 21; -14 22 -7; -140 70 -55]

3×3 Array{Int64,2}:
   57  -21   21
  -14   22   -7
 -140   70  -55

In [22]:
p(x)=factor(det(A-x*eye(3)))
p(x)

         2        
-(x - 15) *(x + 6)

In [23]:
λ=solve(p(x),x)

2-element Array{Sym,1}:
 -6
 15

In [24]:
h=nullspace(A-λ[2]*eye(3))

2-element Array{Array{Sym,1},1}:
 [1/2, 1, 0] 
 [-1/2, 0, 1]

### Example

Let us try some random examples of dimension $n=4$ (the largest $n$ for which we can compute eigevalues symbolically).

In [25]:
A=rand(-4:4,4,4)

4×4 Array{Int64,2}:
  0  -1  -4  -2
  3   3   4  -4
 -3  -3  -3  -3
 -1   3   1   4

In [26]:
p(x)=factor(det(A-x*eye(4)))
p(x)

 4      3      2              
x  - 4*x  + 7*x  + 100*x - 303

In [27]:
λ=solve(p(x),x)

4-element Array{Sym,1}:
  1 + sqrt(-2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2/3 + 2*(158851/216 + 77*sqrt(181941)/36)^(1/3))/2 - sqrt(-212/sqrt(-2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2/3 + 2*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2*(158851/216 + 77*sqrt(181941)/36)^(1/3) - 4/3 + 2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)))/2
  1 + sqrt(-2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2/3 + 2*(158851/216 + 77*sqrt(181941)/36)^(1/3))/2 + sqrt(-212/sqrt(-2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2/3 + 2*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2*(158851/216 + 77*sqrt(181941)/36)^(1/3) - 4/3 + 2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)))/2
 -sqrt(-2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2/3 + 2*(158851/216 + 77*sqrt(181941)/36)^(1/3))/2 + 1 + sqrt(-2*(158851/216 + 77*sqrt(181941)/36)^(1/3) - 4/3 + 2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) + 212/sqrt(-2387/(18*(158851/216 + 77*sqrt(181941)/36)^(1/3)) - 2/3 + 2*(15

In [28]:
length(λ)

4

Since all eigenvalues are distinct, they are all simple and the matrix is diagonalizable. 
With high probability, all eigenvalues of a random matrix are simple.

Do not try to use `nullspace()` here.

In [29]:
A=rand(4,4)
p(x)=factor(det(A-x*eye(4)))
p(x)

                 /                   8        7                      6        
1.38473365461382*\0.722160537275945*x  - 1.0*x  - 0.621207067162894*x  + 0.736
------------------------------------------------------------------------------
                                                             4                
                                                        1.0*x  - 0.25115278391

              5                     4                      3                  
271965268429*x  + 0.20254767220898*x  - 0.136773240824899*x  - 0.0272247973812
------------------------------------------------------------------------------
      3                      2                                                
6885*x  - 0.196577710820786*x  + 0.0218374455983418*x - 0.000576006141084681  

     2                                               \
935*x  + 0.00378514098953576*x - 0.000105729208929072/
------------------------------------------------------
                                           

In this case, symbolic computation does not work well with floating-point numbers - the degree of $p_A(x)$ is 8 instead of 4.

Let us try `Rational` numbers:

In [30]:
A=map(Rational,A)

4×4 Array{Rational{Int64},2}:
  233350601185865//4503599627370496  …   156209333576425//1125899906842624
 1187268839672043//4503599627370496     1760421208468767//4503599627370496
 2905790177081329//4503599627370496      820992529096433//1125899906842624
  316168606053057//4503599627370496     2199420937698647//2251799813685248

In [31]:
p(x)=factor(det(A-x*eye(4)))
p(x)

                                                                4             
25711008708143844408671393477458601640355247900524685364822016*x  - 2914550763
------------------------------------------------------------------------------
                                                                              

                                                      3                       
7874200637445723693625731802664008133468772607459328*x  - 24382536649918716391
------------------------------------------------------------------------------
                                                         257110087081438444086

                                            2                                 
142439779278372651527891701165548927713280*x  + 137988545697549185531994671466
------------------------------------------------------------------------------
71393477458601640355247900524685364822016                                     

                                                 

In [32]:
λ=solve(p(x),x)

4-element Array{Sym,1}:
 5105194386865043/18014398509481984 - sqrt(232064468648950028867905561966787/243388915243820045087367015432192 + 2375527011817949248386086364554195244940426351668369303165541897/(7404770507945427189697361321508077272422311395351109385068740608*(112858860473204976992582890094995210873995944688279254662495661944887950679485658931276444530539/1802239061558267882020799564580559596696031940738425774642816356599997893627415464081874260852736 + sqrt(515649687384845743401317781852869158853719481370974400223905515965282632236151928484319371506060562273849645097893912329756064989347323430208043652095880541650249950283430315260413984962)*I/50062196154396330056133321238348877686000887242734049295633787683333274822983762891163173912576)^(1/3)) + 2*(112858860473204976992582890094995210873995944688279254662495661944887950679485658931276444530539/1802239061558267882020799564580559596696031940738425774642816356599997893627415464081874260852736 + sqrt(5156496873848457434013177818

In [33]:
length(λ)

4

### Example - Circulant matrix

For more details, see 
[A. B&ouml;ttcher and I. Spitkovsky, Special Types of Matrices][BoSp14] and the references therein.

[BoSp14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 22.1-22.20, CRC Press, Boca Raton, 2014."

Given $a_0,a_1,\ldots,a_{n-1}\in \mathbb{C}$, the __circulant matrix__ is

$$
C(a_0,a_1,\ldots,a_{n-1})=\begin{bmatrix}
a_0 & a_{n-1} & a_{n-2} & \cdots & a_{1} \\
a_1 & a_0 & a_{n-1} & \cdots & a_{2} \\
a_2 & a_1 & a_{0} & \cdots & a_{3} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
a_{n-1} & a_{n-2} & a_{n-3} & \cdots & a_{0}
\end{bmatrix}.
$$

Let $a(z)=a_0+a_1z+a_2z^2+\cdots +a_{n-1}z^{n-1}$ be the associated complex polynomial.

Let $\omega_n=\exp\big(\displaystyle\frac{2\pi i}{n}\big)$. The __Fourier matrix__ of order $n$ is

$$
F_n=\frac{1}{\sqrt{n}} \bigg[ \omega_n^{(j-1)(k-1)}\bigg]_{j,k=1}^n=
\frac{1}{\sqrt{n}} \begin{bmatrix} 
1 & 1 & \cdots & 1 \\
1& \omega_n & \omega_n^2 & \cdots \omega_n^{n-1} \\
1& \omega_n^2 & \omega_n^4 & \cdots \omega_n^{2(n-1)} \\
\vdots & \vdots & \ddots & \vdots \\
1& \omega_n^{n-1} & \omega_n^{2(n-1)} & \cdots \omega_n^{(n-1)(n-1)}
\end{bmatrix}.
$$

Fourier matrix is unitary. 
Fourier matrix is a Vandermonde matrix, $F_n=\displaystyle\frac{1}{\sqrt{n}} V(1,\omega_n,\omega_n^2,\ldots, \omega_n^{n-1})$.

Circulant matrix is normal and, thus, unitarily diagonalizable, with the eigenvalue decomposition

$$
C(a_0,a_1,\ldots,a_{n-1})=F_n^*\mathop{\mathrm{diag}}[(a(1),a(\omega_n),a(\omega_n^2),\ldots, 
a(\omega_n^{n-1})]F_n.
$$

We shall use the package [SpecialMatrices.jl](https://github.com/jiahao/SpecialMatrices.jl).

In [34]:
# using Pkg; Pkg.add(PackageSpec(name="SpecialMatrices",rev="master"))

In [35]:
using SpecialMatrices
using Polynomials

In [36]:
varinfo(SpecialMatrices)

| name            |       size | summary       |
|:--------------- | ----------:|:------------- |
| Cauchy          |   40 bytes | UnionAll      |
| Circulant       |   40 bytes | UnionAll      |
| Companion       |   40 bytes | UnionAll      |
| Frobenius       |   40 bytes | UnionAll      |
| Hankel          |   40 bytes | UnionAll      |
| Hilbert         |   40 bytes | UnionAll      |
| Kahan           |   80 bytes | UnionAll      |
| Riemann         |   40 bytes | UnionAll      |
| SpecialMatrices | 16.605 KiB | Module        |
| Strang          |   40 bytes | UnionAll      |
| Toeplitz        |   40 bytes | UnionAll      |
| Vandermonde     |   40 bytes | UnionAll      |
| embed           |    0 bytes | typeof(embed) |


In [37]:
import Random
Random.seed!(123)
n=6
a=rand(-9:9,n)

6-element Array{Int64,1}:
 -5
  5
  9
  8
  0
 -1

In [38]:
C=Circulant(a)

6×6 Circulant{Int64}:
 -5  -1   0   8   9   5
  5  -5  -1   0   8   9
  9   5  -5  -1   0   8
  8   9   5  -5  -1   0
  0   8   9   5  -5  -1
 -1   0   8   9   5  -5

In [39]:
# Check for normality
C*C'-C'*C

6×6 Array{Int64,2}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [40]:
Cm=Matrix(C)
Cm*Cm'-Cm'*Cm

6×6 Array{Int64,2}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [41]:
p1=Polynomials.Poly(a)

Poly(-5 + 5*x + 9*x^2 + 8*x^3 - x^5)

In [42]:
ω=exp(2*π*im/n)

0.5000000000000001 + 0.8660254037844386im

In [43]:
v=map(Complex,[ω^k for k=0:n-1])
F=Vandermonde(v)

6×6 Vandermonde{Complex{Float64}}:
 1.0+0.0im   1.0+0.0im           1.0+0.0im          …   1.0+0.0im        
 1.0+0.0im   0.5+0.866025im     -0.5+0.866025im         0.5-0.866025im   
 1.0+0.0im  -0.5+0.866025im     -0.5-0.866025im        -0.5-0.866025im   
 1.0+0.0im  -1.0+3.88578e-16im   1.0-7.77156e-16im     -1.0+1.94289e-15im
 1.0+0.0im  -0.5-0.866025im     -0.5+0.866025im        -0.5+0.866025im   
 1.0+0.0im   0.5-0.866025im     -0.5-0.866025im     …   0.5+0.866025im   

In [44]:
Fn=Matrix(F)/sqrt(n)
Λ=Fn*Matrix(C)*Fn'

6×6 Array{Complex{Float64},2}:
         16.0+0.0im          …  9.02235e-15-7.69132e-15im
 -6.66448e-16+1.02054e-15im     4.44089e-15+8.88178e-15im
 -1.72202e-15+1.96487e-15im     1.06408e-15-7.24764e-16im
 -1.83133e-16+3.10862e-15im     3.07594e-15-1.87501e-15im
  1.90509e-15+4.97047e-15im     1.70985e-15-1.34822e-14im
  9.13829e-15+7.69826e-15im  …        -15.5-12.9904im    

In [45]:
[diag(Λ) p1(v) eigvals(Matrix(C))]

6×3 Array{Complex{Float64},2}:
  16.0+0.0im       16.0+0.0im           16.0+0.0im    
 -15.5+12.9904im  -15.5+12.9904im      -15.5+12.9904im
  -3.5-2.59808im   -3.5-2.59808im      -15.5-12.9904im
  -8.0+0.0im       -8.0+2.33147e-15im   -3.5+2.59808im
  -3.5+2.59808im   -3.5+2.59808im       -3.5-2.59808im
 -15.5-12.9904im  -15.5-12.9904im       -8.0+0.0im    


## Hermitian and real symmetric matrices

For more details and the proofs of the Facts below, see 
[W. Barrett, Hermitian and Positive Definite Matrices][Bar14] and the references therein.

[Bar14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 9.1-9.13, CRC Press, Boca Raton, 2014."

### Definitions

Matrix $A\in \mathbb{C}^{n\times n}$ is __Hermitian__ or __self-adjoint__ if $A^*=A$, 
or element-wise, $\bar a_{ij}=a_{ji}$. We say $A\in\mathcal{H}_n$.

Matrix $A\in \mathbb{R}^{n\times n}$ is __symmetric__ if $A^T=A$, or element-wise, $a_{ij}=a_{ji}$.
We say $A\in\mathcal{S}_n$.

__Rayleigh qoutient__ of $A\in\mathcal{H}_n$ and nonzero vector $x\in\mathbb{C}^n$ is

$$
R_A(x)=\frac{x^*Ax}{x^*x}.
$$

Matrices $A,B \in\mathcal{H}_n$ are __congruent__ if there exists nonsingular matrix $C$ such that 
$B=C^*AC$.

__Inertia__ of $A\in\mathcal{H}_n$ is the ordered triple 
$$\mathop{\mathrm{in}}(A)=(\pi(A),\nu(A),\zeta(A)),$$

where $\pi(A)$ is the number of positive eigenvalues of $A$,  $\nu(A)$ is the number of negative eigenvalues of $A$,
and $\zeta(A)$ is the number of zero eigenvalues of $A$.

__Gram matrix__ of a set of vectors $x_1,x_2,\ldots,x_k\in\mathbb{C}^{n}$ is the matrix $G$ with entries $G_{ij}=x_i^*x_j$. 

### Facts

Assume $A$ is Hermitian and $x\in\mathbb{C}^n$ is nonzero. Then

1. Real symmetric matrix is Hermitian, and real Hermitian matrix is symmetric.
2. Hermitian and real symmetric matrices are normal.
2. $A+A^*$, $A^*A$, and $AA^*$ are Hermitian.
3. If $A$ is nonsingular, $A^{-1}$ is Hermitian.
4. Main diagonal entries of $A$ are real.
5. Matrix $T$ from the Schur decomposition of $A$ is Hermitian. Consequently:
    * $T$ is diagonal and real, and has eigenvalues of $A$ on diagonal,
    * matrix $Q$ of the Schur decomposition is the unitary matrix of eigenvectors,
    * all eigenvalues of $A$ are semisimple and $A$ is nondefective,
    * eigenvectors corresponding to distinct eigenvalues are orthogonal.
6. __Spectral Theorem.__ To summarize:
    * if $A\in\mathcal{H}_n$, there is a unitary matrix $U$ and real diagonal matrix $\Lambda$ such that 
    $A=U\Lambda U^*$. The diagonal entries of $\Lambda$ are the eigenvalues of $A$, and the 
    columns of $U$ are the corresponding eigenvectors.
    * if $A\in\mathcal{S}_n$, the same holds with orthogonal matrix $U$, $A=U\Lambda U^T$.
    * if $A\in\mathcal{H}_n$ with eigenpairs $(\lambda_i,u_i)$, then
    $$ A=\lambda_1u_1u_1^*+\lambda_2 u_2u_2^* +\cdots +\lambda_n u_nu_n^*.$$
    * similarly, if  $A\in\mathcal{S}_n$, then
    $$ A=\lambda_1u_1u_1^T+\lambda_2 u_2u_2^T +\cdots +\lambda_n u_nu_n^T.$$

7. Since all eigenvalues of $A$ are real, they can be ordered:
$$\lambda_1\geq \lambda_2\geq \cdots \geq \lambda_n.$$
8. __Rayleigh-Ritz Theorem.__ It holds:
\begin{align*}
\lambda_n &\leq \frac{x^*Ax}{x^*x} \leq \lambda_1, \\
\lambda_1&=\max_x\frac{x^*Ax}{x^*x} =\max_{\|x\|_2=1} x^*Ax, \\
\lambda_n&=\min_x\frac{x^*Ax}{x^*x} =\min_{\|x\|_2=1} x^*Ax.
\end{align*}

8. __Courant-Fischer Theorem.__ It holds:
\begin{align*}
\lambda_k& =\max_{\dim(W)=k}\min_{x\in W} \frac{x^*Ax}{x^*x}\\
& =\min_{\dim(W)=n-k+1}\max_{x\in W} \frac{x^*Ax}{x^*x}.
\end{align*} 

10. __Cauchy Interlace Theorem.__ Let $B$ be the principal submatrix of $A$ obtained by deleting the $i$-th row and the $i$-th column of $A$. Let $\mu_1\geq \mu_2\geq \cdots \geq \mu_{n-1}$ be the eignvalues of $B$. Then
$$
\lambda_1\geq \mu_1\geq \lambda_2\geq \mu_2\geq \lambda_3\geq\cdots\geq \lambda_{n-1}\geq\mu_{n-1}\geq\lambda_n.
$$

9. __Weyl Inequalities.__ For $A,B\in\mathcal{H}_n$, it holds:
\begin{align*}
   \lambda_{j+k-1}(A+B)& \leq \lambda_j(A)+\lambda_k(B), & \textrm{for} \ j+k\leq n+1,\\
   \lambda_{j+k-n}(A+B)& \geq \lambda_j(A)+\lambda_k(B), & \textrm{for} \ j+k\geq n+1,
\end{align*}
and, in particular, 
$$
\lambda_j(A)+\lambda_n(B) \leq \lambda_j(A+B) \leq \lambda_j(A)+\lambda_1(B),\quad \textrm{for} \ j=1,2,\ldots,n.
$$

11. $\pi(A)+\mu(A)+\zeta(A)=n$.

12. $\mathop{\mathrm{rank}}(A)=\pi(A)+\mu(A)$.

13. If $A$ is nonsingular, $\mathop{\mathrm{in}}(A)=\mathop{\mathrm{in}}(A^{-1})$.

13. If $A,B \in\mathcal{H}_n$ are similar,  $\mathop{\mathrm{in}}(A)=\mathop{\mathrm{in}}(B)$.

14. __Sylvester's Law of Inertia.__ $A,B \in\mathcal{H}_n$ are congruent if and only if $\mathop{\mathrm{in}}(A)=\mathop{\mathrm{in}}(B)$.

15. __Subadditivity of Inertia.__ For $A,B \in\mathcal{H}_n$, 
$$
\pi(A+B)\leq \pi(A)+\pi(B), \qquad \nu(A+B)\leq \nu(A)+\nu(B).
$$

16. Gram matrix is Hermitian.

### Example - Hermitian matrix

In [46]:
# Generating Hermitian matrix
n=4
A=rand(n,n)+im*rand(n,n)
A=A+A'

4×4 Array{Complex{Float64},2}:
 0.104266+0.0im       0.741656+0.593435im  …  0.419647-0.582424im
 0.741656-0.593435im   1.73082+0.0im          0.991558+0.420682im
 0.572718+0.127964im  0.893311+0.584561im     0.874296+0.411046im
 0.419647+0.582424im  0.991558-0.420682im     0.562132+0.0im     

In [47]:
ishermitian(A)

true

In [48]:
# Diagonal entries
diag(A)

4-element Array{Complex{Float64},1}:
 0.10426632633731314 + 0.0im
   1.730824286816691 + 0.0im
  0.8931361306653263 + 0.0im
   0.562131790202915 + 0.0im

In [49]:
# Schur decomposition
F=schur(A)

Schur{Complex{Float64},Array{Complex{Float64},2}}
T factor:
4×4 Array{Complex{Float64},2}:
 3.49821+2.65864e-16im  …   1.51257e-16+8.1665e-16im 
     0.0+0.0im             -1.58237e-16-4.14455e-16im
     0.0+0.0im              8.37804e-17+9.11091e-17im
     0.0+0.0im               -0.0169431-1.02733e-16im
Z factor:
4×4 Array{Complex{Float64},2}:
 -0.292123-8.24329e-17im  -0.662469+4.49568e-16im  …   0.401409+1.32527e-10im
 -0.671128+0.164382im      0.244787-0.296038im         0.243399+0.251821im   
 -0.487725-0.131844im     0.0726236-0.186454im        -0.296453-0.745111im   
  -0.40854+0.122746im      0.106734+0.601784im        0.0858803+0.256443im   
eigenvalues:
4-element Array{Complex{Float64},1}:
     3.498213636571105 + 2.6586417963921775e-16im
   -1.0584199433748387 + 6.647259711930159e-17im 
    0.8675079512270665 - 1.1028327328217264e-17im
 -0.016943110401087327 - 1.0273329145722432e-16im

In [50]:
λ,U=eigen(A)

Eigen{Complex{Float64},Float64,Array{Complex{Float64},2},Array{Float64,1}}
eigenvalues:
4-element Array{Float64,1}:
 -1.0584199433748378  
 -0.016943110401087313
  0.8675079512270654  
  3.4982136365710983  
eigenvectors:
4×4 Array{Complex{Float64},2}:
 -0.115691+0.652289im   -0.12747+0.380632im   …  -0.279768-0.0840564im
  -0.24874-0.292724im   -0.31608+0.150833im      -0.690044-0.0356828im
 -0.170906-0.104069im   0.800684-0.0444935im      -0.42916-0.266608im 
  0.611176+0.0im       -0.270441-0.0im           -0.426582-0.0im      

In [51]:
λ

4-element Array{Float64,1}:
 -1.0584199433748378  
 -0.016943110401087313
  0.8675079512270654  
  3.4982136365710983  

In [52]:
# Spectral theorem
norm(A-U*diagm(0=>λ)*U')

7.072676736890567e-15

In [53]:
# Spectral theorem
A-sum([λ[i]*U[:,i]*U[:,i]' for i=1:n])

4×4 Array{Complex{Float64},2}:
 6.66134e-16+1.38778e-17im  …  1.66533e-16+0.0im        
 1.44329e-15-1.88738e-15im     3.33067e-16+0.0im        
 1.44329e-15-8.32667e-16im     5.55112e-16+1.66533e-16im
 1.66533e-16+0.0im             6.66134e-16+0.0im        

In [54]:
# Cauchy Interlace Theorem (repeat several times)
@show i=rand(1:n)
μ=eigvals(A[[1:i-1;i+1:n],[1:i-1;i+1:n]])

i = rand(1:n) = 1


3-element Array{Float64,1}:
 -0.4105543568136909 
  0.39486189548088324
  3.2017846690177403 

In [55]:
# Inertia
inertia(A)=[sum(eigvals(A).>0), sum(eigvals(A).<0), sum(eigvals(A).==0)]

inertia (generic function with 1 method)

In [56]:
inertia(A)

3-element Array{Int64,1}:
 2
 2
 0

In [57]:
# Similar matrices
C=rand(n,n)+im*rand(n,n)
B=C*A*inv(C)
eigvals(B)

4-element Array{Complex{Float64},1}:
    3.4982136365711014 + 2.436527542226674e-15im 
   -1.0584199433748376 - 1.1399975071583755e-16im
    0.8675079512270666 + 1.1823672958482756e-16im
 -0.016943110401086207 - 8.397948507032903e-16im 

This did not work numerically due to rounding errors!

In [58]:
# Congruent matrices - this does not work either, without some preparation
B=C'*A*C
inertia(A)==inertia(B)

MethodError: MethodError: no method matching isless(::Int64, ::Complex{Float64})
Closest candidates are:
  isless(!Matched::Missing, ::Any) at missing.jl:66
  isless(!Matched::PyCall.PyObject, ::Any) at C:\Users\Ivan_Slapnicar\.julia\packages\PyCall\a5Jd3\src\pyoperators.jl:75
  isless(!Matched::Sym, ::Number) at C:\Users\Ivan_Slapnicar\.julia\packages\SymPy\4aR3F\src\logical.jl:106
  ...

In [59]:
# We need to symmetrize B
inertia((B+B')/2)

3-element Array{Int64,1}:
 2
 2
 0

In [60]:
# Weyl's Inequalities
B=rand(n,n)+im*rand(n,n)
B=(B+B')/10
@show λ
μ=eigvals(B)
γ=eigvals(A+B)
μ,γ

λ = [-1.05842, -0.0169431, 0.867508, 3.49821]


([-0.0652063, 0.0156768, 0.115116, 0.575003], [-1.05916, 0.0820787, 0.905589, 4.00244])

In [61]:
# Theorem uses different order!
j=rand(1:n)
k=rand(1:n)
@show j,k
if j+k<=n+1
    @show sort(γ,rev=true)[j+k-1], sort(λ,rev=true)[j]+sort(μ,rev=true)[k]
end
if j+k>=n+1
    sort(γ,rev=true)[j+k-n], sort(λ,rev=true)[j]+sort(μ,rev=true)[k]
end

(j, k) = (4, 3)


(0.08207868564832364, -1.042743127994086)

In [62]:
sort(λ,rev=true)

4-element Array{Float64,1}:
  3.4982136365710983  
  0.8675079512270654  
 -0.016943110401087313
 -1.0584199433748378  

### Example - Real symmetric matrix

In [63]:
# Generating real symmetric matrix
n=6
A=rand(-9:9,n,n)
A=A+A'

6×6 Array{Int64,2}:
 18   15    3    5   13  -7
 15   16   -6    3  -12  -3
  3   -6   -8  -13   -2   1
  5    3  -13   18    4  -6
 13  -12   -2    4  -16  -4
 -7   -3    1   -6   -4  18

In [64]:
issymmetric(A)

true

In [65]:
T,Q=schur(A)

Schur{Float64,Array{Float64,2}}
T factor:
6×6 Array{Float64,2}:
 -28.2014   0.0       6.10627e-15   1.94192e-15  -1.70781e-15   6.99959e-17
   0.0     39.5995    1.60472e-14   6.1583e-15   -5.54272e-15   8.73587e-16
   0.0      0.0     -13.5242        6.38843e-15   4.8806e-15    9.68267e-16
   0.0      0.0       0.0          10.1159        2.72228e-15  -2.27259e-15
   0.0      0.0       0.0           0.0          21.3437       -1.88684e-15
   0.0      0.0       0.0           0.0           0.0          16.6665     
Z factor:
6×6 Array{Float64,2}:
  0.364464   -0.611051   0.0266124    0.523911    0.342939  -0.317781
 -0.379423   -0.48175   -0.0225312   -0.346643    0.521675   0.480771
 -0.259611    0.15419   -0.86236      0.0495552   0.244746  -0.320633
 -0.0226141  -0.435281  -0.398126     0.209415   -0.667504   0.402614
 -0.808668   -0.105437   0.310785     0.346905   -0.162825  -0.302484
 -0.0367472   0.41252   -0.00522022   0.662346    0.279775   0.558098
eigenvalues:
6-element Array

In [66]:
T

6×6 Array{Float64,2}:
 -28.2014   0.0       6.10627e-15   1.94192e-15  -1.70781e-15   6.99959e-17
   0.0     39.5995    1.60472e-14   6.1583e-15   -5.54272e-15   8.73587e-16
   0.0      0.0     -13.5242        6.38843e-15   4.8806e-15    9.68267e-16
   0.0      0.0       0.0          10.1159        2.72228e-15  -2.27259e-15
   0.0      0.0       0.0           0.0          21.3437       -1.88684e-15
   0.0      0.0       0.0           0.0           0.0          16.6665     

In [67]:
Q

6×6 Array{Float64,2}:
  0.364464   -0.611051   0.0266124    0.523911    0.342939  -0.317781
 -0.379423   -0.48175   -0.0225312   -0.346643    0.521675   0.480771
 -0.259611    0.15419   -0.86236      0.0495552   0.244746  -0.320633
 -0.0226141  -0.435281  -0.398126     0.209415   -0.667504   0.402614
 -0.808668   -0.105437   0.310785     0.346905   -0.162825  -0.302484
 -0.0367472   0.41252   -0.00522022   0.662346    0.279775   0.558098

In [68]:
λ,U=eigen(A)
λ

6-element Array{Float64,1}:
 -28.201372030244006
 -13.52422486998743 
  10.115898708820268
  16.666492586713147
  21.34369447788987 
  39.59951112680819 

In [69]:
U

6×6 Array{Float64,2}:
 -0.364464    0.0266124    0.523911    0.317781   0.342939  -0.611051
  0.379423   -0.0225312   -0.346643   -0.480771   0.521675  -0.48175 
  0.259611   -0.86236      0.0495552   0.320633   0.244746   0.15419 
  0.0226141  -0.398126     0.209415   -0.402614  -0.667504  -0.435281
  0.808668    0.310785     0.346905    0.302484  -0.162825  -0.105437
  0.0367472  -0.00522022   0.662346   -0.558098   0.279775   0.41252 

In [70]:
A-sum([λ[i]*U[:,i]*U[:,i]' for i=1:n])

6×6 Array{Float64,2}:
 -7.10543e-15   1.77636e-15   2.17604e-14  …  -1.06581e-14   1.15463e-14
  5.32907e-15   3.01981e-14   0.0             -2.66454e-14   1.15463e-14
  2.22045e-14   0.0           1.95399e-14      6.21725e-15  -2.44249e-15
 -3.4639e-14   -1.77636e-14  -1.24345e-14      0.0           7.99361e-15
 -1.06581e-14  -2.66454e-14   5.32907e-15      2.4869e-14    6.21725e-15
  1.15463e-14   1.24345e-14  -1.9984e-15   …   5.32907e-15  -1.27898e-13

In [71]:
inertia(A)

3-element Array{Int64,1}:
 4
 2
 0

In [72]:
C=rand(n,n)
inertia(C'*A*C)

3-element Array{Int64,1}:
 4
 2
 0

## Positive definite matrices

These matrices are an important subset of Hermitian or real symmteric matrices.

### Definitions

Matrix $A\in\mathcal{H}_n$ is __positive definite__ (PD) if $x^*Ax>0$ for all nonzero $x\in\mathbb{C}^n$.

Matrix $A\in\mathcal{H}_n$ is __positive semidefinite__ (PSD) if $x^*Ax\geq 0$ for all nonzero $x\in\mathbb{C}^n$.

### Facts

1. $A\in\mathcal{S}_n$ is PD if $x^TAx>0$ for all nonzero $x\in \mathbb{R}^n$, and is PSD if $x^TAx\geq 0$ for all $x\in \mathbb{R}^n$.
 
2. If $A,B\in \mathrm{PSD}_n$, then $A+B\in \mathrm{PSD}_n$. If, in addition, $A\in \mathrm{PD}_n$, then $A+B\in \mathrm{PD}_n$.

3. If $A\in \mathrm{PD}_n$, then $\mathop{\mathrm{tr}}(A)>0$ and $\det(A)>0$. 

3. If $A\in \mathrm{PSD}_n$, then $\mathop{\mathrm{tr}}(A)\geq 0$ and $\det(A)\geq 0$.

4. Any principal submatrix of a PD matrix is PD. Any principal submatrix of a PSD matrix is PSD. Consequently, all minors are positive or nonnegative, respectively.

5. $A\in\mathcal{H}_n$ is PD iff _every leading_ principal minor of $A$ is positive. $A\in\mathcal{H}_n$ is PSD iff
_every_ principal minor is nonnegative.

6. For $A\in \mathrm{PSD}_n$, there exists unique PSD $k$-th __root__, $A^{1/k}=U\Lambda^{1/k} U^*$.

7. __Cholesky Factorization.__ $A\in\mathcal{H}_n$ if PD iff there is an invertible lower triangular matrix $L$ with positive diagonal entries such that $A=LL^*$.

8. Gram matrix is PSD. If the vectors are linearly independent, Gram matrix is PD.

### Example - Positive definite matrix

In [73]:
# Generating positive definite matrix as a Gram matrix
n=5
A=rand(n,n)+im*rand(n,n)
A=A*A'

5×5 Array{Complex{Float64},2}:
 3.56413+0.0im        1.86501+0.050305im  …   2.71578-0.391029im
 1.86501-0.050305im   1.77571+0.0im            2.3368-0.350274im
 0.94101+0.837856im  0.761651+0.253978im     0.963178+0.435299im
 2.41402+0.121129im   2.11266-0.042927im      2.67522-0.347406im
 2.71578+0.391029im    2.3368+0.350274im      3.79542+0.0im     

In [74]:
ishermitian(A)

true

In [75]:
eigvals(A)

5-element Array{Float64,1}:
  0.005674652388640963
  0.14139406400771196 
  0.6589376045261045  
  1.223257302157311   
 10.69366654403846    

In [76]:
# Positivity of principal leading minors
[det(A[1:i,1:i]) for i=1:n]

5-element Array{Complex{Float64},1}:
   3.5641276631844185 + 0.0im                   
   2.8480711421263254 - 1.2365551857408739e-17im
   0.8763183400825799 - 4.332966334869311e-17im 
  0.03859357982121804 + 1.6940658945086007e-17im
 0.006916066934029409 + 1.360673726469308e-17im 

In [77]:
# Square root
λ,U=eigen(A)
Ar=U*diagm(0=>sqrt.(λ))*U'
A-Ar*Ar

5×5 Array{Complex{Float64},2}:
 8.43769e-15-1.80411e-16im  …   3.9968e-15-2.22045e-16im
 5.77316e-15+2.35922e-16im     3.55271e-15-3.33067e-16im
 2.33147e-15+1.33227e-15im     1.55431e-15+7.77156e-16im
 9.32587e-15+1.38778e-16im      3.9968e-15-2.22045e-16im
 4.44089e-15+2.22045e-16im     4.88498e-15+2.77556e-17im

In [78]:
# Cholesky factorization - the upper triangular factor is returned
L=cholesky(A).U

5×5 UpperTriangular{Complex{Float64},Array{Complex{Float64},2}}:
 1.88789+0.0im  0.987882+0.0266461im  …    1.43853-0.207125im  
         ⋅       0.89392+0.0im             1.03055-0.120064im  
         ⋅               ⋅               -0.258242+0.298933im  
         ⋅               ⋅               -0.521014-0.00188521im
         ⋅               ⋅                0.423323+0.0im       

In [79]:
norm(A-L'*L)

9.844429633125817e-16

### Example - Positive semidefinite matrix

In [80]:
# Generating positive semidefinite matrix as a Gram matrix, try it several times
n=6
m=4
A=rand(-9:9,n,m)

6×4 Array{Int64,2}:
  2   6  -5   7
  8   9   0   5
 -4   2   1   1
  8   9   2   8
  0  -6  -3  -4
 -3   5   5  -5

In [81]:
A=A*A'

6×6 Array{Int64,2}:
 114  105    6  116  -49  -36
 105  170   -9  185  -74   -4
   6   -9   22   -4  -19   22
 116  185   -4  213  -92   -9
 -49  -74  -19  -92   61  -25
 -36   -4   22   -9  -25   84

In [82]:
# There are rounding errors!
eigvals(A)

6-element Array{Float64,1}:
   2.6345389913802536e-16
   1.8367476232847447e-14
  14.786150000289037     
  46.11649419293279      
 113.92747915314348      
 489.16987665363473      

In [83]:
@which rank(A)

rank(A::AbstractArray{T,2} where T) in LinearAlgebra at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\LinearAlgebra\src\generic.jl:742

In [84]:
# Cholesky factorization - this can fail
L=cholesky(A).U

PosDefException: PosDefException: matrix is not positive definite; Cholesky factorization failed.

### Example - Covariance and correlation matrices 

[Covariance and correlation matrices](https://en.wikipedia.org/wiki/Covariance_matrix) are PSD.

Correlation matrix is diagonally scaled covariance matrix.

In [85]:
x=rand(10,5)

10×5 Array{Float64,2}:
 0.934108  0.110226  0.767975  0.425161   0.0701617
 0.123071  0.797408  0.462157  0.410939   0.414877 
 0.813816  0.095699  0.779754  0.0883656  0.81192  
 0.91956   0.186565  0.398596  0.135477   0.206553 
 0.768813  0.586859  0.941196  0.693611   0.587476 
 0.413175  0.623613  0.578657  0.557009   0.0520492
 0.214132  0.62035   0.702451  0.832917   0.194796 
 0.672281  0.830895  0.746427  0.305969   0.0209331
 0.373938  0.72423   0.301046  0.827829   0.927317 
 0.317985  0.493046  0.619772  0.332922   0.208939 

In [86]:
using Statistics
A=cov(x)

5×5 Array{Float64,2}:
  0.0905456   -0.0594738    0.0226628   -0.039109    -0.00340075
 -0.0594738    0.0776365   -0.010829     0.0400494   -0.00296964
  0.0226628   -0.010829     0.0388646   -0.00222493  -0.010662  
 -0.039109     0.0400494   -0.00222493   0.0694736    0.0145688 
 -0.00340075  -0.00296964  -0.010662     0.0145688    0.105244  

In [87]:
# Covariance matrix is a Gram matrix
(x.-mean(x,dims=1))'*(x.-mean(x,dims=1))/(size(x,1)-1)-A

5×5 Array{Float64,2}:
  0.0          -6.93889e-18   0.0          -6.93889e-18   0.0        
 -6.93889e-18   0.0          -1.73472e-18   0.0           0.0        
  0.0          -1.73472e-18   0.0           0.0          -1.73472e-18
 -6.93889e-18   0.0           0.0           0.0           1.73472e-18
  4.33681e-19  -2.60209e-18   0.0          -1.73472e-18   0.0        

In [88]:
B=cor(x)

5×5 Array{Float64,2}:
  1.0        -0.709347    0.382035   -0.493098   -0.0348371
 -0.709347    1.0        -0.197142    0.545322   -0.0328527
  0.382035   -0.197142    1.0        -0.0428183  -0.16671  
 -0.493098    0.545322   -0.0428183   1.0         0.170378 
 -0.0348371  -0.0328527  -0.16671     0.170378    1.0      

In [89]:
# Diagonal scaling
D=1 ./sqrt.(diag(A))

5-element Array{Float64,1}:
 3.3232758896959407
 3.5889457948378296
 5.0725115252255755
 3.7939365154992974
 3.0824831716983927

In [90]:
diagm(0=>D)*A*diagm(0=>D)

5×5 Array{Float64,2}:
  1.0        -0.709347    0.382035   -0.493098   -0.0348371
 -0.709347    1.0        -0.197142    0.545322   -0.0328527
  0.382035   -0.197142    1.0        -0.0428183  -0.16671  
 -0.493098    0.545322   -0.0428183   1.0         0.170378 
 -0.0348371  -0.0328527  -0.16671     0.170378    1.0      

In [91]:
eigvals(A)

5-element Array{Float64,1}:
 0.02049657092565053 
 0.026202517075243164
 0.04897131782823541 
 0.10758609291347618 
 0.17850810006798187 

In [92]:
eigvals(B)

5-element Array{Float64,1}:
 0.2627537418523289
 0.4065754978014736
 0.9407261031111157
 1.097585361779282 
 2.2923592954557983

In [93]:
C=cov(x')

10×10 Array{Float64,2}:
  0.148786    -0.0644134   0.0672401   …  -0.0946185    0.0182793 
 -0.0644134    0.0575342  -0.0584461       0.0235793    0.0177283 
  0.0672401   -0.0584461   0.151334       -0.049813    -0.00834204
  0.101353    -0.0570429   0.0750592      -0.0656002   -0.00222834
  0.0476126   -0.0135053   0.0252371      -0.0356027    0.0147977 
  0.0282215    0.0208758  -0.0533692   …  -0.0284147    0.0290413 
 -0.00199864   0.0339957  -0.0787821      -0.00174868   0.0288678 
  0.0588091    0.0216671  -0.0204272      -0.0687209    0.0439453 
 -0.0946185    0.0235793  -0.049813        0.0775468   -0.0281446 
  0.0182793    0.0177283  -0.00834204     -0.0281446    0.0261345 

In [94]:
eigvals(C)

10-element Array{Float64,1}:
 -4.8513141107094057e-17
 -1.0245953063368211e-17
  1.3265683387837633e-18
  9.261102000458243e-18 
  1.4995963932465505e-17
  2.919072084368664e-17 
  0.05615438085359264   
  0.07050847944530729   
  0.292307637245768     
  0.4247025503860673    

In [95]:
inertia(C)

3-element Array{Int64,1}:
 8
 2
 0

In [96]:
rank(C)

4

Explain the function `rank()`.

In [97]:
@which rank(C)

rank(A::AbstractArray{T,2} where T) in LinearAlgebra at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\LinearAlgebra\src\generic.jl:742