# Eigenvalue Decomposition - Perturbation Theory


## Prerequisites

The reader should be familiar with basic linear algebra concepts and facts about eigenvalue decomposition. 

## Competences 

The reader should be able to understand and check the facts about perturbations of eigenvalues and eigenvectors.


## Norms

In order to measure changes, we need to define norms. For more details and the proofs of the Facts below, see 
[R. Byers and B. N. Datta, Vector and Matrix Norms, Error Analysis, Efficiency, and Stability][Hog14] and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 50.1-50.24, CRC Press, Boca Raton, 2014."

### Definitions

__Norm__ on a vector space $X$ is a real-valued function $\| \phantom{x} \| : X\to \mathbb{R}$ with the following properties:

1. __Positive definiteness.__ $\| x\|\geq 0$ and $\|x\|=0$ if and only if $x$ is the zero vector.  
2. __Homogeneity.__ $\| \lambda x\|=|\lambda| \|x\|$  
3. __Triangle inequality.__ $\| x+y\| \leq \|x\|+\|y\|$ 

Commonly encountered vector norms for $x\in\mathbb{C}^n$ are:

* __H&ouml;lder norm__ or $p$-__norm__: for $p\geq 1$, $\|x\|_p=\big(|x_1|^p+|x_2|^p+\cdots |x_n|^p)^{1/p}$,
* __Sum norm__ or $1$-__norm__: $\|x\|_1=|x_1|+|x_2|+\cdots |x_n|$,
* __Euclidean norm__ or $2$-__norm__: $\|x\|_2=\sqrt{|x_1|^2+|x_2|^2+\cdots |x_n|^2}$,
* __Sup-norm__ or $\infty$-__norm__: $\|x\|_\infty = \max\limits_{i=1,\ldots,n} |x_i|$.

Vector norm is __absolute__ if $\||x|\|=\|x\|$.

Vector norm is __monotone__ if $|x|\leq |y|$ implies $\|x\|\leq \|y\|$. 

From every vector norm we can derive a corresponding __induced__ matrix norm (also, __operator norm__ or __natural norm__):

$$\|A\| = \max\limits_{x\neq 0} \frac{\|Ax\|}{\|x\|}=\max\limits_{\|x\|=1} \|Ax\|.$$

For matrix $A\in\mathbb{C}^{m\times n}$ we define:

* __Maximum absolute column sum norm__: $\|A\|_1=\max\limits_{1\leq j \leq n} \sum_{i=1}^m |a_{ij}|$,
* __Spectral norm__: $\|A\|_2=\sqrt{\rho(A^*A)}=\sigma_{\max}(A)$  (largest singular value of $A$),
* __Maximum absolute row sum norm__: $\|A\|_{\infty}=\max\limits_{1\leq i \leq m} \sum_{j=1}^n |a_{ij}|$,
* __Euclidean norm__ or __Frobenius norm__: 
$\|A\|_F =\sqrt{\sum_{i,j} |a_{ij}|^2}=\sqrt{\mathop{\mathrm{tr}}(A^*A)}$.

Matrix norm is __consistent__ if $\|A\cdot B\|\leq \|A\| \cdot \| B\|$, where $A$ and $B$ are compatible for matrix multiplication.

Matrix norm is __absolute__ if $\||A|\|=\|A\|$.

### Examples

In [1]:
import Random
Random.seed!(425)
x=rand(-4:4,5)

5-element Array{Int64,1}:
 -2
 -3
 -2
  4
  2

In [4]:
using LinearAlgebra
norm(x,1), norm(x), norm(x,Inf)

(13.0, 6.082762530298219, 4.0)

In [5]:
A=rand(-4:4,7,5)

7×5 Array{Int64,2}:
  3  -4  2   2  -1
 -2  -3  3   3   0
  4  -1  1  -2  -4
 -1  -4  4   4  -1
  1  -1  4   4   0
 -1  -3  0   4   0
 -2  -1  0  -1  -3

In [6]:
norm(A,1), norm(A), norm(A,2), norm(A,Inf), 
opnorm(A), opnorm(A,1), opnorm(A,Inf)

(74.0, 15.0996688705415, 15.0996688705415, 4.0, 11.904542657069907, 20.0, 14.0)

In [7]:
# Frobenius norm
norm(vec(A)) 

15.0996688705415

### Facts


1. $\|x\|_1$, $\|x\|_2$, $\|x\|_\infty$ and $\|x\|_p$ are absolute and monotone vector norms.
2. A vector norm is absolute iff it is monotone.
3. __Convergence.__ $x_k\to x_*$ iff for any vector norm $\|x_k-x_*\|\to 0$.
3. Any two vector norms are equivalent in the sense that, for all $x$ and some $\alpha,\beta>0$
$$
\alpha \|x\|_\mu \leq \|x\|_\nu \leq \beta \|x\|_\mu.
$$
In particular:
   * $\|x\|_2 \leq \|x\|_1\leq \sqrt{n}\|x\|_2$,
   * $\|x\|_\infty \leq \|x\|_2\leq \sqrt{n}\|x\|_\infty$,
   * $\|x\|_\infty \leq \|x\|_1\leq n\|x\|_\infty$.
2. __Cauchy-Schwartz inequality.__ $|x^*y|\leq \|x\|_2\|y\|_2$.
3. __H&ouml;lder inequality.__ If $p,q\geq 1$ and $\displaystyle\frac{1}{p}+\frac{1}{q}=1$, then 
$$|x^*y|\leq \|x\|_p\|y\|_q.
$$
1. $\|A\|_1$, $\|A\|_2$ and $\|A\|_\infty$ are induced by the corresponding vector norms.
2. $\|A\|_F$ is not an induced norm.
3. $\|A\|_1$, $\|A\|_2$, $\|A\|_\infty$ and $\|A\|_F$ are consistent.
4. $\|A\|_1$, $\|A\|_\infty$ and $\|A\|_F$ are absolute. However, $\||A|\|_2\neq \|A\|_2$.
5. Any two matrix norms are equivalent in the sense that, for all $A$ and some $\alpha,\beta>0$
$$
\alpha \|A\|_\mu \leq \|A\|_\nu \leq \beta \|A\|_\mu.
$$
In particular:
   * $\frac{1}{\sqrt{n}}\|A\|_\infty \leq \|A\|_2\leq \sqrt{m}\|A\|_\infty$,
   * $\|A\|_2 \leq \|A\|_F\leq \sqrt{n}\|A\|_2$,
   * $\frac{1}{\sqrt{m}}\|A\|_1 \leq \|A\|_2\leq \sqrt{n}\|A\|_1$.
6. $\|A\|_2\leq \sqrt{\|A\|_1 \|A\|_\infty}$.
7. $\|AB\|_F\leq \|A\|_F\|B\|_2$ and $\|AB\|_F\leq \|A\|_2\|B\|_F$.
8. If $A=xy^*$, then $\|A\|_2=\|A\|_F=\|x\|_2\|y\|_2$.
9. $\|A^*\|_2=\|A\|_2$ and $\|A^*\|_F=\|A\|_F$.
10. For a unitary matrix $U$ of compatible dimension,
$$\|AU\|_2=\|A\|_2,\quad \|AU\|_F=\|A\|_F,\quad
\|UA\|_2=\|A\|_2,\quad  \|UA\|_F=\|A\|_F.
$$
11. For $A$ square, $\rho(A)\leq\|A\|$.
12. For $A$ square, $A^k\to 0$ iff $>\rho(A)<1$.

In [9]:
A

7×5 Array{Int64,2}:
  3  -4  2   2  -1
 -2  -3  3   3   0
  4  -1  1  -2  -4
 -1  -4  4   4  -1
  1  -1  4   4   0
 -1  -3  0   4   0
 -2  -1  0  -1  -3

In [11]:
# Absolute norms
opnorm(A,1), opnorm(abs.(A),1), opnorm(A,Inf), opnorm(abs.(A),Inf), norm(A),
norm(abs.(A)),  opnorm(A),opnorm(abs.(A))

(20.0, 20.0, 14.0, 14.0, 15.0996688705415, 15.0996688705415, 11.904542657069907, 13.25246593022328)

In [12]:
# Equivalence of norms
m,n=size(A)
opnorm(A,Inf)\sqrt(n),opnorm(A), sqrt(m)*opnorm(A,Inf)

(0.15971914124998499, 11.904542657069907, 37.04051835490427)

In [13]:
opnorm(A), norm(A), sqrt(n)*opnorm(A)

(11.904542657069907, 15.0996688705415, 26.61936662225428)

In [14]:
opnorm(A,1)\sqrt(m),opnorm(A), sqrt(n)*opnorm(A,1)

(0.13228756555322954, 11.904542657069907, 44.721359549995796)

In [15]:
# Fact 12
opnorm(A), sqrt(opnorm(A,1)*opnorm(A,Inf))

(11.904542657069907, 16.73320053068151)

In [16]:
# Fact 13
B=rand(n,rand(1:9))
norm(A*B), norm(A)*opnorm(B), opnorm(A)*norm(B)

(13.547249832942603, 29.846850055231283, 25.91350101495699)

In [17]:
# Fact 14
x=rand(ComplexF64,10)
y=rand(ComplexF64,10)
A=x*y'
opnorm(A), norm(A), norm(x)*norm(y)

(6.1284463644006175, 6.128446364400618, 6.1284463644006175)

In [18]:
# Fact 15
A=rand(-4:4,7,5)+im*rand(-4:4,7,5)
opnorm(A), opnorm(A'), norm(A), norm(A')

(14.998822296257169, 14.998822296257165, 22.869193252058544, 22.869193252058544)

In [19]:
# Unitary invariance - generate random unitary matrix U
U,R=qr(rand(ComplexF64,size(A)));

In [20]:
opnorm(A), opnorm(U*A), norm(A), norm(U*A)

(14.998822296257169, 14.998822296257169, 22.869193252058544, 22.869193252058544)

In [21]:
# Spectral radius
A=rand(ComplexF64,7,7)
maximum(abs,eigvals(A)), opnorm(A,Inf), opnorm(A,1), opnorm(A), norm(A)

(4.983596548634076, 6.432263905318705, 6.010796616399572, 5.106051220920556, 5.740098293662382)

In [28]:
# Fact 18
B=A/(maximum(abs,eigvals(A))+2)
@show maximum(abs,eigvals(B))
norm(B^100)

maximum(abs, eigvals(B)) = 0.7136146130332816


2.276701017269735e-15

## Errors and condition numbers

We want to answer the question:

__How much the value of a function changes with respect to the change of its argument?__

### Definitions

For function $f(x)$ and argument $x$, the __absolute error__ with respect to the __perturbation__ of the argument 
$\delta x$ is 

$$
\| f(x+\delta x)-f(x)\| = \frac{\| f(x+\delta x)-f(x)\|}{\| \delta x \|} \|\delta x\| \equiv \kappa \|\delta x\|.
$$

The  __condition__ or  __condition number__ $\kappa$ tells how much does the perturbation of the argument increase. (Its form resembles derivative.)

Similarly, the __relative error__ with respect to the relative perturbation of the argument is

$$
\frac{\| f(x+\delta x)-f(x)\|}{\| f(x) \|}= \frac{\| f(x+\delta x)-f(x)\|\cdot  \|x\| }{\|\delta x\| \cdot\| f(x)\|}
\cdot \frac{\|\delta x\|}{\|x\|} \equiv \kappa_{rel} \frac{\|\delta x\|}{\|x\|}.
$$

## Peturbation bounds

### Definitions

Let $A\in\mathbb{C}^{n\times n}$.

Pair $(\lambda,x)\in\mathbb{C}\times\mathbb{C}^{n\times n}$ is an __eigenpair__ of $A$ if $x\neq 0$ and $Ax=\lambda x$.

Triplet $(y,\lambda,x)\in\times\mathbb{C}^{n}\times\mathbb{C}\times\mathbb{C}^{n}$ is an __eigentriplet__ of $A$ if $x,y\neq 0$ and $Ax=\lambda x$ and $y^*A=\lambda y^*$.

__Eigenvalue matrix__ is a diagonal matrix $\Lambda=\mathop{\mathrm{diag}}(\lambda_1,\lambda_2,\ldots,\lambda_n)$.

If all eigenvalues are real, they can be increasingly ordered. $\Lambda^\uparrow$ is the eigenvalue matrix of increasingly ordered eigenvalues.

$\tau$ is a __permutation__ of $\{1,2,\ldots,n\}$.

$\tilde A=A+\Delta A$ is a __perturbed matrix__, where $\Delta A$ is __perturbation__. $(\tilde \lambda,\tilde x)$ are the eigenpairs of $\tilde A$.

__Condition number__ of a nonsingular matrix $X$ is $\kappa(X)=\|X\| \|X^{-1}\|$.

Let $X,Y\in\mathbb{C}^{n\times k}$ with $\mathop{\mathrm{rank}}(X)=\mathop{\mathrm{rank}}(Y)=k$. The __canonical angles__ between their column spaces, $\theta_i$, are defined by $\cos \theta_i=\sigma_i$, where $\sigma_i$ are the singular values of the matrix
$$(Y^*Y)^{-1/2}Y^*X(X^*X)^{-1/2}.$$ 
The __canonical angle matrix__ between $X$ and $Y$ is 
$$\Theta(X,Y)=\mathop{\mathrm{diag}}(\theta_1,\theta_2,\ldots,\theta_k).
$$
    

### Facts

Bounds become more strict as matrices have more structure. 
Many bounds have versions in spectral norm and Frobenius norm.
For more details and the proofs of the Facts below, see 
[R.-C. Li, Matrix Perturbation Theory][Hog14], and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 21.1-21.20, CRC Press, Boca Raton, 2014."

1. There exists $\tau$ such that
$$\|\Lambda- \tilde\Lambda_\tau\|_2\leq 4(\|A\|_2+\|\tilde A\|_2)^{1-1/n}\|\Delta A\|_2^{1/n}.$$

2. __First-order perturbation bounds.__ Let $(y,\lambda,x)$ be an eigentriplet of a simple $\lambda$. $\Delta A$ changes $\lambda$ to 
$\tilde\lambda=\lambda+ \delta\lambda$, where
$$
\delta\lambda=\frac{y^*(\Delta A)x}{y^*x}+O(\|\Delta A\|_2^2).
$$

3. Let $\mu$ be a semisimple eigenvalue of $A$ with multiplicitiy $k$, and let $X,Y\in \mathbb{C}^{n\times k}$ be the matrices of the corresponding right and left eigenvectors, that is, $AX=\lambda X$ and $Y^*A=\lambda Y^*$, such that $Y^*X=I_k$. $\Delta A$ changes the $k$ copies of $\mu$ to $\tilde \mu=\mu+\delta\mu_i$, where $\delta\mu_i$ are the eigenvalues of $Y^*(\Delta A) X$ up to $O(\|\Delta A\|_2^2)$.

3. Perturbations and the inverse: if $\|A\|_p<1$, then $I-A$ is nonsingular and _(for proof see GVL p. 74 (98))_
$$
(I-A)^{-1}=\sum\limits_{k=0}^\infty A^k
$$
with
$$
\|(I-A)^{-1}\|_p \leq \frac{1}{1-\|A\|_p},\qquad 
\|(I-A)^{-1}-I\|_p \leq \frac{\|A\|_p}{1-\|A\|_p}.
$$

4. __Geršgorin Circle Theorem.__ If $X^{-1} A X=D+F$, where $D=\mathop{\mathrm{diag}}(d_1,\ldots,d_n)$ 
and $F$ has zero diagonal entries, then _(for proof see GVL p.357 (381))_
$$\sigma(A) \subseteq \bigcup\limits_{i=1}^n D_i,$$
where 
$$D_i=\big\{z\in\mathbb{C} : |z-d_i| \leq \sum\limits_{j=1}^n |f_{ij}| \big\}.
$$
Moreover, by continuity, if a connected component of $D$ consists of $k$ circles, it contains $k$ eigenvalues.

4. __Bauer-Fike Theorem.__ If $A$ is diagonalizable and $A=X\Lambda X^{-1}$ is its eigenvalue decomposition, then _(for proof see GVL p.357 (381))_
$$
\max_i\min_j |\tilde \lambda_i -
\lambda_j|\leq \|X^{-1}(\Delta A)X\|_p\leq \kappa_p(X)\|\Delta A\|_p.
$$

5. If $A$ and $\tilde A$ are diagonalizable, there exists $\tau$ such that
$$\|\Lambda-\tilde\Lambda_\tau\|_F\leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_F.
$$ If $\Lambda$ and  $\tilde\Lambda$ are real, then
$$
\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\|_{2,F} \leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_{2,F}.
$$

6. If $A$ is normal, there exists $\tau$ such that $\|\Lambda-\tilde\Lambda_\tau\|_F\leq\sqrt{n}\|\Delta A\|_F$.

7. __Hoffman-Wielandt Theorem.__ If $A$ and $\tilde A$ are normal, there exists $\tau$ such that $\|\Lambda-\tilde\Lambda_\tau\|_F\leq\|\Delta A\|_F$.

8. If $A$ and $\tilde A$ are Hermitian, for any unitarily invariant norm $\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\| \leq \|\Delta A\|$. In particular,
\begin{align*}
\max_i|\lambda^\uparrow_i-\tilde\lambda^\uparrow_i|&\leq \|\Delta A\|_2,\\ 
\sqrt{\sum_i(\lambda^\uparrow_i-\tilde\lambda^\uparrow_i)^2}&\leq \|\Delta A\|_F.
\end{align*}

9. __Residual bounds.__ Let $A$ be Hermitian. For some $\tilde\lambda\in\mathbb{R}$ and $\tilde x\in\mathbb{C}^n$ with $\|\tilde x\|_2=1$, define __residual__ $r=A\tilde x-\tilde\lambda\tilde x$. Then
$|\tilde\lambda-\lambda|\leq \|r\|_2$ for some $\lambda\in\sigma(A)$.

9. Let, in addition,  $\tilde\lambda=\tilde x^* A\tilde x$, let $\lambda$ be closest to $\tilde\lambda$ and $x$ be its unit eigenvector, and let 
$$\eta=\mathop{\mathrm{gap}}(\tilde\lambda)= \min_{\lambda\neq\mu\in\sigma(A)}|\tilde\lambda-\mu|.$$
If $\eta>0$, then
$$ |\tilde\lambda-\lambda|\leq \frac{\|r\|_2^2}{\eta},\quad \sin\theta(x,\tilde x)\leq \frac{\|r\|_2}{\eta}.
$$

10. Let $A$ be Hermitian, $X\in\mathbb{C}^{n\times k}$ have full column rank, and $M\in\mathcal{H}_k$ having eigenvalues 
$\mu_1\leq\mu_2\leq\cdots\leq\mu_k$. Set $R=AX-XM$. Then
there exist $\lambda_{i_1}\leq\lambda_{i_2}\leq\cdots\leq\lambda_{i_k}\in\sigma(A)$ such that
\begin{align*}    
\max_{1\leq j\leq k} |\mu_j-\lambda_{i_j}|& \leq \frac{\|R\|_2}{\sigma_{\min}(X)},\\
\sqrt{\sum_{j=1}^k (\mu_j-\lambda_{i_j})^2}&\leq \frac{\|R\|_F}{\sigma_{\min}(X)}.
\end{align*}
(The indices $i_j$ need not be the same in the above formulae.)

10. If, additionally, $X^*X=I$ and $M=X^*AX$, and if all but $k$ of $A$'s eigenvalues differ from every one of $M$'s eigenvalues by at least $\eta>0$, then
$$\sqrt{\sum_{j=1}^k (\mu_j-\lambda_{i_j})^2}\leq \frac{\|R\|_F^2}{\eta\sqrt{1-\|R\|_F^2/\eta^2}}.$$

11. Let $A=\begin{bmatrix} M & E^* \\ E & H \end{bmatrix}$ and $\tilde A=\begin{bmatrix} M & 0 \\ 0 & H \end{bmatrix}$ be Hermitian, and set $\eta=\min |\mu-\nu|$ over all $\mu\in\sigma(M)$ and $\nu\in\sigma(H)$. Then
$$ 
\max |\lambda_j^\uparrow -\tilde\lambda_j^\uparrow| \leq \frac{2\|E\|_2^2}{\eta+\sqrt{\eta^2+4\|E\|_2^2}}.
$$

14. Let 
$$
\begin{bmatrix} X_1^*\\ X_2^* \end{bmatrix} A \begin{bmatrix} X_1 & X_2 \end{bmatrix}=
\begin{bmatrix} A_1 &  \\ & A_2 \end{bmatrix}, \quad \begin{bmatrix} X_1 & X_2 \end{bmatrix} \textrm{unitary},
\quad X_1\in\mathbb{C}^{n\times k}.
$$
Let $Q\in\mathbb{C}^{n\times k}$ have orthonormal columns and for a Hermitian $k\times k$ matrix $M$ set
$R=AQ-QM$. Let $\eta=\min|\mu-\nu|$ over all $\mu\in\sigma(M)$ and $\nu\in\sigma(A_2)$. If $\eta > 0$, then
$$
\|\sin\Theta(X_1,Q)\|_F\leq \frac{\|R\|_F}{\eta}.
$$

### Example - Nondiagonalizable matrix

In [29]:
A=[-3 7 -1; 6 8 -2; 72 -28 19]

3×3 Array{Int64,2}:
 -3    7  -1
  6    8  -2
 72  -28  19

In [30]:
# (Right) eigenvectors
λ,X=eigen(A)
λ

3-element Array{Float64,1}:
 -6.000000000000005
 15.000000241477958
 14.999999758522048

In [31]:
X

3×3 Array{Float64,2}:
  0.235702   0.218218  -0.218218
 -0.235702   0.436436  -0.436436
 -0.942809  -0.872872   0.872872

In [32]:
cond(X)

9.091581997455394e7

In [34]:
X[:,2]+X[:,3]

3-element Array{Float64,1}:
 -2.007421329164316e-8 
 -4.0148426638797474e-8
 -2.5092766420264923e-8

In [35]:
# Left eigenvectors
λ1,Y=eigen(Matrix(A'))

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
eigenvalues:
3-element Array{Complex{Float64},1}:
 -5.999999999999998 + 0.0im                  
 14.999999999999993 + 2.0088262607214127e-7im
 14.999999999999993 - 2.0088262607214127e-7im
eigenvectors:
3×3 Array{Complex{Float64},2}:
     0.894427+0.0im      0.970143+0.0im             0.970143-0.0im       
    -0.447214+0.0im  -7.58506e-16-1.62404e-8im  -7.58506e-16+1.62404e-8im
 -6.07504e-17+0.0im      0.242536+4.0601e-9im       0.242536-4.0601e-9im 

In [37]:
cond(Y)

1.1178754628722218e8

In [38]:
# Try k=2,3
k=3
Y[:,k]'*A-λ[k]*Y[:,k]'

1×3 Adjoint{Complex{Float64},Array{Complex{Float64},1}}:
 2.34268e-7+1.94885e-7im  9.60124e-15-3.9217e-15im  5.8567e-8+4.87212e-8im

In [39]:
ΔA=rand(3,3)/20
B=A+ΔA

3×3 Array{Float64,2}:
 -2.97486    7.01215  -0.995576
  6.02949    8.01452  -1.95884 
 72.038    -27.9706   19.0326  

In [40]:
norm(ΔA)

0.0832934252656342

In [41]:
μ,Z=eigen(B)

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
eigenvalues:
3-element Array{Complex{Float64},1}:
  -5.95316554016302 + 0.0im               
 15.012689796092324 + 0.3003547581981762im
 15.012689796092324 - 0.3003547581981762im
eigenvectors:
3×3 Array{Complex{Float64},2}:
 -0.23616+0.0im  -0.215727+0.0162492im  -0.215727-0.0162492im
 0.234201+0.0im  -0.429694+0.0324421im  -0.429694-0.0324421im
 0.943069+0.0im   0.876075+0.0im         0.876075-0.0im      

In [42]:
# Fact 2
δλ=μ[1]-λ[1]

0.046834459836984976 + 0.0im

In [43]:
k=1
Y[:,k]'*ΔA*X[:,k]/(Y[:,k]⋅X[:,k])

0.04674961668023222 + 0.0im

### Example - Jordan form

In [44]:
n=10
c=0.5
J=Bidiagonal(c*ones(n),ones(n-1),'U')

10×10 Bidiagonal{Float64,Array{Float64,1}}:
 0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5

In [45]:
# Accurately defined eigenvalues
λ=eigvals(J)

10-element Array{Float64,1}:
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5

In [46]:
# Only one eigenvector
X=eigvecs(J)

10×10 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [47]:
x=eigvecs(J)[:,1]
y=eigvecs(J')[:,1]

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

In [48]:
y'*Matrix(J)-0.5*y'

1×10 Adjoint{Float64,Array{Float64,1}}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [50]:
# Just one perturbed element in the lower left corner
ΔJ=sqrt(eps())*[zeros(n-1);1]*Matrix(I,1,n)

10×10 Array{Float64,2}:
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.49012e-8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [51]:
B=J+ΔJ
μ=eigvals(B)

10-element Array{Complex{Float64},1}:
 0.3350615111920276 + 0.0im                
 0.3665619595167544 + 0.09694841124280963im
 0.3665619595167544 - 0.09694841124280963im
 0.4490312038888047 + 0.15686582456677023im
 0.4490312038888047 - 0.15686582456677023im
 0.5509687960268455 + 0.15686582462828694im
 0.5509687960268455 - 0.15686582462828694im
 0.6334380405156275 + 0.09694841134170258im
 0.6334380405156275 - 0.09694841134170258im
 0.6649384889119079 + 0.0im                

In [52]:
# Fact 2
maximum(abs,λ-μ)

0.16493848891190788

In [53]:
y'*ΔJ*x/(y⋅x)

Inf

However, since $B$ is diagonalizable, we can apply Bauer-Fike theorem to it: 

In [54]:
μ,Y=eigen(B)

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
eigenvalues:
10-element Array{Complex{Float64},1}:
 0.3350615111920276 + 0.0im                
 0.3665619595167544 + 0.09694841124280963im
 0.3665619595167544 - 0.09694841124280963im
 0.4490312038888047 + 0.15686582456677023im
 0.4490312038888047 - 0.15686582456677023im
 0.5509687960268455 + 0.15686582462828694im
 0.5509687960268455 - 0.15686582462828694im
 0.6334380405156275 + 0.09694841134170258im
 0.6334380405156275 - 0.09694841134170258im
 0.6649384889119079 + 0.0im                
eigenvectors:
10×10 Array{Complex{Float64},2}:
   -0.986304+0.0im     0.986304+0.0im          …     0.986304+0.0im
    0.162679+0.0im     -0.13161+0.0956206im          0.162679+0.0im
  -0.0268321+0.0im   0.00829158-0.0255188im         0.0268321+0.0im
  0.00442565+0.0im    0.0013676+0.00420904im       0.00442565+0.0im
 -0.00072996+0.0im  -0.00059055-0.000429059im      0.00072996+0.0im
 0.000120398+0.0im  0.0001203

In [55]:
cond(Y)

1.1068834616372574e7

In [43]:
opnorm(inv(Y)*ΔJ*Y), cond(Y)*opnorm(ΔJ)

(0.16493848884660864, 0.1649384888466086)

### Example - Normal matrix

In [56]:
using SpecialMatrices

In [57]:
# In juliabox clone the repository SpecialMatrices.jl and use
# include("/mnt/juliabox/SpecialMatrices/src/SpecialMatrices.jl")

In [58]:
n=6
C=SpecialMatrices.Circulant(rand(-5:5,n))

6×6 Circulant{Int64}:
  5  -4  -2   2  -2   3
  3   5  -4  -2   2  -2
 -2   3   5  -4  -2   2
  2  -2   3   5  -4  -2
 -2   2  -2   3   5  -4
 -4  -2   2  -2   3   5

In [59]:
λ=eigvals(Matrix(C))

6-element Array{Complex{Float64},1}:
      9.500000000000004 + 6.06217782649107im 
      9.500000000000004 - 6.06217782649107im 
      4.499999999999998 + 6.062177826491071im
      4.499999999999998 - 6.062177826491071im
 1.7190285397211416e-16 + 0.0im              
     2.0000000000000018 + 0.0im              

In [60]:
ΔC=rand(n,n)*0.0001

6×6 Array{Float64,2}:
 5.96311e-5  4.83127e-5  9.19171e-5  7.9502e-6   7.10992e-5  9.15689e-6
 4.48653e-5  9.53479e-5  5.84141e-5  4.36502e-5  8.75515e-5  4.09035e-5
 7.703e-5    7.64984e-5  2.86144e-5  3.95265e-5  9.20274e-5  8.21549e-5
 1.32236e-5  9.45009e-5  9.71054e-5  9.05317e-5  6.69507e-5  7.95216e-5
 5.48305e-5  8.15656e-5  4.89373e-5  1.10659e-5  7.25446e-5  6.06036e-5
 6.69371e-5  5.85326e-5  4.64776e-5  3.55563e-5  8.1531e-5   1.97101e-5

In [61]:
@show opnorm(ΔC)
μ=eigvals(C+ΔC)

opnorm(ΔC) = 0.0003690971549687793


6-element Array{Complex{Float64},1}:
      9.49999342765262 + 6.062182435172971im
      9.49999342765262 - 6.062182435172971im
     4.499997281390571 + 6.062167293502126im
     4.499997281390571 - 6.062167293502126im
 2.9165807491056557e-5 + 0.0im              
     2.000355795930484 + 0.0im              

### Example - Hermitian matrix

In [63]:
m=10
n=6
A=rand(m,n)
# Some scaling
D=Diagonal((rand(n).-0.5)*exp(20))
A=A*D

10×6 Array{Float64,2}:
     2.3313e5   -3.6501e7   1.03542e8  3.11251e5  -1.61322e8  9.42928e7
     2.30251e5  -2.07743e7  1.3239e8   1.76627e6  -1.6926e8   5.88813e7
 62865.6        -3.93369e7  6.45184e7  1.73695e6  -1.43821e8  5.4822e7 
     3.1513e5   -3.01738e7  2.03246e8  5.91028e5  -1.0279e8   8.95838e7
 23531.7        -3.93693e7  2.06661e8  2.71312e6  -6.3268e7   3.79758e7
 62439.1        -2.54376e7  6.10799e7  3.61271e6  -1.76274e8  7.63728e6
     1.86145e5  -1.23617e8  5.0802e7   1.72768e6  -9.96324e7  6.46712e7
 98497.7        -3.20323e7  7.60662e7  3.33727e6  -5.32469e7  4.28102e7
 25478.7        -1.2638e8   1.26035e8  5.89616e5  -4.43379e7  9.30454e7
     3.41282e5  -9.39765e7  1.99682e8  2.95502e6  -1.7756e8   3.86944e7

In [64]:
using Statistics
A=cor(A)

6×6 Array{Float64,2}:
  1.0          0.00820476   0.39962    -0.247253  -0.492085    0.280969
  0.00820476   1.0          0.0511433   0.208272  -0.314068   -0.279042
  0.39962      0.0511433    1.0        -0.123148   0.0868575   0.148194
 -0.247253     0.208272    -0.123148    1.0       -0.113222   -0.961373
 -0.492085    -0.314068     0.0868575  -0.113222   1.0         0.272202
  0.280969    -0.279042     0.148194   -0.961373   0.272202    1.0     

In [65]:
ΔA=cor(rand(m,n)*D)*1e-5

6×6 Array{Float64,2}:
  1.0e-5      -4.52463e-7   6.67585e-7  -5.41126e-6  -1.78034e-6   1.10849e-6
 -4.52463e-7   1.0e-5      -2.95428e-7  -5.44173e-6   4.49186e-6   5.91348e-6
  6.67585e-7  -2.95428e-7   1.0e-5      -3.13012e-6   2.80409e-6   5.52927e-6
 -5.41126e-6  -5.44173e-6  -3.13012e-6   1.0e-5      -2.02745e-6  -5.63677e-6
 -1.78034e-6   4.49186e-6   2.80409e-6  -2.02745e-6   1.0e-5       7.43164e-6
  1.10849e-6   5.91348e-6   5.52927e-6  -5.63677e-6   7.43164e-6   1.0e-5    

In [66]:
B=A+ΔA

6×6 Array{Float64,2}:
  1.00001      0.00820431   0.399621   -0.247258  -0.492087    0.28097 
  0.00820431   1.00001      0.051143    0.208266  -0.314063   -0.279036
  0.399621     0.051143     1.00001    -0.123151   0.0868603   0.148199
 -0.247258     0.208266    -0.123151    1.00001   -0.113224   -0.961378
 -0.492087    -0.314063     0.0868603  -0.113224   1.00001     0.27221 
  0.28097     -0.279036     0.148199   -0.961378   0.27221     1.00001 

In [67]:
λ,U=eigen(A) 
μ=eigvals(B)
[λ μ]

6×2 Array{Float64,2}:
 0.00948519  0.00948926
 0.251862    0.251868  
 0.815043    0.81506   
 0.986492    0.9865    
 1.661       1.66101   
 2.27612     2.27613   

In [68]:
norm(ΔA)

3.342223193385679e-5

In [54]:
# ?round

In [69]:
# Residual bounds - how close is μ, y to λ[2],X[:,2]
k=3
μ=round(λ[k],sigdigits=2)
y=round.(U[:,k],sigdigits=2)
y=y/norm(y)

6-element Array{Float64,1}:
 -0.321226050423861  
  0.873333324589872  
  0.04115708771055719
 -0.2509578518936414 
  0.17065133928767615
  0.2007662815149131 

In [70]:
μ

0.82

In [71]:
# Fact 9
r=A*y-μ*y

6-element Array{Float64,1}:
  0.0002761074708931832
 -0.005216396128218226 
 -0.0008152622513391272
 -0.001259155514236887 
  0.0011399763361898962
 -0.003998518633898357 

In [72]:
minimum(abs,μ.-λ), norm(r)

(0.004956610934408023, 0.006842868284730471)

In [73]:
# Fact 10 - μ is Rayleigh quotient
μ=y⋅(A*y)
r=A*y-μ*y

6-element Array{Float64,1}:
 -0.0013204289063599162
 -0.0008758128525614417
 -0.0006107060280035811
 -0.0025064495589658675
  0.001988136286605602 
 -0.0030006833981151837

In [74]:
η=min(abs(μ-λ[k-1]),abs(μ-λ[k+1]))

0.17146238785913304

In [75]:
μ-λ[k], norm(r)^2/η

(-1.352263709542001e-5, 0.00012902315732217525)

In [63]:
# Eigenvector bound
# cos(θ)
cosθ=dot(y,U[:,k])
# sin(θ)
sinθ=sqrt(1-cosθ^2)
sinθ,norm(r)/η

(0.0049866315297567914, 0.014087781327881386)

In [76]:
# Residual bounds - Fact 13
U=eigvecs(A)
Q=round.(U[:,1:3],sigdigits=2)
# Orthogonalize
F=qr(Q)
X=Matrix(F.Q)
M=X'*A*X
R=A*X-X*M
μ=eigvals(M)
R

6×3 Array{Float64,2}:
  0.00249703   0.00366504    0.001572   
 -0.00311609   0.000966629   0.000738625
  0.00123378   0.0028502     0.000629885
 -0.00698628  -0.00129032   -0.00025978 
  0.00168813  -0.00201999   -0.00148783 
  0.00712955   0.00117902    0.000112987

In [77]:
λ

6-element Array{Float64,1}:
 0.009485194294310316
 0.2518622136868459  
 0.8150433890655919  
 0.9864922542876295  
 1.6610018114204508  
 2.2761151372451716  

In [78]:
μ

3-element Array{Float64,1}:
 0.009538900336553024
 0.8150504020920549  
 0.2518824636778341  

In [79]:
# The entries of μ are not ordered - which algorithm was called?
issymmetric(M)

false

In [80]:
M=Hermitian(M)
R=A*X-X*M
μ=eigvals(M)

3-element Array{Float64,1}:
 0.00953890033655317
 0.25188246367783385
 0.815050402092055  

In [81]:
η=λ[4]-λ[3]

0.17144886522203762

In [82]:
norm(λ[1:3]-μ), norm(R)^2/η

(5.7823729113355817e-5, 0.0009057451482534426)

In [83]:
A

6×6 Array{Float64,2}:
  1.0          0.00820476   0.39962    -0.247253  -0.492085    0.280969
  0.00820476   1.0          0.0511433   0.208272  -0.314068   -0.279042
  0.39962      0.0511433    1.0        -0.123148   0.0868575   0.148194
 -0.247253     0.208272    -0.123148    1.0       -0.113222   -0.961373
 -0.492085    -0.314068     0.0868575  -0.113222   1.0         0.272202
  0.280969    -0.279042     0.148194   -0.961373   0.272202    1.0     

In [84]:
# Fact 13
M=A[1:3,1:3]
H=A[4:6,4:6]
E=A[4:6,1:3]
# Block-diagonal matrix
B=cat(M,H,dims=(1,2))

6×6 Array{Float64,2}:
 1.0         0.00820476  0.39962     0.0        0.0        0.0     
 0.00820476  1.0         0.0511433   0.0        0.0        0.0     
 0.39962     0.0511433   1.0         0.0        0.0        0.0     
 0.0         0.0         0.0         1.0       -0.113222  -0.961373
 0.0         0.0         0.0        -0.113222   1.0        0.272202
 0.0         0.0         0.0        -0.961373   0.272202   1.0     

In [85]:
η=minimum(abs,eigvals(M)-eigvals(H))
μ=eigvals(B)
[λ μ]

6×2 Array{Float64,2}:
 0.00948519  0.0251331
 0.251862    0.598074 
 0.815043    0.941195 
 0.986492    0.997935 
 1.661       1.40399  
 2.27612     2.03367  

In [86]:
2*norm(E)^2/(η+sqrt(η^2+4*norm(E)^2))

0.7763545112514764

In [87]:
# Eigenspace bounds - Fact 14
B=A+ΔA
μ,V=eigen(B)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
6-element Array{Float64,1}:
 0.009489262611888023
 0.2518681611207958  
 0.8150599944192113  
 0.9865003639609535  
 1.6610102454816043  
 2.276131972405544   
eigenvectors:
6×6 Array{Float64,2}:
 -0.180427    -0.631461   0.319342   -0.0151393   -0.632237    -0.258401
 -0.00320524  -0.206597  -0.874034    0.00848078  -0.34553      0.271861
  0.0639109    0.386354  -0.0412306  -0.835571    -0.317032    -0.215076
  0.63363     -0.300324   0.254923   -0.262048     0.00400248   0.612084
 -0.220691    -0.555964  -0.168763   -0.454329     0.61443     -0.172569
  0.716352    -0.100075  -0.197277    0.162592     0.0532489   -0.639246

In [88]:
# sin(Θ(U[:,1:3],V[:,1:3]))
X=U[:,1:3]
Q=V[:,1:3]
cosθ=svdvals(sqrt(Q'*Q)*Q'*X*sqrt(X'*X))
sinθ=sqrt.(1 .-cosθ.^2)

3-element Array{Float64,1}:
 1.3342157238182946e-6
 2.9171663448887905e-6
 1.4131871930124374e-5

In [89]:
# Bound
M=Q'*A*Q

3×3 Array{Float64,2}:
  0.00948519  -7.27808e-7   1.1051e-6 
 -7.27808e-7   0.251862    -3.62278e-6
  1.1051e-6   -3.62278e-6   0.815043  

In [90]:
R=A*Q-Q*M

6×3 Array{Float64,2}:
  2.4554e-6    7.2924e-7    9.50823e-7
  9.75012e-7  -1.04827e-6  -3.07399e-6
 -1.29157e-6  -1.35812e-7   2.94727e-6
 -1.46206e-6  -2.42141e-6  -4.71583e-6
 -3.43411e-6   3.3633e-7    3.70815e-6
  9.7329e-7    2.43651e-6   5.27644e-6

In [91]:
eigvals(M), λ

([0.00948519, 0.815043, 0.251862], [0.00948519, 0.251862, 0.815043, 0.986492, 1.661, 2.27612])

In [92]:
η=abs(eigvals(M)[3]-λ[4])
norm(sinθ), norm(R)/η

(1.4491369684431937e-5, 1.4908912980674565e-5)