# Eigenvalue Decomposition - Perturbation Theory

---

## Prerequisites

The reader should be familiar with basic linear algebra concepts and facts about eigenvalue decomposition. 

## Competences 

The reader should be able to understand and check the facts about perturbations of eigenvalues and eigenvectors.

---

## Norms

In order to measure changes, we need to define norms. For more details and the proofs of the Facts below, see 
[R. Byers and B. N. Datta, Vector and Matrix Norms, Error Analysis, Efficiency, and Stability][Hog14] and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 50.1-50.24, CRC Press, Boca Raton, 2014."

### Definitions

__Norm__ on a vector space $X$ is a real-valued function $\| \phantom{x} \| : X\to \mathbb{R}$ with the following properties:

1. $\| x\|\geq 0$ and $\|x\|=0$ if and only if $x$ is the zero vector _(Positive definiteness)_
2. $\| \lambda x\|=|\lambda| \|x\|$ _(Homogeneity)_
3. $\| x+y\| \leq \|x\|+\|y\|$ _(Triangle inequality)_

Commonly encountered vector norms for $x\in\mathbb{C}^n$ are:

* __H&ouml;lder norm__ or $p$-__norm__: for $p\geq 1$, $\|x\|_p=\big(|x_1|^p+|x_2|^p+\cdots |x_n|^p)^{1/p}$,
* __Sum norm__ or $1$-__norm__: $\|x\|_1=|x_1|+|x_2|+\cdots |x_n|$,
* __Euclidean norm__ or $2$-__norm__: $\|x\|_2=\sqrt{|x_1|^2+|x_2|^2+\cdots |x_n|^2}$,
* __Sup-norm__ or $\infty$-__norm__: $\|x\|_\infty = \max\limits_{i=1,\ldots,n} |x_i|$.

Vector norm is __absolute__ if $\||x|\|=\|x\|$.

Vector norm is __monotone__ if $|x|\leq |y|$ implies $\|x\|\leq \|y\|$. 

From every vector norm we can derive a corresponding __induced__ matrix norm (also, __operator norm__ or __natural norm__):

$$\|A\| = \max\limits_{x\neq 0} \frac{\|Ax\|}{\|x\|}=\max\limits_{\|x\|=1} \|Ax\|.$$

For matrix $A\in\mathbb{C}^{m\times n}$ we define:

* __Maximum absolute column sum norm__: $\|A\|_1=\max\limits_{1\leq j \leq n} \sum_{i=1}^m |a_{ij}|$,
* __ Spectral norm__: $\|A\|_2=\sqrt{\rho(A^*A)}=\sigma_{\max}(A)$  (largest singular value of $A$),
* __Maximum absolute row sum norm__: $\|A\|_{\infty}=\max\limits_{1\leq i \leq m} \sum_{j=1}^n |a_{ij}|$,
* __Euclidean norm__ or __Frobenius norm__: 
$\|A\|_F =\sqrt{\sum_{i,j} |a_{ij}|^2}=\sqrt{\mathop{\mathrm{tr}}(A^*A)}$.

Matrix norm is __consistent__ if $\|A\cdot B\|\leq \|A\| \cdot \| B\|$, where $A$ and $B$ are compatible for matrix multiplication.

Matrix norm is __absolute__ if $\||A|\|=\|A\|$.

### Examples

In [1]:
x=rand(-4:4,5)

5-element Array{Int64,1}:
 -2
  1
  4
 -1
  3

In [2]:
norm(x,1), norm(x), norm(x,Inf)

(11.0, 5.5677643628300215, 4.0)

In [3]:
A=rand(-4:4,7,5)

7×5 Array{Int64,2}:
 -4  -3  -2  -4  -3
 -2  -4   1   2  -4
  1   0   3  -2  -3
 -3   1   0   4   4
  4  -3   4   1  -4
  3   4   2  -3   1
 -3   1   4  -1  -2

In [4]:
norm(A,1), norm(A), norm(A,2), norm(A,Inf), vecnorm(A)

(21.0, 10.76811404079164, 10.76811404079164, 16.0, 16.97056274847714)

In [5]:
norm(vec(A))

16.97056274847714

### Facts


1. $\|x\|_1$, $\|x\|_2$, $\|x\|_\infty$ and $\|x\|_p$ are absolute and monotone vector norms.
2. A vector norm is absolute iff it is monotone.
3. _Convergence_: $x_k\to x_*$ iff for any vector norm $\|x_k-x_*\|\to 0$.
3. Any two vector norms are equivalent in the sense that, for all $x$ and some $\alpha,\beta>0$
$$
\alpha \|x\|_\mu \leq \|x\|_\nu \leq \beta \|x\|_\mu.
$$
In particular:
   * $\|x\|_2 \leq \|x\|_1\leq \sqrt{n}\|x\|_2$,
   * $\|x\|_\infty \leq \|x\|_2\leq \sqrt{n}\|x\|_\infty$,
   * $\|x\|_\infty \leq \|x\|_1\leq n\|x\|_\infty$.
2. _Cauchy-Schwartz inequality_: $|x^*y|\leq \|x\|_2\|y\|_2$.
3. _H&ouml;lder inequality_: if $p,q\geq 1$ and $\frac{1}{p}+\frac{1}{q}=1$, then $|x^*y|\leq \|x\|_p\|y\|_q$.
1. $\|A\|_1$, $\|A\|_2$ and $\|A\|_\infty$ are induced by the corresponding vector norms.
2. $\|A\|_F$ is not an induced norm.
3. $\|A\|_1$, $\|A\|_2$, $\|A\|_\infty$ and $\|A\|_F$ are consistent.
4. $\|A\|_1$, $\|A\|_\infty$ and $\|A\|_F$ are absolute. However, $\||A|\|_2\neq \|A\|_2$.
5. Any two matrix norms are equivalent in the sense that, for all $A$ and some $\alpha,\beta>0$
$$
\alpha \|A\|_\mu \leq \|A\|_\nu \leq \beta \|A\|_\mu.
$$
In particular:
   * $\frac{1}{\sqrt{n}}\|A\|_\infty \leq \|A\|_2\leq \sqrt{m}\|A\|_\infty$,
   * $\|A\|_2 \leq \|A\|_F\leq \sqrt{n}\|A\|_2$,
   * $\frac{1}{\sqrt{m}}\|A\|_1 \leq \|A\|_2\leq \sqrt{n}\|A\|_1$.
6. $\|A\|_2\leq \sqrt{\|A\|_1 \|A\|_\infty}$.
7. $\|AB\|_F\leq \|A\|_F\|B\|_2$ and $\|AB\|_F\leq \|A\|_2\|B\|_F$.
8. If $A=xy^*$, then $\|A\|_2=\|A\|_F=\|x\|_2\|y\|_2$.
9. $\|A^*\|_2=\|A\|_2$ and $\|A^*\|_F=\|A\|_F$.
10. For a unitary matrix $U$ of compatible dimension,
$$\|AU\|_2=\|A\|_2,\quad \|AU\|_F=\|A\|_F,\quad
\|UA\|_2=\|A\|_2,\quad  \|UA\|_F=\|A\|_F.
$$
11. For $A$ square, $\rho(A)\leq\|A\|$.
12. For $A$ square, $A^k\to 0$ iff $>\rho(A)<1$.

In [6]:
# Absolute norms
norm(A,1), norm(abs.(A),1), norm(A,Inf), norm(abs.(A),Inf), vecnorm(A),
vecnorm(abs.(A)),  norm(A),norm(abs.(A))

(21.0, 21.0, 16.0, 16.0, 16.97056274847714, 16.97056274847714, 10.76811404079164, 15.573528888569491)

In [7]:
# Equivalence of norms
m,n=size(A)
norm(A,Inf)\sqrt(n),norm(A), sqrt(m)*norm(A,Inf)

(0.13975424859373686, 10.76811404079164, 42.33202097703345)

In [8]:
norm(A), vecnorm(A), sqrt(n)*norm(A)

(10.76811404079164, 16.97056274847714, 24.078234984680048)

In [9]:
norm(A,1)\sqrt(m),norm(A), sqrt(n)*norm(A,1)

(0.12598815766974242, 10.76811404079164, 46.95742752749558)

In [10]:
# Fact 12
norm(A), sqrt(norm(A,1)*norm(A,Inf))

(10.76811404079164, 18.33030277982336)

In [11]:
# Fact 13
B=rand(n,rand(1:9))
vecnorm(A*B), vecnorm(A)*norm(B), norm(A)*vecnorm(B)

(34.106205904950826, 58.096848282538794, 41.93543077379869)

In [12]:
# Fact 14
x=rand(10)+im*rand(10)
y=rand(10)+im*rand(10)
A=x*y'
norm(A), vecnorm(A), norm(x)*norm(y)

(6.248004935728231, 6.248004935728233, 6.2480049357282335)

In [13]:
# Fact 15
A=rand(-4:4,7,5)+im*rand(-4:4,7,5)
norm(A), norm(A'), vecnorm(A), vecnorm(A')

(14.443326063220818, 14.443326063220818, 20.83266665599966, 20.83266665599966)

In [14]:
# Unitary invariance - generate random unitary matrix U
U,R=qr(rand(size(A))+im*rand(size(A)),thin=false);

In [15]:
norm(A), norm(U*A), vecnorm(A), vecnorm(U*A)

(14.443326063220818, 14.443326063220814, 20.83266665599966, 20.83266665599966)

In [16]:
# Spectral radius
A=rand(7,7)+im*rand(7,7)
maximum(abs,eigvals(A)), norm(A,Inf), norm(A,1), norm(A), vecnorm(A)

(4.618780106677782, 6.05938750409579, 6.263213682591239, 4.867195651383478, 5.4614277929444786)

In [17]:
# Fact 18
B=A/(maximum(abs,eigvals(A))+2)
@show maximum(abs,eigvals(B))
norm(B^100)

maximum(abs, eigvals(B)) = 0.6978295142359907


2.473828671647889e-16

## Errors and condition numbers

We want to answer the question:

__How much the value of a function changes with respect to the change of its argument?__

### Definitions

For function $f(x)$ and argument $x$, the __absolute error__ with respect to the __perturbation__ of the argument 
$\delta x$ is 

$$
\| f(x+\delta x)-f(x)\| = \frac{\| f(x+\delta x)-f(x)\|}{\| \delta x \|} \|\delta x\| \equiv \kappa \|\delta x\|.
$$

The  __condition__ or  __condition number__ $\kappa$ tells how much does the perturbation of the argument increase. (Its form resembles derivative.)

Similarly, the __relative error__ with respect to the relative perturbation of the argument is

$$
\frac{\| f(x+\delta x)-f(x)\|}{\| f(x) \|}= \frac{\| f(x+\delta x)-f(x)\|\cdot  \|x\| }{\|\delta x\| \cdot\| f(x)\|}
\cdot \frac{\|\delta x\|}{\|x\|} \equiv \kappa_{rel} \frac{\|\delta x\|}{\|x\|}.
$$

## Peturbation bounds

### Definitions

Let $A\in\mathbb{C}^{n\times n}$.

Pair $(\lambda,x)\in\mathbb{C}\times\mathbb{C}^{n\times n}$ is an __eigenpair__ of $A$ if $x\neq 0$ and $Ax=\lambda x$.

Triplet $(y,\lambda,x)\in\times\mathbb{C}^{n}\times\mathbb{C}\times\mathbb{C}^{n}$ is an __eigentriplet__ of $A$ if $x,y\neq 0$ and $Ax=\lambda x$ and $y^*A=\lambda y^*$.

__Eigenvalue matrix__ is a diagonal matrix $\Lambda=\mathop{\mathrm{diag}}(\lambda_1,\lambda_2,\ldots,\lambda_n)$.

If all eigenvalues are real, they can be increasingly ordered. $\Lambda^\uparrow$ is the eigenvalue matrix of increasingly ordered eigenvalues.

$\tau$ is a __permutation__ of $\{1,2,\ldots,n\}$.

$\tilde A=A+\Delta A$ is a __perturbed matrix__, where $\Delta A$ is __perturbation__. $(\tilde \lambda,\tilde x)$ are the eigenpairs of $\tilde A$.

__Condition number__ of a nonsingular matrix $X$ is $\kappa(X)=\|X\| \|X^{-1}\|$.

Let $X,Y\in\mathbb{C}^{n\times k}$ with $\mathop{\mathrm{rank}}(X)=\mathop{\mathrm{rank}}(Y)=k$. The __canonical angles__ between their column spaces, $\theta_i$, are defined by $\cos \theta_i=\sigma_i$, where $\sigma_i$ are the singular values of the matrix
$$(Y^*Y)^{-1/2}Y^*X(X^*X)^{-1/2}.$$ 
The __canonical angle matrix__ between $X$ and $Y$ is 
$$\Theta(X,Y)=\mathop{\mathrm{diag}}(\theta_1,\theta_2,\ldots,\theta_k).
$$
    

### Facts

Bounds become more strict as matrices have more structure. 
Many bounds have versions in spectral norm and Frobenius norm.
For more details and the proofs of the Facts below, see 
[R.-C. Li, Matrix Perturbation Theory][Hog14], and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 21.1-21.20, CRC Press, Boca Raton, 2014."

1. There exists $\tau$ such that
$$\|\Lambda- \tilde\Lambda_\tau\|_2\leq 4(\|A\|_2+\|\tilde A\|_2)^{1-1/n}\|\Delta A\|_2^{1/n}.$$

2. _(First-order perturbation bounds)_ Let $(y,\lambda,x)$ be an eigentriplet of a simple $\lambda$. $\Delta A$ changes $\lambda$ to 
$\tilde\lambda=\lambda+ \delta\lambda$, where
$$
\delta\lambda=\frac{y^*(\Delta A)x}{y^*x}+O(\|\Delta A\|_2^2).
$$

3. Let $\lambda$ be a semisimple eigenvalue of $A$ with multiplicitiy $k$, and let $X,Y\in \mathbb{C}^{n\times k}$ be the matrices of the corresponding right and left eigenvectors, that is, $AX=\lambda X$ and $Y^*A=\lambda Y^*$, such that $Y^*X=I_k$. $\Delta A$ changes the $k$ copies of $\mu$ to $\tilde \mu=\mu+\delta\mu_i$, where $\delta\mu_i$ are the eigenvalues of $Y^*(\Delta A) X$ up to $O(\|\Delta A\|_2^2$.

3. Perturbations of an inverse matrix are as follows: if $\|A\|_p<1$, then $I-A$ is nonsingular and
$$
(I-A)^{-1}=\sum\limits_{k=0}^\infty A^k
$$
with
$$
\|I-A\|_p \leq \frac{1}{1-\|A\|_p},\qquad 
\|(I-A)^{-1}-I\|_p \leq \frac{\|A\|_p}{1-\|A\|_p}.
$$

4. _(Geršgorin Circle Theorem)_ If $X^{-1} A X=D+F$, where $D=\mathop{\mathrm{diag}}(d_1,\ldots,d_n)$ 
and $F$ has zero diagonal entries, then
$$\sigma(A) \subseteq \bigcup\limits_{i=1}^n D_i,$$
where 
$$D_i=\big\{z\in\mathbb{C} : |z-d_i| \leq \sum\limits_{j=1}^n |f_{ij}| \big\}.
$$
Moreover, by continuity, if a connected component of $D$ consists of $k$ circles, it contains $k$ eigenvalues.

4. _(Bauer-Fike Theorem)_ If $A$ is diagonalizable and $A=X\Lambda X^{-1}$ is its eigenvalue decomposition, then
$$
\max_i\min_j |\tilde \lambda_i -
\lambda_j|\leq \|X^{-1}(\Delta A)X\|_p\leq \kappa_p(X)\|\Delta A\|_p.
$$

5. If $A$ and $\tilde A$ are diagonalizable, there exists $\tau$ such that
$$\|\Lambda-\tilde\Lambda_\tau\|_F\leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_F.
$$ If $\Lambda$ and  $\tilde\Lambda$ are real, then
$$
\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\|_{2,F} \leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_{2,F}.
$$

6. If $A$ is normal, there exists $\tau$ such that $\|\Lambda-\tilde\Lambda_\tau\|_F\leq\sqrt{n}\|\Delta A\|_F$.

7. _(Hoffman-Wielandt Theorem)_ If $A$ and $\tilde A$ are normal, there exists $\tau$ such that $\|\Lambda-\tilde\Lambda_\tau\|_F\leq\|\Delta A\|_F$.

8. If $A$ and $\tilde A$ are Hermitian, for any unitarily invariant norm $\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\| \leq \|\Delta A\|$. In particular,
\begin{align*}
\max_i|\lambda^\uparrow_i-\tilde\lambda^\uparrow_i|&\leq \|\Delta A\|_2,\\ 
\sqrt{\sum_i(\lambda^\uparrow_i-\tilde\lambda^\uparrow_i)^2}&\leq \|\Delta A\|_F.
\end{align*}

9. _(Residual bounds)_ Let $A$ be Hermitian. For some $\tilde\lambda\in\mathbb{R}$ and $\tilde x\in\mathbb{C}^n$ with $\|\tilde x\|_2=1$, define __residual__ $r=A\tilde x-\tilde\lambda\tilde x$. Then
$|\tilde\lambda-\lambda|\leq \|r\|_2$ for some $\lambda\in\sigma(A)$.

9. Let, in addition,  $\tilde\lambda=\tilde x^* A\tilde x$, let $\lambda$ be closest to $\tilde\lambda$ and $x$ be its unit eigenvector, and let 
$$\eta=\mathop{\mathrm{gap}}(\tilde\lambda)= \min_{\lambda\neq\mu\in\sigma(A)}|\tilde\lambda-\mu|.$$
If $\eta>0$, then
$$ |\tilde\lambda-\lambda|\leq \frac{\|r\|_2^2}{\eta},\quad \sin\theta(x,\tilde x)\leq \frac{\|r\|_2}{\eta}.
$$

10. Let $A$ be Hermitian, $X\in\mathbb{C}^{n\times k}$ have full column rank, and $M\in\mathcal{H}_k$ having eigenvalues 
$\mu_1\leq\mu_2\leq\cdots\leq\mu_k$. Set $R=AX-XM$. Then
there exist $\lambda_{i_1}\leq\lambda_{i_2}\leq\cdots\leq\lambda_{i_k}\in\sigma(A)$ such that
\begin{align*}    
\max_{1\leq j\leq k} |\mu_j-\lambda_{i_j}|& \leq \frac{\|R\|_2}{\sigma_{\min}(X)},\\
\sqrt{\sum_{j=1}^k (\mu_j-\lambda_{i_j})^2}&\leq \frac{\|R\|_F}{\sigma_{\min}(X)}.
\end{align*}
(The indices $i_j$ need not be the same in the above formulae.)

10. If, additionally, $X^*X=I$ and $M=X^*AX$, and if all but $k$ of $A$'s eigenvalues differ from every one of $M$'s eigenvalues by at least $\eta>0$, then
$$\sqrt{\sum_{j=1}^k (\mu_j-\lambda_{i_j})^2}\leq \frac{\|R\|_F^2}{\eta\sqrt{1-\|R\|_F^2/\eta^2}}.$$

11. Let $A=\begin{bmatrix} M & E^* \\ E & H \end{bmatrix}$ and $\tilde A=\begin{bmatrix} M & 0 \\ 0 & H \end{bmatrix}$ be Hermitian, and set $\eta=\min |\mu-\nu|$ over all $\mu\in\sigma(M)$ and $\nu\in\sigma(H)$. Then
$$ 
\max |\lambda_j^\uparrow -\tilde\lambda_j^\uparrow| \leq \frac{2\|E\|_2^2}{\eta+\sqrt{\eta^2+4\|E\|_2^2}}.
$$

14. Let 
$$
\begin{bmatrix} X_1^*\\ X_2^* \end{bmatrix} A \begin{bmatrix} X_1 & X_2 \end{bmatrix}=
\begin{bmatrix} A_1 &  \\ & A_2 \end{bmatrix}, \quad \begin{bmatrix} X_1 & X_2 \end{bmatrix} \textrm{unitary},
\quad X_1\in\mathbb{C}^{n\times k}.
$$
Let $Q\in\mathbb{C}^{n\times k}$ have orthonormal columns and for a Hermitian $k\times k$ matrix $M$ set
$R=AQ-QM$. Let $\eta=\min|\mu-\nu|$ over all $\mu\in\sigma(M)$ and $\nu\in\sigma(A_2)$. If $\eta > 0$, then
$$
\|\sin\Theta(X_1,Q)\|_F\leq \frac{\|R\|_F}{\eta}.
$$

### Example - Nondiagonalizable matrix

In [18]:
A=[-3 7 -1; 6 8 -2; 72 -28 19]

3×3 Array{Int64,2}:
 -3    7  -1
  6    8  -2
 72  -28  19

In [19]:
# (Right) eigenvectors
λ,X=eig(A)
λ

3-element Array{Float64,1}:
 -6.0
 15.0
 15.0

In [20]:
X

3×3 Array{Float64,2}:
  0.235702   0.218218  -0.218218
 -0.235702   0.436436  -0.436436
 -0.942809  -0.872872   0.872872

In [21]:
cond(X)

9.091581997455394e7

In [22]:
# Left eigenvectors
λ1,Y=eig(A')

(Complex{Float64}[-6.0+0.0im, 15.0+2.00883e-7im, 15.0-2.00883e-7im], Complex{Float64}[0.894427+0.0im 0.970143+0.0im 0.970143-0.0im; -0.447214+0.0im -7.58506e-16-1.62404e-8im -7.58506e-16+1.62404e-8im; -6.07504e-17+0.0im 0.242536+4.0601e-9im 0.242536-4.0601e-9im])

In [23]:
# Try k=2,3
k=3
Y[:,k]'*A-λ[k]*Y[:,k]'

1×3 RowVector{Complex{Float64},Array{Complex{Float64},1}}:
 2.34268e-7+1.94885e-7im  9.60124e-15-3.9217e-15im  5.8567e-8+4.87212e-8im

In [24]:
ΔA=rand(3,3)/20
B=A+ΔA

3×3 Array{Float64,2}:
 -2.96942    7.03051  -0.983663
  6.00088    8.03607  -1.99097 
 72.0156   -27.9579   19.0035  

In [25]:
norm(ΔA)

0.07075027963364372

In [26]:
μ,Z=eig(B)

(Complex{Float64}[-6.01962+0.0im, 15.0449+0.434326im, 15.0449-0.434326im], Complex{Float64}[-0.236561+0.0im -0.214995+0.0233978im -0.214995-0.0233978im; 0.234554+0.0im -0.42985+0.0466703im -0.42985-0.0466703im; 0.94288+0.0im 0.875374+0.0im 0.875374-0.0im])

In [27]:
# Fact 2
δλ=μ[1]-λ[1]

-0.019617391753927294 + 0.0im

In [28]:
k=1
Y[:,k]'*ΔA*X[:,k]/(Y[:,k]⋅X[:,k])

-0.01974457939708444 + 0.0im

### Example - Jordan form

In [29]:
n=10
c=0.5
J=Bidiagonal(c*ones(n),ones(n-1),true)

10×10 Bidiagonal{Float64}:
 0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  1.0
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5

In [30]:
# Accurately defined eigenvalues
λ=eigvals(J)

10-element Array{Float64,1}:
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5

In [31]:
# Only one eigenvector
X=eigvecs(J)

10×10 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [32]:
x=eigvecs(J)[:,1]
y=eigvecs(J')[:,1]

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

In [33]:
y'*full(J)-0.5*y'

1×10 RowVector{Float64,Array{Float64,1}}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [34]:
# Just one perturbed element in the lower left corner
ΔJ=sqrt(eps())*[zeros(n-1);1]*eye(1,n)

10×10 Array{Float64,2}:
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.49012e-8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [35]:
B=J+ΔJ
μ=eigvals(B)

10-element Array{Complex{Float64},1}:
 0.335062+0.0im      
 0.366562+0.0969484im
 0.366562-0.0969484im
 0.449031+0.156866im 
 0.449031-0.156866im 
 0.550969+0.156866im 
 0.550969-0.156866im 
 0.633438+0.0969484im
 0.633438-0.0969484im
 0.664938+0.0im      

In [36]:
# Fact 2
maximum(abs,λ-μ)

0.16493848891190788

In [37]:
y'*ΔJ*x/(y⋅x)

Inf

However, since $B$ is diagonalizable, we can apply Bauer-Fike theorem to it: 

In [38]:
μ,Y=eig(B)

(Complex{Float64}[0.335062+0.0im, 0.366562+0.0969484im, 0.366562-0.0969484im, 0.449031+0.156866im, 0.449031-0.156866im, 0.550969+0.156866im, 0.550969-0.156866im, 0.633438+0.0969484im, 0.633438-0.0969484im, 0.664938+0.0im], Complex{Float64}[-0.986304+0.0im 0.986304+0.0im … 0.986304-0.0im 0.986304+0.0im; 0.162679+0.0im -0.13161+0.0956206im … 0.13161-0.0956206im 0.162679+0.0im; … ; -5.4024e-7+0.0im 1.66943e-7+5.13799e-7im … 1.66943e-7+5.13799e-7im 5.4024e-7+0.0im; 8.91064e-8+0.0im -7.20886e-8-5.23754e-8im … 7.20886e-8+5.23754e-8im 8.91064e-8+0.0im])

In [39]:
cond(Y)

1.1068834616372582e7

In [40]:
norm(inv(Y)*ΔJ*Y), cond(Y)*norm(ΔJ)

(0.16493848884660858, 0.16493848884660872)

### Example - Normal matrix

In [41]:
using SpecialMatrices

In [42]:
n=6
C=Circulant(rand(-5:5,n))

6×6 SpecialMatrices.Circulant{Int64}:
 -1  -5   5   2  -1  -4
 -4  -1  -5   5   2  -1
 -1  -4  -1  -5   5   2
  2  -1  -4  -1  -5   5
  5   2  -1  -4  -1  -5
 -5   5   2  -1  -4  -1

In [43]:
λ=eigvals(full(C))

6-element Array{Complex{Float64},1}:
 10.0+0.0im    
  3.5+6.06218im
  3.5-6.06218im
 -9.5+4.33013im
 -9.5-4.33013im
 -4.0+0.0im    

In [44]:
ΔC=rand(n,n)*0.0001

6×6 Array{Float64,2}:
 1.11684e-5  6.99639e-5  9.69326e-6  2.8644e-5   9.55351e-5  1.21652e-5
 7.12929e-5  6.5681e-5   3.48421e-5  6.48608e-5  6.90718e-5  4.48986e-5
 8.55286e-5  6.90486e-5  2.09346e-5  3.53193e-5  3.99119e-5  6.85725e-5
 6.94868e-6  3.92435e-5  2.83419e-5  9.39607e-6  9.11408e-5  4.08131e-5
 6.39143e-5  8.07473e-5  2.65192e-5  9.3099e-5   6.63436e-5  9.51232e-5
 9.05907e-5  1.33501e-6  1.68074e-5  6.79121e-5  2.31163e-5  3.9173e-5 

In [45]:
@show norm(ΔC)
μ=eigvals(C+ΔC)

norm(ΔC) = 0.0003152673674791101


6-element Array{Complex{Float64},1}:
 9.99997+0.0im    
 3.49997+6.06214im
 3.49997-6.06214im
    -9.5+4.33012im
    -9.5-4.33012im
 -3.9997+0.0im    

### Example - Hermitian matrix

In [46]:
m=10
n=6
A=rand(m,n)
# Some scaling
D=diagm((rand(n)-0.5)*exp(20))
A=A*D

10×6 Array{Float64,2}:
 7.5132e6   -5.55648e7  -7.64438e7  -1.66149e7  -1.63386e8  1.18489e7
 3.287e7    -1.45851e8  -1.03084e8  -1.48176e8  -6.84466e7  8.76988e6
 7.08335e6  -8.89844e7  -7.50507e7  -3.83114e6  -1.74728e8  3.86564e6
 8.91659e5  -2.22116e8  -1.03247e8  -1.11943e8  -1.26934e8  8.11015e6
 4.12768e7  -7.0973e7   -2.52113e7  -4.10038e7  -2.08255e8  4.46049e6
 2.92242e7  -1.69294e8  -7.42288e7  -1.32212e7  -1.41646e7  4.35094e6
 1.34822e7  -1.77262e8  -8.79891e6  -1.57164e8  -1.05574e8  5.97572e5
 3.29068e7  -1.36747e8  -7.48709e7  -1.88126e7  -1.85884e8  8.64352e6
 1.22814e7  -1.88896e8  -8.23273e7  -3.1027e7   -1.39463e8  6.27034e6
 3.08031e7  -1.56325e8  -1.53281e7  -1.38903e8  -1.95751e8  4.96986e6

In [47]:
A=cor(A)

6×6 Array{Float64,2}:
  1.0         0.216706   0.32947   -0.0526228  -0.0409572  -0.107417
  0.216706    1.0        0.167845   0.484116   -0.475422    0.226527
  0.32947     0.167845   1.0       -0.28466    -0.359969   -0.663481
 -0.0526228   0.484116  -0.28466    1.0        -0.173916    0.226361
 -0.0409572  -0.475422  -0.359969  -0.173916    1.0        -0.10834 
 -0.107417    0.226527  -0.663481   0.226361   -0.10834     1.0     

In [48]:
ΔA=cor(rand(m,n)*D)*1e-5

6×6 Array{Float64,2}:
  1.0e-5       6.12236e-8  -3.19053e-6   7.46852e-7  -4.21836e-6  -1.6462e-6 
  6.12236e-8   1.0e-5      -5.99331e-8   3.32769e-6   1.52986e-7  -5.61261e-6
 -3.19053e-6  -5.99331e-8   1.0e-5       2.18164e-6   2.23744e-6   1.29535e-6
  7.46852e-7   3.32769e-6   2.18164e-6   1.0e-5      -3.39068e-6  -3.56411e-7
 -4.21836e-6   1.52986e-7   2.23744e-6  -3.39068e-6   1.0e-5      -7.31302e-7
 -1.6462e-6   -5.61261e-6   1.29535e-6  -3.56411e-7  -7.31302e-7   1.0e-5    

In [49]:
B=A+ΔA

6×6 Array{Float64,2}:
  1.00001     0.216706   0.329467  -0.0526221  -0.0409614  -0.107419
  0.216706    1.00001    0.167844   0.484119   -0.475422    0.226521
  0.329467    0.167844   1.00001   -0.284658   -0.359967   -0.66348 
 -0.0526221   0.484119  -0.284658   1.00001    -0.173919    0.226361
 -0.0409614  -0.475422  -0.359967  -0.173919    1.00001    -0.108341
 -0.107419    0.226521  -0.66348    0.226361   -0.108341    1.00001 

In [50]:
λ,U=eig(A) 
μ=eigvals(B)
[λ μ]

6×2 Array{Float64,2}:
 0.123901  0.123915
 0.363441  0.363452
 0.767609  0.767618
 0.915298  0.915304
 1.87677   1.87678 
 1.95298   1.95299 

In [51]:
norm(ΔA)

1.7986543972680414e-5

In [52]:
# Residual bounds - how close is μ, y to λ[2],X[:,2]
k=3
μ=round(λ[k],2)
y=round.(U[:,k],2)
y=y/norm(y)

6-element Array{Float64,1}:
  0.130668 
 -0.0804111
 -0.0201028
 -0.693546 
 -0.422159 
  0.562878 

In [53]:
μ

0.77

In [54]:
# Fact 9
r=A*y-μ*y

6-element Array{Float64,1}:
 -0.000671223
 -0.00109835 
  0.000860664
  0.00123622 
  0.00265362 
 -0.000706823

In [55]:
minimum(abs,μ-λ), norm(r)

(0.002391274450983083, 0.0033863237540606443)

In [56]:
# Fact 10 - μ is Rayleigh quotient
μ=y⋅(A*y)
r=A*y-μ*y

6-element Array{Float64,1}:
 -0.000358643
 -0.00129071 
  0.000812575
 -0.000422861
  0.00164375 
  0.000639675

In [57]:
η=min(abs(μ-λ[k-1]),abs(μ-λ[k+1]))

0.14768979749804312

In [58]:
μ-λ[k], norm(r)^2/η

(-8.912397204685618e-7, 3.8897283176329225e-5)

In [59]:
# Eigenvector bound
# cos(θ)
cosθ=dot(y,U[:,k])
# sin(θ)
sinθ=sqrt(1-cosθ^2)
sinθ,norm(r)/η

(0.003673726700830189, 0.016228724466098778)

In [60]:
# Residual bounds - Fact 13
U=eigvecs(A)
Q=round.(U[:,1:3],2)
# Orthogonalize
X,R=qr(Q)
M=X'*A*X
R=A*X-X*M
μ=eigvals(M)
R

6×3 Array{Float64,2}:
  0.00334204   -0.00305685   0.000101505
 -0.00184431   -0.00215055   0.00109278 
  0.00802689   -0.00440734   0.000349577
 -0.00518804    0.00043765   0.000729886
 -0.000759485   0.00252428  -0.00106985 
 -0.00771464    0.00267746   0.000241967

In [61]:
λ

6-element Array{Float64,1}:
 0.123901
 0.363441
 0.767609
 0.915298
 1.87677 
 1.95298 

In [62]:
μ

3-element Array{Float64,1}:
 0.123992
 0.767612
 0.363472

In [63]:
# The entries of μ are not ordered - which algorithm was called?
issymmetric(M)

false

In [64]:
M=Hermitian(M)
R=A*X-X*M
μ=eigvals(M)

3-element Array{Float64,1}:
 0.123992
 0.363472
 0.767612

In [65]:
η=λ[4]-λ[3]

0.14768890625832265

In [66]:
norm(λ[1:3]-μ), vecnorm(R)^2/η

(9.619831268680912e-5, 0.0014638790207778718)

In [67]:
# Fact 13
M=A[1:3,1:3]
H=A[4:6,4:6]
E=A[4:6,1:3]
# Block-diagonal matrix
B=cat([1,2],M,H)

6×6 Array{Float64,2}:
 1.0       0.216706  0.32947    0.0        0.0        0.0     
 0.216706  1.0       0.167845   0.0        0.0        0.0     
 0.32947   0.167845  1.0        0.0        0.0        0.0     
 0.0       0.0       0.0        1.0       -0.173916   0.226361
 0.0       0.0       0.0       -0.173916   1.0       -0.10834 
 0.0       0.0       0.0        0.226361  -0.10834    1.0     

In [68]:
η=minimum(abs,eigvals(M)-eigvals(H))
μ=eigvals(B)
[λ μ]

6×2 Array{Float64,2}:
 0.123901  0.665189
 0.363441  0.759756
 0.767609  0.851795
 0.915298  0.896659
 1.87677   1.34359 
 1.95298   1.48302 

In [69]:
2*norm(E)^2/(η+sqrt(η^2+4*norm(E)^2))

0.8335136211809866

In [70]:
# Eigenspace bounds - Fact 14
B=A+ΔA
μ,V=eig(B)

([0.123915, 0.363452, 0.767618, 0.915304, 1.87678, 1.95299], [0.103017 0.300815 … 0.306124 -0.231031; 0.256569 -0.705346 … 0.603549 0.244541; … ; -0.263458 -0.488428 … -0.554187 -0.0481877; -0.542726 -0.0612388 … -0.0296229 0.593927])

In [71]:
# sin(Θ(U[:,1:3],V[:,1:3]))
X=U[:,1:3]
Q=V[:,1:3]
cosθ=svdvals(sqrtm(Q'*Q)*Q'*X*sqrtm(X'*X))
sinθ=sqrt.(1-cosθ.^2)

3-element Array{Float64,1}:
 1.11151e-6
 4.18569e-6
 8.98759e-6

In [72]:
# Bound
M=Q'*A*Q

3×3 Array{Float64,2}:
  0.123901    -6.43048e-7   9.44664e-7
 -6.43048e-7   0.363441    -4.00189e-6
  9.44664e-7  -4.00189e-6   0.767609  

In [73]:
R=A*Q-Q*M

6×3 Array{Float64,2}:
 -3.57837e-6  -2.00699e-6   6.76391e-7
 -1.55747e-6  -2.33769e-6   2.48687e-6
 -4.50612e-7   6.08486e-7   2.25188e-6
 -6.22714e-7  -1.87907e-6   1.00817e-6
 -2.76393e-7   6.81236e-7  -2.91319e-6
 -3.89137e-7  -1.64911e-6  -6.78909e-7

In [74]:
eigvals(M), λ

([0.123901, 0.767609, 0.363441], [0.123901, 0.363441, 0.767609, 0.915298, 1.87677, 1.95298])

In [75]:
η=abs(eigvals(M)[3]-λ[4])
vecnorm(sinθ), vecnorm(R)/η

(9.976580591137428e-6, 1.3353306158869609e-5)