# Eigenvalue Decomposition - Perturbation Theory

---

## Prerequisites

The reader should be familiar with basic linear algebra concepts and facts about eigenvalue decomposition. 

## Competences 

The reader should be able to understand and check the facts about perturbations of eigenvalues and eigenvectors.

---

## Norms

In order to measure changes, we need to define norms. For more details and the proofs of the Facts below, see 
[R. Byers and B. N. Datta, Vector and Matrix Norms, Error Analysis, Efficiency, and Stability][Hog14] and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 50.1-50.24, CRC Press, Boca Raton, 2014."

### Definitions

__Norm__ on a vector space $X$ is a real-valued function $\| \phantom{x} \| : X\to \mathbb{R}$ with the following properties:

1. $\| x\|\geq 0$ and $\|x\|=0$ if and only if $x$ is the zero vector _(Positive definiteness)_
2. $\| \lambda x\|=|\lambda| \|x\|$ _(Homogeneity)_
3. $\| x+y\| \leq \|x\|+\|y\|$ _(Triangle inequality)_

Commonly encountered vector norms for $x\in\mathbb{C}^n$ are:

* __H&ouml;lder norm__ or $p$-__norm__: for $p\geq 1$, $\|x\|_p=\big(|x_1|^p+|x_2|^p+\cdots |x_n|^p)^{1/p}$,
* __Sum norm__ or $1$-__norm__: $\|x\|_1=|x_1|+|x_2|+\cdots |x_n|$,
* __Euclidean norm__ or $2$-__norm__: $\|x\|_2=\sqrt{|x_1|^2+|x_2|^2+\cdots |x_n|^2}$,
* __Sup-norm__ or $\infty$-__norm__: $\|x\|_\infty = \max\limits_{i=1,\ldots,n} |x_i|$.

Vector norm is __absolute__ if $\||x|\|=\|x\|$.

Vector norm is __monotone__ if $|x|\leq |y|$ implies $\|x\|\leq \|y\|$. 

From every vector norm we can derive a corresponding __induced__ matrix norm (also, __operator norm__ or __natural norm__):

$$\|A\| = \max\limits_{x\neq 0} \frac{\|Ax\|}{\|x\|}=\max\limits_{\|x\|=1} \|Ax\|.$$

For matrix $A\in\mathbb{C}^{m\times n}$ we define:

* __Maximum absolute column sum norm__: $\|A\|_1=\max\limits_{1\leq j \leq n} \sum_{i=1}^m |a_{ij}|$,
* __ Spectral norm__: $\|A\|_2=\sqrt{\rho(A^*A)}=\sigma_{\max}(A)$  (largest singular value of $A$),
* __Maximum absolute row sum norm__: $\|A\|_{\infty}=\max\limits_{1\leq i \leq m} \sum_{j=1}^n |a_{ij}|$,
* __Euclidean norm__ or __Frobenius norm__: 
$\|A\|_F =\sqrt{\sum_{i,j} |a_{ij}|^2}=\sqrt{\mathop{\mathrm{tr}}(A^*A)}$.

Matrix norm is __consistent__ if $\|A\cdot B\|\leq \|A\| \cdot \| B\|$, where $A$ and $B$ are compatible for matrix multiplication.

Matrix norm is __absolute__ if $\||A|\|=\|A\|$.

### Examples

In [1]:
x=rand(-4:4,5)

5-element Array{Int64,1}:
  3
  4
 -1
 -2
  1

In [2]:
norm(x,1), norm(x), norm(x,Inf)

(11.0,5.5677643628300215,4.0)

In [3]:
A=rand(-4:4,7,5)

7x5 Array{Int64,2}:
 -3  -2   0   2   2
  0   1  -2   2  -4
  4  -2   1   3   2
 -1   3   2  -2   1
  0   0   2   3  -2
  1   1   1   0   4
  2  -1   4  -3   0

In [4]:
norm(A,1), norm(A), norm(A,2), norm(A,Inf), vecnorm(A)

(15.0,7.769185860688749,7.769185860688749,12.0,12.84523257866513)

In [6]:
norm(vec(A))

12.84523257866513

### Facts


1. $\|x\|_1$, $\|x\|_2$, $\|x\|_\infty$ and $\|x\|_p$ are absolute and monotone vector norms.
2. A vector norm is absolute iff it is monotone.
3. _Convergence_: $x_k\to x_*$ iff for any vector norm $\|x_k-x_*\|\to 0$.
3. Any two vector norms are equivalent in the sense that, for all $x$ and some $\alpha,\beta>0$
$$
\alpha \|x\|_\mu \leq \|x\|_\nu \leq \beta \|x\|_\mu.
$$
In particular:
   * $\|x\|_2 \leq \|x\|_1\leq \sqrt{n}\|x\|_2$,
   * $\|x\|_\infty \leq \|x\|_2\leq \sqrt{n}\|x\|_\infty$,
   * $\|x\|_\infty \leq \|x\|_1\leq n\|x\|_\infty$.
2. _Cauchy-Schwartz inequality_: $|x^*y|\leq \|x\|_2\|y\|_2$.
3. _H&ouml;lder inequality_: if $p,q\geq 1$ and $\frac{1}{p}+\frac{1}{q}=1$, then $|x^*y|\leq \|x\|_p\|y\|_q$.
1. $\|A\|_1$, $\|A\|_2$ and $\|A\|_\infty$ are induced by the corresponding vector norms.
2. $\|A\|_F$ is not and induced norm.
3. $\|A\|_1$, $\|A\|_2$, $\|A\|_\infty$ and $\|A\|_F$ are consistent.
4. $\|A\|_1$, $\|A\|_\infty$ and $\|A\|_F$ are absolute. However, $\||A|\|_2\neq \|A\|_2$.
5. Any two matrix norms are equivalent in the sense that, for all $A$ and some $\alpha,\beta>0$
$$
\alpha \|A\|_\mu \leq \|A\|_\nu \leq \beta \|A\|_\mu.
$$
In particular:
   * $\frac{1}{\sqrt{n}}\|A\|_\infty \leq \|A\|_2\leq \sqrt{m}\|A\|_\infty$,
   * $\|A\|_2 \leq \|A\|_F\leq \sqrt{n}\|A\|_2$,
   * $\frac{1}{\sqrt{m}}\|A\|_1 \leq \|A\|_2\leq \sqrt{n}\|A\|_1$.
6. $\|A\|_2\leq \sqrt{\|A\|_1 \|A\|_\infty}$.
7. $\|AB\|_F\leq \|A\|_F\|B\|_2$ and $\|AB\|_F\leq \|A\|_2\|B\|_F$.
8. If $A=xy^*$, then $\|A\|_2=\|A\|_F=\|x\|_2\|y\|_2$.
9. $\|A^*\|_2=\|A\|_2$ and $\|A^*\|_F=\|A\|_F$.
10. For a unitary matrix $U$ of compatible dimension,
$$\|AU\|_2=\|A\|_2,\quad \|AU\|_F=\|A\|_F,\quad
\|UA\|_2=\|A\|_2,\quad  \|UA\|_F=\|A\|_F.
$$
11. For $A$ square, $\rho(A)\leq\|A\|$.
12. For $A$ square, $A^k\to 0$ iff $>\rho(A)<1$.

In [7]:
# Absolute norms
norm(A,1), norm(abs(A),1), norm(A,Inf), norm(abs(A),Inf), vecnorm(A),
vecnorm(abs(A)),  norm(A),norm(abs(A))

(15.0,15.0,12.0,12.0,12.84523257866513,12.84523257866513,7.769185860688749,10.925217814397506)

In [8]:
# Equivalence of norms
m,n=size(A)
norm(A,Inf)\sqrt(n),norm(A), sqrt(m)*norm(A,Inf)

(0.18633899812498247,7.769185860688749,31.74901573277509)

In [9]:
norm(A), vecnorm(A), sqrt(n)*norm(A)

(7.769185860688749,12.84523257866513,17.372427714330254)

In [10]:
norm(A,1)\sqrt(m),norm(A), sqrt(n)*norm(A,1)

(0.17638342073763938,7.769185860688749,33.54101966249685)

In [11]:
# Fact 12
norm(A), sqrt(norm(A,1)*norm(A,Inf))

(7.769185860688749,13.416407864998739)

In [13]:
# Fact 13
B=rand(n,rand(1:9))
vecnorm(A*B), vecnorm(A)*norm(B), norm(A)*vecnorm(B)

(17.39391657295395,36.64419785557018,25.549669589506628)

In [15]:
# Fact 14
x=rand(10)+im*rand(10)
y=rand(10)+im*rand(10)
A=x*y'
norm(A), vecnorm(A), norm(x)*norm(y)

(8.163126728063434,8.163126728063432,8.163126728063432)

In [16]:
# Fact 15
A=rand(-4:4,7,5)+im*rand(-4:4,7,5)
norm(A), norm(A'), vecnorm(A), vecnorm(A')

(14.69243849374946,14.69243849374946,20.688160865577203,20.688160865577203)

In [18]:
# Unitary invariance - generate random unitary matrix U
U,R=qr(rand(size(A))+im*rand(size(A)),thin=false);

In [19]:
norm(A), norm(U*A), vecnorm(A), vecnorm(U*A)

(14.69243849374946,14.692438493749457,20.688160865577203,20.6881608655772)

In [20]:
# Spectral radius
A=rand(7,7)+im*rand(7,7)
maxabs(eigvals(A)), norm(A,Inf), norm(A,1), norm(A), vecnorm(A)

(4.939800178955722,6.337162218176092,5.970131091829915,5.0968404553445605,5.647736689955629)

In [25]:
# Fact 18
B=A/(maxabs(eigvals(A))+2)
@show maxabs(eigvals(B))
norm(B^100)

maxabs(eigvals(B)) = 0.7118072641248647


1.7713644872588498e-15

## Errors and condition numbers

We want to answer the question:

__How much the value of a function changes with respect to the change of its argument?__

### Definitions

For function $f(x)$ and argument $x$, the __absolute error__ with respect to the __perturbation__ of the argument 
$\delta x$ is 

$$
\| f(x+\delta x)-f(x)\| = \frac{\| f(x+\delta x)-f(x)\|}{\| \delta x \|} \|\delta x\| \equiv \kappa \|\delta x\|.
$$

The  __condition__ or  __condition number__ $\kappa$ tells how much does the perturbation of the argument increase. (Its form resembles derivative.)

Similarly, the __relative error__ with respect to the relative perturbation of the argument is

$$
\frac{\| f(x+\delta x)-f(x)\|}{\| f(x) \|}= \frac{\| f(x+\delta x)-f(x)\|\cdot  \|x\| }{\|\delta x\| \cdot\| f(x)\|}
\cdot \frac{\|\delta x\|}{\|x\|} \equiv \kappa_{rel} \frac{\|\delta x\|}{\|x\|}.
$$

## Peturbation bounds

### Definitions

Let $A\in\mathbb{C}^{n\times n}$.

Pair $(\lambda,x)\in\mathbb{C}\times\mathbb{C}^{n\times n}$ is an __eigenpair__ of $A$ if $x\neq 0$ and $Ax=\lambda x$.

Triplet $(y,\lambda,x)\in\times\mathbb{C}^{n}\times\mathbb{C}\times\mathbb{C}^{n}$ is an __eigentriplet__ of $A$ if $x,y\neq 0$ and $Ax=\lambda x$ and $y^*A=\lambda y^*$.

__Eigenvalue matrix__ is a diagonal matrix $\Lambda=\mathop{\mathrm{diag}}(\lambda_1,\lambda_2,\ldots,\lambda_n)$.

If all eigenvalues are real, they can be increasingly ordered. $\Lambda^\uparrow$ is the eigenvalue matrix of increasingly ordered eigenvalues.

$\tau$ is a __permutation__ of $\{1,2,\ldots,n\}$.

$\tilde A=A+\Delta A$ is a __perturbed matrix__, where $\Delta A$ is __perturbation__. $(\tilde \lambda,\tilde x)$ are the eigenpairs of $\tilde A$.

__Condition number__ of a nonsingular matrix $X$ is $\kappa(X)=\|X\| \|X^{-1}\|$.

Let $X,Y\in\mathbb{C}^{n\times k}$ with $\mathop{\mathrm{rank}}(X)=\mathop{\mathrm{rank}}(Y)=k$. The __canonical angles__ between their column spaces are $\theta_i=\cos^{-1}\sigma_i$, where $\sigma_i$ are the singular values of 
$(Y^*Y)^{-1/2}Y^*X(X^*X)^{-1/2}$. The __canonical angle matrix__ between $X$ and $Y$ is 
$$\Theta(X,Y)=\mathop{\mathrm{diag}}(\theta_1,\theta_2,\ldots,\theta_k).
$$
    

### Facts

Bounds become more strict as matrices have more structure. 
Many bounds have versions in spectral norm and Frobenius norm.
For more details and the proofs of the Facts below, see 
[R.-C. Li, Matrix Perturbation Theory][Hog14], and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 21.1-21.20, CRC Press, Boca Raton, 2014."

1. There exists $\tau$ such that
$$\|\Lambda- \tilde\Lambda_\tau\|_2\leq 4(\|A\|_2+\|\tilde A\|_2)^{1-1/n}\|\Delta A\|_2^{1/n}.$$

2. _(First-order perturbation bounds)_ Let $(y,\lambda,x)$ be an eigentriplet of a simple $\lambda$. $\Delta A$ changes $\lambda$ to 
$\tilde\lambda=\lambda+ \delta\lambda$, where
$$
\delta\lambda=\frac{y^*(\Delta A)x}{y^*x}+O(\|\Delta A\|_2^2).
$$

3. Let $\lambda$ be a semisimple eigenvalue of $A$ with multiplicitiy $k$, and let $X,Y\in \mathbb{C}^{n\times k}$ be the matrices of the corresponding right and left eigenvectors, that is, $AX=\lambda X$ and $Y^*A=\lambda Y^*$, such that $Y^*X=I_k$. $\Delta A$ changes the $k$ copies of $\mu$ to $\tilde \mu=\mu+\delta\mu_i$, where $\delta\mu_i$ are the eigenvalues of $Y^*(\Delta A) X$ up to $O(\|\Delta A\|_2^2$.

4. _(Bauer-Fike Theorem)_ If $A$ is diagonalizable and $A=X\Lambda X^{-1}$ is its eigenvalue decomposition, then
$$
\max_i\min_j |\tilde \lambda_i -
\lambda_j|\leq \|X^{-1}(\Delta A)X\|_p\leq \kappa_p(X)\|\Delta A\|_p.
$$

5. If $A$ and $\tilde A$ are diagonalizable, there exists $\tau$ such that
$$\|\Lambda-\tilde\Lambda_\tau\|_F\leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_F.
$$ If $\Lambda$ and  $\tilde\Lambda$ are real, then
$$
\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\|_{2,F} \leq \sqrt{\kappa_2(X)\kappa_2(\tilde X)}\|\Delta A\|_{2,F}.
$$

6. If $A$ is normal, there exists $\tau$ such that $\|\Lambda-\tilde\Lambda_\tau\|_F\leq\sqrt{n}\|\Delta A\|_F$.

7. _(Hoffman-Wielandt Theorem)_ If $A$ and $\tilde A$ are normal, there exists $\tau$ such that $\|\Lambda-\tilde\Lambda_\tau\|_F\leq\|\Delta A\|_F$.

8. If $A$ is Hermitian, for any unitarily invariant norm $\|\Lambda^\uparrow-\tilde\Lambda^\uparrow\| \leq \|\Delta A\|$. In particular,
\begin{align*}
\max_i|\lambda^\uparrow_i-\tilde\lambda^\uparrow_i|&\leq \|\Delta A\|_2,\\ 
\sqrt{\sum_i(\lambda^\uparrow_i-\tilde\lambda^\uparrow_i)^2}&\leq \|\Delta A\|_F.
\end{align*}

9. _(Residual bounds)_ Let $A$ be Hermitian. For some $\tilde\lambda\in\mathbb{R}$ and $\tilde x\in\mathbb{C}^n$ with $\|\tilde x\|_2=1$, define __residual__ $r=A\tilde x-\tilde\lambda\tilde x$. Then
$|\tilde\lambda-\lambda|\leq \|r\|_2$ for some $\lambda\in\sigma(A)$.

9. Let, in addition,  $\tilde\lambda=\tilde x^* A\tilde x$, let $\lambda$ be closest to $\tilde\lambda$ and $x$ be its unit eigenvector, and let 
$$\eta=\mathop{\mathrm{gap}}(\tilde\lambda)= \min_{\lambda\neq\mu\in\sigma(A)}|\tilde\lambda-\mu|.$$
If $\eta>0$, then
$$ |\tilde\lambda-\lambda|\leq \frac{\|r\|_2^2}{\eta},\quad \sin\theta(x,\tilde x)\leq \frac{\|r\|_2}{\eta}.
$$

10. Let $A$ be Hermitian, $X\in\mathbb{C}^{n\times k}$ have full column rank, and $M\in\mathcal{H}_k$ having eigenvalues 
$\mu_1\leq\mu_2\leq\cdots\leq\mu_k$. Set $R=AX-XM$. Then
there exist $\lambda_{i_1}\leq\lambda_{i_2}\leq\cdots\leq\lambda_{i_k}\in\sigma(A)$ such that
\begin{align*}    
\max_{1\leq j\leq k} |\mu_j-\lambda_{i_j}|& \leq \frac{\|R\|_2}{\sigma_{\min}(X)},\\
\sqrt{\sum_{j=1}^k (\mu_j-\lambda_{i_j})^2}&\leq \frac{\|R\|_F}{\sigma_{\min}(X)}.
\end{align*}
(The indices $i_j$ need not be the same in the above formulae.)

10. If, additionally, $X^*X=I$ and $M=X^*AX$, and if all but $k$ of $A$'s eigenvalues differ from every one of $M$'s eigenvalues by at least $\eta>0$, then
$$\sqrt{\sum_{j=1}^k (\mu_j-\lambda_{i_j})^2}\leq \frac{\|R\|_F^2}{\eta\sqrt{1-\|R\|_F^2/\eta^2}}.$$

11. Let $A=\begin{bmatrix} M & E^* \\ E & H \end{bmatrix}$ and $\tilde A=\begin{bmatrix} M & 0 \\ 0 & H \end{bmatrix}$ be Hermitian, and set $\eta=\min |\mu-\nu|$ over all $\mu\in\sigma(M)$ and $\nu\in\sigma(H)$. Then
$$ 
\max |\lambda_j^\uparrow -\tilde\lambda_j^\uparrow| \leq \frac{2\|E\|_2^2}{\eta+\sqrt{\eta^2+4\|E\|_2^2}}.
$$

14. Let 
$$
\begin{bmatrix} X_1^*\\ X_2^* \end{bmatrix} A \begin{bmatrix} X_1 & X_2 \end{bmatrix}=
\begin{bmatrix} A_1 &  \\ & A_2 \end{bmatrix}, \quad \begin{bmatrix} X_1 & X_2 \end{bmatrix} \textrm{unitary},
\quad X_1\in\mathbb{C}^{n\times k}.
$$
Let $Q\in\mathbb{C}^{n\times k}$ have orthonormal columns and for a Hermitian $k\times k$ matrix $M$ set
$R=AQ-QM$. Let $\eta=\min|\mu-\nu|$ over all $\mu\in\sigma(M)$ and $\nu\in\sigma(A_2)$. If $\eta > 0$, then
$$
\|\sin\Theta(X_1,Q)\|_F\leq \frac{\|R\|_F}{\eta}.
$$

### Example - Nondiagonalizable matrix

In [40]:
A=[-3 7 -1; 6 8 -2; 72 -28 19]

3x3 Array{Int64,2}:
 -3    7  -1
  6    8  -2
 72  -28  19

In [41]:
# (Right) eigenvectors
λ,X=eig(A)

([-6.000000000000005,15.000000241477958,14.999999758522048],
3x3 Array{Float64,2}:
  0.235702   0.218218  -0.218218
 -0.235702   0.436436  -0.436436
 -0.942809  -0.872872   0.872872)

In [42]:
cond(X)

9.091581997455394e7

In [43]:
# Left eigenvectors
λ1,Y=eig(A')

(Complex{Float64}[-5.999999999999998 + 0.0im,14.999999999999993 + 2.0088262607214127e-7im,14.999999999999993 - 2.0088262607214127e-7im],
3x3 Array{Complex{Float64},2}:
     0.894427+0.0im               0.970143+0.0im               0.970143-0.0im
    -0.447214+0.0im  -7.58506e-16-1.62404e-8im    -7.58506e-16+1.62404e-8im  
 -6.07504e-17+0.0im       0.242536+4.0601e-9im         0.242536-4.0601e-9im  )

In [44]:
# Try k=2,3
k=3
Y[:,k]'*A-λ[k]*Y[:,k]'

1x3 Array{Complex{Float64},2}:
 2.34268e-7+1.94885e-7im  9.60124e-15-3.9217e-15im  5.8567e-8+4.87212e-8im

In [45]:
ΔA=rand(3,3)/20
B=A+ΔA

3x3 Array{Float64,2}:
 -2.994      7.03203  -0.967823
  6.01664    8.02073  -1.99135 
 72.0002   -27.987    19.039   

In [46]:
norm(ΔA)

0.0633478703837324

In [47]:
μ,Z=eig(B)

([-6.089801552211211,15.68225690289727,14.473225661829952],
3x3 Array{Float64,2}:
  0.237844   0.191836  -0.241757
 -0.234438   0.385262  -0.484829
 -0.942586  -0.902647   0.840532)

In [48]:
# Fact 2
δλ=μ[1]-λ[1]

-0.08980155221120611

In [52]:
k=1
Y[:,k]'*ΔA*X[:,k]/(Y[:,k]⋅X[:,k])

1-element Array{Complex{Float64},1}:
 -0.090266+0.0im

### Example - Jordan form

In [53]:
n=10
c=0.5
J=Bidiagonal(c*ones(n),ones(n-1),true)

10x10 Bidiagonal{Float64}:
 0.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.5  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.5  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.5  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.5  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.5  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.5  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.5  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.5

In [54]:
# Accurately defined eigenvalues
λ=eigvals(J)

10-element Array{Float64,1}:
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5

In [55]:
# Only one eigenvector
X=eigvecs(J)

10x10 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [56]:
x=eigvecs(J)[:,1]
y=eigvecs(J')[:,1]

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

In [57]:
y'*full(J)-0.5*y'

1x10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [58]:
# Just one perturbed element in the lower left corner
ΔJ=sqrt(eps())*[zeros(n-1);1]*eye(1,n)

10x10 Array{Float64,2}:
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.49012e-8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [59]:
B=J+ΔJ
μ=eigvals(B)

10-element Array{Complex{Float64},1}:
 0.335062+0.0im      
 0.366562+0.0969484im
 0.366562-0.0969484im
 0.449031+0.156866im 
 0.449031-0.156866im 
 0.550969+0.156866im 
 0.550969-0.156866im 
 0.633438+0.0969484im
 0.633438-0.0969484im
 0.664938+0.0im      

In [60]:
# Fact 2
maximum(abs(λ-μ))

0.16493848891190788

In [61]:
y'*ΔJ*x/(y⋅x)

1-element Array{Float64,1}:
 Inf

However, since $B$ is diagonalizable, we can apply Bauer-Fike theorem to it: 

In [62]:
μ,Y=eig(B)

(Complex{Float64}[0.3350615111920276 + 0.0im,0.3665619595167544 + 0.09694841124280963im,0.3665619595167544 - 0.09694841124280963im,0.4490312038888047 + 0.15686582456677023im,0.4490312038888047 - 0.15686582456677023im,0.5509687960268455 + 0.15686582462828694im,0.5509687960268455 - 0.15686582462828694im,0.6334380405156275 + 0.09694841134170258im,0.6334380405156275 - 0.09694841134170258im,0.6649384889119079 + 0.0im],
10x10 Array{Complex{Float64},2}:
   -0.986304+0.0im              0.986304+0.0im          …     0.986304+0.0im
    0.162679+0.0im              -0.13161+0.0956206im          0.162679+0.0im
  -0.0268321+0.0im            0.00829158-0.0255188im         0.0268321+0.0im
  0.00442565+0.0im             0.0013676+0.00420904im       0.00442565+0.0im
 -0.00072996+0.0im           -0.00059055-0.000429059im      0.00072996+0.0im
 0.000120398+0.0im  0.000120398+6.48524e-14im           …  0.000120398+0.0im
 -1.98583e-5+0.0im  -1.60657e-5+1.16724e-5im                1.98583e-5+0.0im
   3.2754e

In [63]:
cond(Y)

1.1068834616372587e7

In [64]:
norm(inv(Y)*ΔJ*Y), cond(Y)*norm(ΔJ)

(0.16493848884660858,0.1649384888466088)

### Example - Normal matrix

In [65]:
using SpecialMatrices

In [66]:
n=6
C=Circulant(rand(n))

6x6 SpecialMatrices.Circulant{Float64}:
 0.839873  0.972672  0.796722  0.938404  0.668738  0.483951
 0.483951  0.839873  0.972672  0.796722  0.938404  0.668738
 0.668738  0.483951  0.839873  0.972672  0.796722  0.938404
 0.938404  0.668738  0.483951  0.839873  0.972672  0.796722
 0.796722  0.938404  0.668738  0.483951  0.839873  0.972672
 0.972672  0.796722  0.938404  0.668738  0.483951  0.839873

In [67]:
λ=eigvals(full(C))

6-element Array{Complex{Float64},1}:
    4.70036+0.0im     
   -0.10295+0.534083im
   -0.10295-0.534083im
   0.317237+0.312407im
   0.317237-0.312407im
 -0.0896933+0.0im     

In [68]:
ΔC=rand(n,n)*0.0001

6x6 Array{Float64,2}:
 7.80923e-5  9.94615e-5  4.61706e-5  1.49864e-5  9.53938e-5  9.4143e-5 
 1.40809e-5  5.94743e-6  7.90804e-5  2.0352e-5   2.38248e-5  5.82097e-5
 6.55942e-5  5.50246e-5  1.48565e-5  7.78751e-5  8.99909e-5  5.49387e-5
 8.52461e-5  5.61173e-5  9.70967e-5  3.98743e-5  3.37698e-5  2.80123e-5
 9.10812e-5  7.86243e-5  1.58107e-5  5.94569e-6  5.10499e-5  9.54479e-6
 5.96041e-5  9.68311e-6  7.16509e-5  6.48051e-5  6.00179e-5  4.16628e-5

In [69]:
@show norm(ΔC)
μ=eigvals(C+ΔC)

norm(ΔC) = 0.0003280799685464677


6-element Array{Complex{Float64},1}:
   4.70067+0.0im     
 -0.102963+0.534077im
 -0.102963-0.534077im
  0.317219+0.312422im
  0.317219-0.312422im
 -0.089717+0.0im     

In [70]:
λ

6-element Array{Complex{Float64},1}:
    4.70036+0.0im     
   -0.10295+0.534083im
   -0.10295-0.534083im
   0.317237+0.312407im
   0.317237-0.312407im
 -0.0896933+0.0im     

### Example - Hermitian matrix

In [72]:
m=10
n=6
A=rand(m,n)
# Some scaling
D=diagm((rand(n)-0.5)*exp(20))
A=A*D

10x6 Array{Float64,2}:
 4.68723e6  -1.61978e6  -1.43215e8  9.92442e7  9.38944e7  -1.05361e8
 2.92458e7  -6.01205e7  -6.86453e6  1.09225e8  2.93499e7  -1.34852e8
 3.98754e7  -1.39037e8  -5.42486e7  7.08408e7  6.20342e7  -5.40849e7
 7.19523e7  -6.66203e7  -7.26219e7  9.29318e7  1.77954e8  -6.67456e7
 2.50905e7  -2.16041e8  -1.74833e7  1.51602e8  1.61512e7  -1.68418e8
 7.12306e7  -6.63539e7  -5.10338e7  5.67614e7  1.9457e8   -8.57768e7
 7.69074e7  -1.62113e8  -8.25782e7  1.95486e8  6.60085e7  -4.65106e7
 5.62677e7  -1.09113e8  -1.35853e7  2.24811e7  5.41631e7  -2.62331e7
 5.44872e6  -1.63262e8  -1.20547e8  5.24115e7  5.1354e7   -1.10613e8
 4.1468e7   -7.48028e7  -9.90906e7  4.61141e7  1.94056e8  -7.8754e7 

In [73]:
A=cor(A)

6x6 Array{Float64,2}:
  1.0         -0.00900098   0.334128    0.130912    0.463433   0.619772 
 -0.00900098   1.0         -0.295965   -0.345767    0.535686   0.151591 
  0.334128    -0.295965     1.0         0.0404434  -0.33555   -0.0870318
  0.130912    -0.345767     0.0404434   1.0        -0.356336  -0.29632  
  0.463433     0.535686    -0.33555    -0.356336    1.0        0.317913 
  0.619772     0.151591    -0.0870318  -0.29632     0.317913   1.0      

In [74]:
ΔA=cor(rand(m,n)*D)*1e-5

6x6 Array{Float64,2}:
  1.0e-5      -1.36018e-6   3.17499e-6   3.0635e-6   -5.81645e-6  -1.51331e-6
 -1.36018e-6   1.0e-5       3.64825e-6  -2.11891e-7  -4.10982e-6  -2.80424e-6
  3.17499e-6   3.64825e-6   1.0e-5       1.48331e-6  -3.93263e-6  -4.11282e-6
  3.0635e-6   -2.11891e-7   1.48331e-6   1.0e-5       3.69778e-7   5.84041e-6
 -5.81645e-6  -4.10982e-6  -3.93263e-6   3.69778e-7   1.0e-5       8.73753e-7
 -1.51331e-6  -2.80424e-6  -4.11282e-6   5.84041e-6   8.73753e-7   1.0e-5    

In [75]:
B=A+ΔA

6x6 Array{Float64,2}:
  1.00001     -0.00900234   0.334131    0.130915    0.463427   0.619771 
 -0.00900234   1.00001     -0.295961   -0.345768    0.535682   0.151589 
  0.334131    -0.295961     1.00001     0.0404449  -0.335554  -0.0870359
  0.130915    -0.345768     0.0404449   1.00001    -0.356336  -0.296314 
  0.463427     0.535682    -0.335554   -0.356336    1.00001    0.317914 
  0.619771     0.151589    -0.0870359  -0.296314    0.317914   1.00001  

In [76]:
λ,U=eig(A) 
μ=eigvals(B)
[λ μ]

6x2 Array{Float64,2}:
 0.0151637  0.015175
 0.446823   0.446835
 0.716278   0.71629 
 0.93175    0.931759
 1.61492    1.61493 
 2.27507    2.27507 

In [77]:
norm(ΔA)

2.1907353225260797e-5

In [79]:
# Residual bounds - how close is μ, y to λ[2],X[:,2]
k=3
μ=round(λ[k],2)
y=round(U[:,k],2)
y=y/norm(y)

6-element Array{Float64,1}:
 -0.169941
 -0.489829
 -0.469836
 -0.219923
 -0.319888
  0.59979 

In [80]:
μ

0.72

In [81]:
# Fact 9
r=A*y-μ*y

6-element Array{Float64,1}:
 -0.00546351 
 -0.000961872
  0.00287959 
  0.00279741 
 -0.00401788 
 -0.00727543 

In [82]:
minimum(abs(μ-λ)), norm(r)

(0.0037220705637717177,0.010768841653597537)

In [83]:
# Fact 10 - μ is Rayleigh quotient
μ=(y'*A*y)[] # Vector, unfortunately
r=A*y-μ*y

6-element Array{Float64,1}:
 -0.00608328
 -0.00274827
  0.00116611
  0.00199535
 -0.00518451
 -0.00508801

In [84]:
η=min(abs(μ-λ[k-1]),abs(μ-λ[k+1]))

0.2153971594841746

In [85]:
μ-λ[k], norm(r)^2/η

(7.508693667368505e-5,0.00047664259468324665)

In [86]:
# Eigenvector bound
# cos(θ)
cosθ=dot(y,U[:,k])
# sin(θ)
sinθ=sqrt(1-cosθ^2)
sinθ,norm(r)/η

(0.00902764493773874,0.04704098848494193)

In [89]:
# Residual bounds - Fact 13
U=eigvecs(A)
Q=round(U[:,1:3],2)
# Orthogonalize
X,R=qr(Q)
M=X'*A*X
R=A*X-X*M
μ=eigvals(M)
λ, μ, R

([0.015163653655468411,0.4468225524462972,0.7162779294362283,0.9317501758570765,1.6149200635986434,2.275065625006287],[0.015182085709575355,0.7163542531793838,0.446860740393538],
6x3 Array{Float64,2}:
 -0.0020104     0.00352427  -0.00555125 
 -0.00231547    0.00316844  -0.00286047 
 -0.000168061  -0.00148052   0.000848665
  0.00325943   -0.00219385   0.00164777 
 -0.00289782    0.00469999  -0.00536911 
 -0.00294261    0.00412861  -0.00550346 )

In [90]:
# The entries of μ are not ordered - which algorithm was called?
issym(M)

false

In [91]:
M=Hermitian(M)
R=A*X-X*M
μ=eigvals(M)

3-element Array{Float64,1}:
 0.0151821
 0.446861 
 0.716354 

In [92]:
η=λ[4]-λ[3]

0.21547224642084828

In [93]:
norm(λ[1:3]-μ), vecnorm(R)^2/η

(8.731193333350986e-5,0.0009618904768011849)

In [94]:
# Fact 13
M=A[1:3,1:3]
H=A[4:6,4:6]
E=A[4:6,1:3]
# Block-diagonal matrix
B=cat([1,2],M,H)

6x6 Array{Float64,2}:
  1.0         -0.00900098   0.334128   0.0        0.0        0.0     
 -0.00900098   1.0         -0.295965   0.0        0.0        0.0     
  0.334128    -0.295965     1.0        0.0        0.0        0.0     
  0.0          0.0          0.0        1.0       -0.356336  -0.29632 
  0.0          0.0          0.0       -0.356336   1.0        0.317913
  0.0          0.0          0.0       -0.29632    0.317913   1.0     

In [95]:
η=minimum(abs(eigvals(M)-eigvals(H)))
μ=eigvals(B)
[λ μ], 2*norm(E)^2/(η+sqrt(η^2+4*norm(E)^2))

(
6x2 Array{Float64,2}:
 0.0151637  0.558084
 0.446823   0.64121 
 0.716278   0.711098
 0.93175    0.991065
 1.61492    1.45085 
 2.27507    1.64769 ,

0.9265931815031623)

In [96]:
# Eigenspace bounds - Fact 14
B=A+ΔA
μ,V=eig(B)

([0.015174991050246065,0.4468350586829201,0.7162898094187525,0.9317594156811587,1.6149327375994904,2.2750679875674336],
6x6 Array{Float64,2}:
  0.627882    0.0780697  -0.165189   0.196101   -0.649864  -0.334069
  0.0952271  -0.661411   -0.48816   -0.0210619   0.354002  -0.435209
 -0.362628   -0.0996506  -0.471654  -0.56877    -0.519867   0.205799
 -0.318856   -0.269897   -0.216488   0.773022   -0.234665   0.354948
 -0.460575    0.565897   -0.315623   0.198291    0.056344  -0.570543
 -0.389099   -0.391698    0.604541  -0.0268218  -0.351931  -0.452913)

In [97]:
# sin(Θ(U[:,1:3],V[:,1:3]))
X=U[:,1:3]
Q=V[:,1:3]
cosθ=svdvals(sqrtm(Q'*Q)*Q'*X*sqrtm(X'*X))
sinθ=sqrt(1-cosθ.^2)

3-element Array{Float64,1}:
 3.92554e-7
 3.10706e-6
 2.33575e-5

In [98]:
# Bound
M=Q'*A*Q

3x3 Array{Float64,2}:
 0.0151637    1.69553e-6   3.08338e-6
 1.69553e-6   0.446823    -3.13103e-6
 3.08338e-6  -3.13103e-6   0.716278  

In [99]:
R=A*Q-Q*M

6x3 Array{Float64,2}:
  2.06616e-7   1.5562e-6   -1.42633e-6
  1.87939e-6  -1.70765e-6  -1.43394e-6
 -4.14125e-6   2.06829e-6   3.7911e-6 
  1.77607e-6   1.0333e-6   -2.58071e-6
  2.47296e-6  -1.00309e-6  -2.67145e-6
  2.70217e-7   5.06293e-7  -9.08757e-7

In [100]:
eigvals(M), λ

([0.015163653681256495,0.7162779295540006,0.44682255245602837],[0.015163653655468411,0.4468225524462972,0.7162779294362283,0.9317501758570765,1.6149200635986434,2.275065625006287])

In [101]:
η=abs(eigvals(M)[3]-λ[4])
vecnorm(sinθ), vecnorm(R)/η

(2.3566477335760387e-5,1.7870659763096776e-5)