# Singular Value Decomposition - Perturbation Theory



## Prerequisites

The reader should be familiar with eigenvalue decomposition, singular value decompostion, and perturbation theory for eigenvalue decomposition.

## Competences 

The reader should be able to understand and check the facts about perturbations of singular values and vectors.

## Peturbation bounds

For more details and the proofs of the Facts below, see 
[R.-C. Li, Matrix Perturbation Theory][Hog14], and the references therein.

[Hog14]: #1 "L. Hogben, ed., 'Handbook of Linear Algebra', pp. 21.6-21.8 and 21.16-21.18, CRC Press, Boca Raton, 2014."

### Definitions
Let $A\in\mathbb{C}^{m\times n}$ and let $A=U\Sigma V^*$ be its SVD.

The set of $A$'s singular values is $sv(B)=\{\sigma_1,\sigma_2,\ldots)$, with 
$\sigma_1\geq \sigma_2\geq \cdots\geq 0$, and let 
$sv_{ext}(B)=sv(B)$ unless $m>n$ for which $sv_{ext}(B)=sv(B)\cup \{0,\ldots,0\}$ (additional $|m-n|$ zeros).

Triplet $(u,\sigma,v)\in\times\mathbb{C}^{m}\times\mathbb{R}\times\mathbb{C}^{n}$ is a __singular triplet__ of $A$ if $\|u\|_2=1$, $\|v\|_2=1$, $\sigma\geq 0$, and $Av=\sigma u$ and $A^*u=\sigma v$.

$\tilde A=A+\Delta A$ is a __perturbed matrix__, where $\Delta A$ is __perturbation__.
_The same notation is adopted to $\tilde A$, except all symbols are with tildes._

__Spectral condition number__ of $A$ is $\kappa_2(A)=\sigma_{\max}(A)/ \sigma_{\min}(A)$.

Let $X,Y\in\mathbb{C}^{n\times k}$ with $\mathop{\mathrm{rank}}(X)=\mathop{\mathrm{rank}}(Y)=k$. The __canonical angles__ between their column spaces are $\theta_i=\cos^{-1}\sigma_i$, where $\sigma_i$ are the singular values of 
$(Y^*Y)^{-1/2}Y^*X(X^*X)^{-1/2}$. The __canonical angle matrix__ between $X$ and $Y$ is 

$$\Theta(X,Y)=\mathop{\mathrm{diag}}(\theta_1,\theta_2,\ldots,\theta_k).
$$
    

### Facts

1. __Mirsky Theorem.__ $\|\Sigma-\tilde\Sigma\|_2\leq \|\Delta A\|_2$ and 
$\|\Sigma-\tilde\Sigma\|_F\leq \|\Delta A\|_F$.

2. __Residual bounds.__ Let $\|\tilde u\|_2=\|\tilde v\|_2=1$ and 
$\tilde \mu=\tilde u^* A \tilde v$. Let residuals $r=A\tilde v-\tilde \mu \tilde u$ and $s=A^*\tilde u - \tilde \mu \tilde v$, and let 
$\varepsilon=\max\{\|r\|_2,\|s\|_2\}$. Then $|\tilde \mu -\mu|\leq \varepsilon$ for some singular value $\mu$ of $A$. 

3. The smallest error matrix $\Delta A$ for which $(\tilde u, \tilde \mu, \tilde v)$ is a singular triplet of $\tilde A$ satisfies $\| \Delta A\|_2=\varepsilon$.

4. Let $\mu$ be the closest singular value in $sv_{ext}(A)$ to $\tilde \mu$ and $(u,\mu,v)$
be the associated singular triplet, and let
$$\eta=\mathop{\mathrm{gap}}(\tilde\mu)= \min_{\mu\neq\sigma\in sv_{ext}(A)}|\tilde\mu-\sigma|.$$
If $\eta>0$, then
\begin{align*}
|\tilde\mu-\mu |&\leq \frac{\varepsilon^2}{\eta},\\
\sqrt{\sin^2\theta(u,\tilde u)+ \sin^2\theta(v,\tilde v)} & \leq 
\frac{\sqrt{\|r\|_2^2 + \|s\|_2^2}}{\eta}.
\end{align*}

5. Let 
$$
A=\begin{bmatrix} M & E \\ F & H \end{bmatrix}, \quad 
\tilde A=\begin{bmatrix} M & 0 \\ 0 & H \end{bmatrix},
$$ 
where $M\in\mathbb{C}^{k\times k}$, and set $\eta=\min |\mu-\nu|$ over all $\mu\in sv(M)$ and $\nu\in sv_{ext}(H)$, and $\varepsilon =\max \{ \|E\|_2,\|F\|_2 \}$. Then
$$ 
\max |\sigma_j -\tilde\sigma_j| \leq \frac{2\varepsilon^2}{\eta+\sqrt{\eta^2+4\varepsilon^2}}.
$$

6. Let $m\geq n$ and let
$$
\begin{bmatrix} U_1^*\\ U_2^* \end{bmatrix} A \begin{bmatrix} V_1 & V_2 \end{bmatrix}=
\begin{bmatrix} A_1 &  \\ & A_2 \end{bmatrix}, \quad 
\begin{bmatrix} \tilde U_1^*\\ \tilde U_2^* \end{bmatrix} \tilde A \begin{bmatrix} \tilde V_1 & \tilde V_2 \end{bmatrix}=
\begin{bmatrix} \tilde A_1 &  \\ & \tilde A_2 \end{bmatrix},
$$
where $\begin{bmatrix} U_1 & U_2 \end{bmatrix}$, 
$\begin{bmatrix} V_1 & V_2 \end{bmatrix}$,
$\begin{bmatrix} \tilde U_1 & \tilde U_2 \end{bmatrix}$, and
$\begin{bmatrix} \tilde V_1 & \tilde V_2 \end{bmatrix}$ are unitary, and 
$U_1,\tilde U_1\in \mathbb{C}^{m\times k}$, 
$V_1,\tilde V_1\in \mathbb{C}^{n\times k}$. Set
$$
R=A\tilde V_1-\tilde U_1\tilde A_1,\quad 
S=A^*\tilde U_1-\tilde V_1 \tilde A_1.
$$
Let $\eta=\min|\tilde \mu-\nu|$ over all $\tilde \mu\in sv(\tilde A_1)$ and 
$\nu\in sv_{ext}(A_2)$. If $\eta > 0$, then
$$
\sqrt{\|\sin\Theta(U_1,\tilde U_1)\|_F^2 +
\|\sin\Theta(V_1,\tilde V_1)\|_F^2}
\leq \frac{\sqrt{\|R\|_F^2 + \|S\|_F^2 }}{\eta}.
$$


### Example

In [1]:
import Random
Random.seed!(421)
m=8
n=5
k=min(m,n)
A=rand(-9:9,m,n)

8×5 Array{Int64,2}:
  9  -8  -6  -8   6
 -7  -3  -3  -5   1
 -6   5   4  -4   9
 -6  -9   9   4   2
  6  -3   8   2  -9
 -5   3   4  -9   9
  5   4   6  -6   4
 -3  -1   5   4   3

In [2]:
ΔA=rand(m,n)/100
B=A+ΔA

8×5 Array{Float64,2}:
  9.00708  -7.99113   -5.9908   -7.9925    6.00039
 -6.99401  -2.99656   -2.99585  -4.99217   1.00968
 -5.99831   5.00369    4.00099  -3.99453   9.00176
 -5.99876  -8.99785    9.0021    4.00802   2.00052
  6.00337  -2.99211    8.00542   2.00362  -8.99755
 -4.99083   3.00391    4.00915  -8.99509   9.00952
  5.00833   4.0062     6.00446  -5.99618   4.00705
 -2.99155  -0.997366   5.00548   4.00731   3.00406

In [3]:
using LinearAlgebra
U,σ,V=svd(A)
U₁,σ₁,V₁=svd(B)

SVD{Float64,Float64,Array{Float64,2}}([0.149248 0.696477 … 0.451151 -0.196549; 0.224144 -0.00330314 … 0.409252 0.674625; … ; 0.24481 0.0940152 … -0.473739 0.0171393; 0.0522446 -0.343101 … 0.0807253 -0.425683], [22.715, 19.4395, 14.7481, 13.9792, 7.36631], [-0.356946 0.21649 … -0.535417 0.732047; 0.620365 -0.0384243 … -0.432837 0.0472716; … ; -0.332565 -0.881079 … 0.0553775 0.161166; -0.330458 -0.0668079 … -0.679111 -0.645265])

In [4]:
# Mirsky's Theorems
maximum(abs,σ-σ₁), opnorm(ΔA), norm(σ-σ₁), norm(ΔA)

(0.00799982856752468, 0.03472318158204487, 0.010462619462297785, 0.03749141691124676)

In [5]:
# Residual bounds - how close is (x,ζ,y) to (U[:,j],σ[j],V[:,j])
j=rand(2:k-1)
x=round.(U[:,j],digits=3)
y=round.(V[:,j],digits=3)
x=x/norm(x)
y=y/norm(y)
ζ=(x'*A*y)[]
σ, j, ζ

([22.7144, 19.4392, 14.7417, 13.9812, 7.37431], 4, 13.981196477128567)

In [6]:
# Fact 2
r=A*y-ζ*x
s=A'*x-ζ*y
ϵ=max(norm(r),norm(s))

0.010564193333948667

In [7]:
minimum(abs,σ.-ζ), ϵ

(8.956937342929905e-7, 0.010564193333948667)

In [8]:
# Fact 4
η=min(abs(ζ-σ[j-1]),abs(ζ-σ[j+1]))

0.7605256814865999

In [9]:
ζ-σ[j], ϵ^2/η

(-8.956937342929905e-7, 0.0001467434743017443)

In [10]:
# Eigenvector bound
# cos(θ)
cosθU=dot(x,U[:,j])
cosθV=dot(y,V[:,j])
# Bound
sqrt(1-cosθU^2+1-cosθV^2), sqrt(norm(r)^2+norm(s)^2)/η

(0.0007359748346531112, 0.014416518399856987)

In [11]:
# Fact 5 - we create small off-diagonal block perturbation
j=3
M=A[1:j,1:j]
H=A[j+1:m,j+1:n]
B=cat(M,H,dims=(1,2))

8×5 Array{Int64,2}:
  9  -8  -6   0   0
 -7  -3  -3   0   0
 -6   5   4   0   0
  0   0   0   4   2
  0   0   0   2  -9
  0   0   0  -9   9
  0   0   0  -6   4
  0   0   0   4   3

In [12]:
E=rand(Float64,size(A[1:j,j+1:n]))/100
F=rand(Float64,size(A[j+1:m,1:j]))/100
C=map(Float64,B)
C[1:j,j+1:n]=E
C[j+1:m,1:j]=F
C

8×5 Array{Float64,2}:
  9.0         -8.0          -6.0          0.00521644   0.00229319
 -7.0         -3.0          -3.0          0.00368332   0.00264824
 -6.0          5.0           4.0          0.00130663   0.00403048
  0.00541968   0.00523952    0.0094073    4.0          2.0       
  0.00584898   0.00697791    0.00233598   2.0         -9.0       
  0.00916926   0.00831539    0.00563637  -9.0          9.0       
  0.00512033   0.000574522   0.00351357  -6.0          4.0       
  0.00438309   0.000464975   0.00187312   4.0          3.0       

In [13]:
svdvals(M)

3-element Array{Float64,1}:
 16.166941117157883  
  7.9748473893074925 
  0.17839291355117629

In [14]:
svdvals(H)'

1×2 Adjoint{Float64,Array{Float64,1}}:
 16.6354  8.20136

In [15]:
svdvals(M).-svdvals(H)'

3×2 Array{Float64,2}:
  -0.468496   7.96559 
  -8.66059   -0.226508
 -16.457     -8.02296 

In [16]:
ϵ=max(norm(E), norm(F))
β=svdvals(B)
γ=svdvals(C)
η=minimum(abs,svdvals(M).-svdvals(H)')
[β γ], maximum(abs,β-γ), 2*ϵ^2/(η+sqrt(η^2+4*ϵ^2))

([16.6354 16.6354; 16.1669 16.1669; … ; 7.97485 7.97485; 0.178393 0.178431], 3.7713327345700876e-5, 0.002101834711812092)

## Relative perturbation theory

### Definitions

Matrix $A\in\mathbb{C}^{m\times n}$ is __multiplicatively pertubed__ to $\tilde A$ if
$\tilde A=D_L^* A D_R$ for some $D_L\in\mathbb{C}^{m\times m}$ and 
$D_R\in\mathbb{C}^{n\times n}$. 

Matrix $A$ is (highly) __graded__ if it can be scaled as $A=GS$ such that $\kappa_2(G)$ is of modest magnitude. The __scaling matrix__ $S$ is often diagonal. Interesting cases are when $\kappa_2(G)\ll \kappa_2(A)$.

__Relative distances__ between two complex numbers $\alpha$ and $\tilde \alpha$ are:

\begin{align*}
\zeta(\alpha,\tilde \alpha)&=\frac{|\alpha-\tilde\alpha|}{\sqrt{|\alpha\tilde \alpha|}}, \quad \textrm{for } \alpha\tilde\alpha\neq 0,\\
\varrho(\alpha,\tilde \alpha)&=\frac{|\alpha-\tilde\alpha|}
{\sqrt{|\alpha|^2 +  |\tilde \alpha|^2}}, \quad \textrm{for } |\alpha|+|\tilde\alpha|> 0.
\end{align*}

### Facts

1. If $D_L$ and $D_R$ are non-singular and $m\geq n$, then
\begin{align*}
\frac{\sigma_j}{\|D_L^{-1}\|_2\|D_R^{-1}\|_2}& \leq \tilde\sigma_j \leq
\sigma_j \|D_L\|_2\|D_R\|_2, \quad \textrm{for } i=1,\ldots,n, \\
\| \mathop{\mathrm{diag}}(\zeta(\sigma_1,\tilde \sigma_1),\ldots,
\zeta(\sigma_n,\tilde \sigma_n)\|_{2,F} & \leq
\frac{1}{2}\|D_L^*-D_L^{-1}\|_{2,F} + \frac{1}{2}\|D_R^*-D_R^{-1}\|_{2,F}.
\end{align*}

2. Let $m\geq n$ and let
$$
\begin{bmatrix} U_1^*\\ U_2^* \end{bmatrix} A \begin{bmatrix} V_1 & V_2 \end{bmatrix}=
\begin{bmatrix} A_1 &  \\ & A_2 \end{bmatrix}, \quad 
\begin{bmatrix} \tilde U_1^*\\ \tilde U_2^* \end{bmatrix} \tilde A \begin{bmatrix} \tilde V_1 & \tilde V_2 \end{bmatrix}=
\begin{bmatrix} \tilde A_1 &  \\ & \tilde A_2 \end{bmatrix},
$$
where $\begin{bmatrix} U_1 & U_2 \end{bmatrix}$, 
$\begin{bmatrix} V_1 & V_2 \end{bmatrix}$,
$\begin{bmatrix} \tilde U_1 & \tilde U_2 \end{bmatrix}$, and
$\begin{bmatrix} \tilde V_1 & \tilde V_2 \end{bmatrix}$ are unitary, and 
$U_1,\tilde U_1\in \mathbb{C}^{m\times k}$, 
$V_1,\tilde V_1\in \mathbb{C}^{n\times k}$. Set
$$
R=A\tilde V_1-\tilde U_1\tilde A_1,\quad 
S=A^*\tilde U_1-\tilde V_1 \tilde A_1.
$$
Let $\eta=\min \varrho(\mu,\tilde \mu)$ over all $\mu\in sv(A_1)$ and 
$\tilde \mu\in sv_{ext}(A_2)$. If $\eta > 0$, then
\begin{align*}
& \sqrt{\|\sin\Theta(U_1,\tilde U_1)\|_F^2 +
\|\sin\Theta(V_1,\tilde V_1)\|_F^2} \\
& \leq \frac{1}{\eta}( \|(I-D_L^*)U_1\|_F^2+ \|(I-D_L^{-1})U_1\|_F^2 \\
& \quad +\|(I-D_R^*)V_1\|_F^2+ \|(I-D_R^{-1})V_1\|_F^2 )^{1/2}.
\end{align*}

3. Let $A=GS$ and $\tilde A=\tilde GS$, and let 
$\Delta G=\tilde G-G$. Then $\tilde A=DA$, where $D=I+(\Delta G) G^{\dagger}$, and 
Fact 1 applies with $D_L=D$, $D_R=I$, and 
$$
\|D^*-D^{-1}\|_{2,F} \leq \bigg(1+\frac{1}{1-\|(\Delta G) G^{\dagger}\|_{2}}\bigg)
\frac{\|(\Delta G) G^{\dagger}\|_{2,F}}{2}.
$$
According to the notebook on 
[Jacobi Method and High Relative Accuracy](L4c Symmetric Eigenvalue Decomposition - Jacobi Method and High Relative Accuracy.ipynb), nearly optimal diagonal scaling is such that all columns of $G$ have unit norms, $S=\mathop{\mathrm{diag}} \big( \| A_{:,1}\|_2,\ldots,\|A_{:,n}\|_2 \big)$.

4. Let $A$ be an real upper-bidiagonal matrix with diagonal entries $a_1,a_2,\ldots,a_n$ and 
the super-diagonal entries $b_1,b_2, \ldots,b_{n-1}$. Let the diagonal entries of 
$\tilde A$ be $\alpha_1 a_1,\alpha_2 a_2,\ldots,\alpha_n a_n$, and its super-diagonal entries be
$\beta_1 b_1,\beta_2 b_2,\ldots,\beta_{n-1} b_{n-1}$. Then $\tilde A=D_L^* A D_R$ with 
\begin{align*}
D_L &=\mathop{\mathrm{diag}} \bigg(\alpha_1,\frac{\alpha_1 \alpha_2}{\beta_1},
\frac{\alpha_1 \alpha_2 \alpha_3}{\beta_1 \beta_2},\cdots\bigg),\\
D_R &=\mathop{\mathrm{diag}} \bigg(1, \frac{\beta_1}{\alpha_1},
\frac{\beta_1 \beta_2}{\alpha_1 \alpha_2},\cdots\bigg).
\end{align*}
Let $\alpha=\prod\limits_{j=1}^n \max\{\alpha_j, 1/\alpha_j\}$ and 
$\beta=\prod\limits_{j=1}^{n-1} \max\{\beta_j, 1/\beta_j\}$. Then
$$
(\alpha\beta)^{-1}\leq \| D_L^{-1}\|_2 \|D_R^{-1}\|_2 \leq
\| D_L\|_2 \|D_R\|_2  \leq \alpha\beta,
$$
and Fact 1 applies. This is a result by [Demmel and Kahan](http://www.netlib.org/lapack/lawnspdf/lawn03.pdf).
 
5. Consider the block partitioned matrices
\begin{align*}
A & =\begin{bmatrix} B & C \\ 0 & D\end{bmatrix}, \\
\tilde A & =  \begin{bmatrix} B & 0 \\ 0 & D\end{bmatrix}
=A \begin{bmatrix} I & -B^{-1} C \\ 0 & I \end{bmatrix}\equiv A D_R.
\end{align*}
By Fact 1, $\zeta(\sigma_j,\tilde \sigma_j) \leq \frac{1}{2} \|B^{-1}C\|_2$. This is used as a deflation criterion in the SVD algorithm for bidiagonal matrices.

### Example - Bidiagonal matrix

In order to illustrate Facts 1 to 3, we need an algorithm which computes the singular values with high relative acuracy. Such algorithm, the one-sided Jacobi method, is discussed in the following notebook. 

The algorithm actually used in the function `svdvals()` for `Bidiagonal` is the zero-shift bidiagonal QR algorithm, which attains the accuracy given by Fact 4: if all
$1-\varepsilon \leq \alpha_i,\beta_j \leq 1+\varepsilon$, then
$$
(1-\varepsilon)^{2n-1} \leq (\alpha\beta)^{-1} \leq \alpha\beta \leq (1-\varepsilon)^{2n-1}.
$$
In other words, $\varepsilon$ relative changes in diagonal and super-diagonal elements, cause at most $(2n-1)\varepsilon$ relative changes in the singular values.

__However__, if singular values and vectors are desired, the function `svd()` calls the standard algorithm, described in the next notebook, which __does not attain this accuracy__ .

In [17]:
n=50
δ=100000
# The starting matrix
a=exp.(50*(rand(n).-0.5))
b=exp.(50*(rand(n-1).-0.5))
A=Bidiagonal(a,b,'U')
# Multiplicative perturbation
DL=ones(n)+(rand(n).-0.5)/δ
DR=ones(n)+(rand(n).-0.5)/δ
# The perturbed matrix
α=DL.*a.*DR
β=DL[1:end-1].*b.*DR[2:end]
B=Bidiagonal(α,β,'U')
(A.dv-B.dv)./A.dv

50-element Array{Float64,1}:
 -4.992520753911388e-6 
 -2.7977790984424107e-6
  2.6590624168323442e-6
  6.831499805221434e-6 
  4.149104871814255e-6 
 -1.4085976562169903e-6
  2.778951216380591e-6 
  9.179104419033834e-6 
 -2.2035946717467185e-7
 -8.196786961929508e-6 
 -2.84624047179932e-6  
 -1.832915020986907e-6 
  6.659913785220769e-6 
  ⋮                    
  2.914388817213355e-6 
  3.582284363500114e-6 
 -2.3148627157544815e-6
 -2.980259849966326e-6 
 -5.592953339158236e-6 
 -5.557812482481944e-9 
 -4.357208500332647e-7 
 -5.0805008087282724e-6
  5.465052788114942e-6 
  2.6336643393668867e-7
 -3.2703312497147747e-6
 -6.8275808581655436e-6

In [18]:
(a-α)./a, (b-β)./b

([-4.99252e-6, -2.79778e-6, 2.65906e-6, 6.8315e-6, 4.1491e-6, -1.4086e-6, 2.77895e-6, 9.1791e-6, -2.20359e-7, -8.19679e-6  …  -2.31486e-6, -2.98026e-6, -5.59295e-6, -5.55781e-9, -4.35721e-7, -5.0805e-6, 5.46505e-6, 2.63366e-7, -3.27033e-6, -6.82758e-6], [-8.55547e-6, 4.21726e-6, 3.1856e-6, 5.02104e-6, -2.15784e-6, 2.16843e-6, 8.67916e-6, 3.1619e-6, -2.33646e-6, -5.56656e-6  …  1.86283e-6, 2.55659e-6, -8.80213e-6, -5.4456e-6, 8.37035e-6, -5.37989e-6, 1.87583e-7, 5.94104e-7, 5.82796e-7, -5.3759e-6])

In [19]:
@which svdvals(A)

svdvals(A::AbstractArray{#s571,2} where #s571<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/svd.jl:165

In [20]:
σ=svdvals(A)
μ=svdvals(B)
[σ (σ-μ)./σ]

50×2 Array{Float64,2}:
 3.40078e9     5.82351e-7
 7.36508e8    -5.55733e-9
 4.70154e8    -5.59295e-6
 3.44534e8     9.3746e-6 
 9.8205e7     -5.2759e-7 
 5.52383e7     5.46505e-6
 5.3739e7      2.65906e-6
 1.85736e7     2.77895e-6
 1.34581e7    -2.26233e-6
 1.16407e7    -1.02195e-9
 3.3998e6     -5.11021e-6
 1.89901e6    -3.31652e-6
 1.33922e6     4.1491e-6 
 ⋮                       
 0.000135607  -1.17994e-6
 4.51178e-6   -2.68009e-6
 1.43836e-6    9.1791e-6 
 2.22915e-8   -1.83292e-6
 5.53813e-9    2.54776e-6
 3.12743e-9   -5.49369e-6
 4.11692e-10   5.96403e-7
 2.41415e-11  -1.4086e-6 
 1.58249e-11  -5.0406e-6 
 1.40086e-12  -7.84291e-6
 2.03616e-25   3.67804e-6
 1.77974e-27   8.8293e-7 

In [21]:
cond(A)

1.9108287046553626e36

In [22]:
# The standard algorithm
U,ν,V=svd(A);

In [23]:
(σ-ν)./σ

50-element Array{Float64,1}:
      5.608556811127367e-16 
     -1.6185749018692682e-16
      0.0                   
      0.0                   
      1.5173529140016301e-16
     -1.3488061837777467e-16
      0.0                   
      0.0                   
      0.0                   
      0.0                   
      0.0                   
      0.0                   
      0.0                   
      ⋮                     
      1.653579079720307e-7  
      0.0                   
     -5.084310710613914e-10 
    -14.233124551484504     
    -60.31483778083099      
   -107.57771542294151      
   -823.8130308863146       
 -14064.763999126983        
 -21454.949212747277        
   -148.36866319444985      
    -28.373263514934052     
   -124.78402584557277      